// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bin_conv_1,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.749500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=40,HLS_SYN_DSP=0,HLS_SYN_FF=4363,HLS_SYN_LUT=23062,HLS_VERSION=2018_2}" *)

module bin_conv_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_V_V,
        Input_1_V_V_ap_vld,
        Input_1_V_V_ap_ack,
        Input_2_V_V,
        Input_2_V_V_ap_vld,
        Input_2_V_V_ap_ack,
        Output_1_V_V,
        Output_1_V_V_ap_vld,
        Output_1_V_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_pp2_stage0 = 12'd1024;
parameter    ap_ST_fsm_state13 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] Input_1_V_V;
input   Input_1_V_V_ap_vld;
output   Input_1_V_V_ap_ack;
input  [63:0] Input_2_V_V;
input   Input_2_V_V_ap_vld;
output   Input_2_V_V_ap_ack;
output  [63:0] Output_1_V_V;
output   Output_1_V_V_ap_vld;
input   Output_1_V_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Input_1_V_V_ap_ack;
reg Input_2_V_V_ap_ack;
reg Output_1_V_V_ap_vld;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] bin_conv_cnt;
wire   [2:0] o_index_list_address0;
reg    o_index_list_ce0;
wire   [8:0] o_index_list_q0;
wire   [2:0] n_outputs_list_address0;
reg    n_outputs_list_ce0;
wire   [7:0] n_outputs_list_q0;
wire   [2:0] d_i_idx_list_V_address0;
reg    d_i_idx_list_V_ce0;
wire   [0:0] d_i_idx_list_V_q0;
wire   [2:0] d_o_idx_list_V_address0;
reg    d_o_idx_list_V_ce0;
wire   [0:0] d_o_idx_list_V_q0;
wire   [2:0] n_inputs_list_address0;
reg    n_inputs_list_ce0;
wire   [9:0] n_inputs_list_q0;
wire   [2:0] width_mode_list_address0;
reg    width_mode_list_ce0;
wire   [0:0] width_mode_list_q0;
wire   [2:0] norm_mode_list_address0;
reg    norm_mode_list_ce0;
wire   [1:0] norm_mode_list_q0;
reg   [9:0] dmem_V_0_0_address0;
reg    dmem_V_0_0_ce0;
reg    dmem_V_0_0_we0;
reg   [63:0] dmem_V_0_0_d0;
wire   [63:0] dmem_V_0_0_q0;
reg   [9:0] dmem_V_0_1_address0;
reg    dmem_V_0_1_ce0;
reg    dmem_V_0_1_we0;
reg   [63:0] dmem_V_0_1_d0;
wire   [63:0] dmem_V_0_1_q0;
reg   [9:0] dmem_V_1_0_address0;
reg    dmem_V_1_0_ce0;
reg    dmem_V_1_0_we0;
reg   [63:0] dmem_V_1_0_d0;
wire   [63:0] dmem_V_1_0_q0;
reg   [9:0] dmem_V_1_1_address0;
reg    dmem_V_1_1_ce0;
reg    dmem_V_1_1_we0;
reg   [63:0] dmem_V_1_1_d0;
wire   [63:0] dmem_V_1_1_q0;
reg    Input_1_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_1_fu_549_p2;
reg    Input_2_V_V_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_flatten1_fu_571_p2;
reg    Output_1_V_V_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] exitcond_flatten3_reg_1321;
reg   [12:0] indvar_flatten2_reg_451;
reg   [1:0] dmem_i5_reg_462;
reg   [12:0] indvar_flatten3_reg_473;
reg   [1:0] dmem_j6_reg_484;
reg   [10:0] dmem_k7_reg_495;
reg   [31:0] bin_conv_cnt_load_reg_1134;
wire   [63:0] tmp_s_fu_539_p1;
reg   [63:0] tmp_s_reg_1141;
reg   [8:0] o_index_V_reg_1160;
wire    ap_CS_fsm_state2;
wire   [9:0] o_index_V_cast_fu_545_p1;
reg   [9:0] o_index_V_cast_reg_1165;
reg   [7:0] n_outputs_V_reg_1170;
wire   [6:0] kh_i_1_fu_555_p2;
reg    ap_block_state3;
wire   [0:0] tmp_2_fu_566_p2;
wire    ap_CS_fsm_state4;
wire   [12:0] indvar_flatten_next1_fu_577_p2;
reg    ap_block_state5;
wire   [1:0] dmem_i_t_mid2_v_fu_603_p3;
wire   [1:0] dmem_j_mid2_fu_675_p3;
wire   [10:0] dmem_k_1_fu_691_p2;
wire   [12:0] indvar_flatten_next_fu_703_p3;
wire    ap_CS_fsm_state6;
wire   [7:0] tmp_13_fu_714_p2;
reg   [7:0] tmp_13_reg_1246;
reg   [0:0] d_i_idx_list_V_load_reg_1251;
wire    ap_CS_fsm_state7;
reg   [0:0] d_o_idx_list_V_load_reg_1256;
reg   [9:0] n_inputs_list_load_reg_1261;
reg   [0:0] width_mode_list_load_reg_1266;
reg   [1:0] norm_mode_list_load_reg_1271;
wire   [0:0] exitcond_fu_723_p2;
wire    ap_CS_fsm_state8;
wire   [7:0] kh_index_V_fu_728_p2;
reg   [7:0] kh_index_V_reg_1280;
wire   [1:0] off_V_fu_749_p1;
reg   [1:0] off_V_reg_1290;
wire   [0:0] this_assign_1_fu_753_p2;
reg   [0:0] this_assign_1_reg_1297;
wire   [0:0] tmp_5_fu_759_p2;
wire   [15:0] nc_V_fu_865_p3;
reg   [15:0] nc_V_reg_1306;
wire    ap_CS_fsm_state9;
wire   [9:0] o_index_V_1_fu_874_p2;
reg   [9:0] o_index_V_1_reg_1311;
wire   [0:0] sel_tmp3_fu_894_p2;
reg   [0:0] sel_tmp3_reg_1316;
wire    ap_block_state11_pp2_stage0_iter0;
wire    ap_block_state12_pp2_stage0_iter1;
reg    ap_sig_ioackin_Output_1_V_V_ap_ack;
reg    ap_block_state12_io;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] exitcond_flatten3_fu_906_p2;
wire   [12:0] indvar_flatten_next3_fu_912_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] dmem_i5_t_mid2_fu_942_p3;
reg   [0:0] dmem_i5_t_mid2_reg_1330;
wire   [0:0] not_exitcond_flatten_2_fu_964_p2;
reg   [0:0] not_exitcond_flatten_2_reg_1335;
wire   [0:0] tmp_15_mid_fu_982_p2;
reg   [0:0] tmp_15_mid_reg_1340;
wire   [1:0] dmem_i5_mid2_fu_988_p3;
wire   [0:0] sel_tmp3_mid1_fu_1020_p2;
reg   [0:0] sel_tmp3_mid1_reg_1350;
wire   [0:0] sel_tmp4_mid2_fu_1032_p3;
reg   [0:0] sel_tmp4_mid2_reg_1355;
wire   [1:0] dmem_j6_mid2_fu_1040_p3;
wire   [10:0] dmem_k_2_fu_1056_p2;
wire   [12:0] indvar_flatten_next2_fu_1068_p3;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state11;
reg   [5:0] kh_mem_V_address0;
reg    kh_mem_V_ce0;
reg    kh_mem_V_we0;
wire   [63:0] kh_mem_V_q0;
wire    grp_bin_conv_fu_506_ap_start;
wire    grp_bin_conv_fu_506_ap_done;
wire    grp_bin_conv_fu_506_ap_idle;
wire    grp_bin_conv_fu_506_ap_ready;
wire    grp_bin_conv_fu_506_Input_1_V_V_ap_ack;
wire   [9:0] grp_bin_conv_fu_506_dmem_0_0_V_address0;
wire    grp_bin_conv_fu_506_dmem_0_0_V_ce0;
wire    grp_bin_conv_fu_506_dmem_0_0_V_we0;
wire   [63:0] grp_bin_conv_fu_506_dmem_0_0_V_d0;
wire   [9:0] grp_bin_conv_fu_506_dmem_0_1_V_address0;
wire    grp_bin_conv_fu_506_dmem_0_1_V_ce0;
wire    grp_bin_conv_fu_506_dmem_0_1_V_we0;
wire   [63:0] grp_bin_conv_fu_506_dmem_0_1_V_d0;
wire   [9:0] grp_bin_conv_fu_506_dmem_1_0_V_address0;
wire    grp_bin_conv_fu_506_dmem_1_0_V_ce0;
wire    grp_bin_conv_fu_506_dmem_1_0_V_we0;
wire   [63:0] grp_bin_conv_fu_506_dmem_1_0_V_d0;
wire   [9:0] grp_bin_conv_fu_506_dmem_1_1_V_address0;
wire    grp_bin_conv_fu_506_dmem_1_1_V_ce0;
wire    grp_bin_conv_fu_506_dmem_1_1_V_we0;
wire   [63:0] grp_bin_conv_fu_506_dmem_1_1_V_d0;
wire    grp_bin_conv_fu_506_width_mode_V;
reg   [6:0] kh_i_reg_364;
reg   [12:0] indvar_flatten1_reg_375;
reg   [1:0] dmem_i_reg_386;
reg   [12:0] indvar_flatten_reg_397;
reg   [1:0] dmem_j_reg_408;
reg   [10:0] dmem_k_reg_419;
reg   [9:0] t_V_1_reg_430;
wire    ap_CS_fsm_state10;
reg   [7:0] t_V_reg_440;
reg    grp_bin_conv_fu_506_ap_start_reg;
wire   [63:0] tmp_3_fu_561_p1;
wire   [63:0] tmp_4_fu_683_p1;
wire   [63:0] tmp_i_fu_744_p1;
wire   [63:0] tmp_10_fu_1048_p1;
wire   [31:0] p_s_fu_1120_p3;
wire    ap_CS_fsm_state13;
wire    ap_block_pp2_stage0_01001;
reg    ap_reg_ioackin_Output_1_V_V_ap_ack;
wire   [0:0] tmp_1036_fu_611_p1;
wire   [0:0] dmem_j_t_mid2_fu_667_p3;
wire   [0:0] exitcond_flatten_fu_583_p2;
wire   [1:0] dmem_i_s_fu_597_p2;
wire   [0:0] tmp_1037_fu_621_p1;
wire   [0:0] not_exitcond_flatten_fu_615_p2;
wire   [0:0] tmp_6_fu_631_p2;
wire   [1:0] dmem_j_mid_fu_589_p3;
wire   [0:0] tmp_9_mid_fu_637_p2;
wire   [0:0] tmp_9_fu_649_p2;
wire   [1:0] dmem_j_1_fu_643_p2;
wire   [0:0] tmp_1038_fu_663_p1;
wire   [0:0] dmem_j_t_mid_fu_625_p2;
wire   [10:0] dmem_k_mid2_fu_655_p3;
wire   [12:0] indvar_flatten_op_fu_697_p2;
wire   [7:0] tmp_1039_fu_711_p1;
wire   [7:0] tmp_1040_fu_719_p1;
wire   [5:0] r_V_fu_734_p4;
wire   [0:0] tmp_3_i_fu_764_p2;
wire   [0:0] tmp_4_i_fu_773_p2;
wire   [0:0] sel_tmp1_fu_813_p2;
wire   [0:0] sel_tmp6_demorgan_fu_825_p2;
wire   [0:0] tmp_5_i_fu_788_p2;
wire   [0:0] sel_tmp6_fu_831_p2;
wire   [0:0] sel_tmp7_fu_837_p2;
wire   [15:0] loc_V_2_fu_793_p4;
wire   [15:0] loc_V_1_fu_778_p4;
wire   [0:0] sel_tmp2_fu_819_p2;
wire   [15:0] loc_V_fu_769_p1;
wire   [15:0] loc_V_3_fu_803_p4;
wire   [0:0] or_cond_fu_851_p2;
wire   [15:0] newSel_fu_843_p3;
wire   [15:0] newSel1_fu_857_p3;
wire   [0:0] tmp_1043_fu_880_p1;
wire   [0:0] tmp_1044_fu_890_p1;
wire   [0:0] sel_tmp_fu_884_p2;
wire   [0:0] exitcond_flatten2_fu_918_p2;
wire   [1:0] dmem_i_1_fu_932_p2;
wire   [0:0] tmp_1045_fu_938_p1;
wire   [0:0] sel_tmp_mid1_fu_950_p2;
wire   [0:0] sel_tmp4_fu_900_p2;
wire   [0:0] tmp_14_fu_976_p2;
wire   [1:0] dmem_j6_mid_fu_924_p3;
wire   [0:0] tmp_15_fu_1002_p2;
wire   [1:0] dmem_j_2_fu_996_p2;
wire   [0:0] tmp_1046_fu_1016_p1;
wire   [0:0] sel_tmp_mid2_fu_956_p3;
wire   [0:0] sel_tmp4_mid1_fu_1026_p2;
wire   [0:0] sel_tmp4_mid_fu_970_p2;
wire   [10:0] dmem_k7_mid2_fu_1008_p3;
wire   [12:0] indvar_flatten20_op_fu_1062_p2;
wire   [0:0] sel_tmp3_mid_fu_1076_p2;
wire   [0:0] sel_tmp3_mid2_fu_1080_p3;
wire   [63:0] newSel3_fu_1086_p3;
wire   [63:0] newSel4_fu_1093_p3;
wire   [31:0] tmp_11_fu_1109_p2;
wire   [0:0] tmp_12_fu_1114_p2;
reg   [11:0] ap_NS_fsm;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_condition_901;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 bin_conv_cnt = 32'd0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 grp_bin_conv_fu_506_ap_start_reg = 1'b0;
#0 ap_reg_ioackin_Output_1_V_V_ap_ack = 1'b0;
end

bin_conv_1_o_indeeOg #(
    .DataWidth( 9 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
o_index_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(o_index_list_address0),
    .ce0(o_index_list_ce0),
    .q0(o_index_list_q0)
);

bin_conv_1_n_outpfYi #(
    .DataWidth( 8 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
n_outputs_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(n_outputs_list_address0),
    .ce0(n_outputs_list_ce0),
    .q0(n_outputs_list_q0)
);

bin_conv_1_d_i_idg8j #(
    .DataWidth( 1 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
d_i_idx_list_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(d_i_idx_list_V_address0),
    .ce0(d_i_idx_list_V_ce0),
    .q0(d_i_idx_list_V_q0)
);

bin_conv_1_d_o_idhbi #(
    .DataWidth( 1 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
d_o_idx_list_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(d_o_idx_list_V_address0),
    .ce0(d_o_idx_list_V_ce0),
    .q0(d_o_idx_list_V_q0)
);

bin_conv_1_n_inpuibs #(
    .DataWidth( 10 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
n_inputs_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(n_inputs_list_address0),
    .ce0(n_inputs_list_ce0),
    .q0(n_inputs_list_q0)
);

bin_conv_1_width_jbC #(
    .DataWidth( 1 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
width_mode_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(width_mode_list_address0),
    .ce0(width_mode_list_ce0),
    .q0(width_mode_list_q0)
);

bin_conv_1_norm_mkbM #(
    .DataWidth( 2 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
norm_mode_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(norm_mode_list_address0),
    .ce0(norm_mode_list_ce0),
    .q0(norm_mode_list_q0)
);

bin_conv_1_dmem_VlbW #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_0_address0),
    .ce0(dmem_V_0_0_ce0),
    .we0(dmem_V_0_0_we0),
    .d0(dmem_V_0_0_d0),
    .q0(dmem_V_0_0_q0)
);

bin_conv_1_dmem_VlbW #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_1_address0),
    .ce0(dmem_V_0_1_ce0),
    .we0(dmem_V_0_1_we0),
    .d0(dmem_V_0_1_d0),
    .q0(dmem_V_0_1_q0)
);

bin_conv_1_dmem_VlbW #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_0_address0),
    .ce0(dmem_V_1_0_ce0),
    .we0(dmem_V_1_0_we0),
    .d0(dmem_V_1_0_d0),
    .q0(dmem_V_1_0_q0)
);

bin_conv_1_dmem_VlbW #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_1_address0),
    .ce0(dmem_V_1_1_ce0),
    .we0(dmem_V_1_1_we0),
    .d0(dmem_V_1_1_d0),
    .q0(dmem_V_1_1_q0)
);

bin_conv_1_kh_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kh_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kh_mem_V_address0),
    .ce0(kh_mem_V_ce0),
    .we0(kh_mem_V_we0),
    .d0(Input_1_V_V),
    .q0(kh_mem_V_q0)
);

bin_conv grp_bin_conv_fu_506(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_conv_fu_506_ap_start),
    .ap_done(grp_bin_conv_fu_506_ap_done),
    .ap_idle(grp_bin_conv_fu_506_ap_idle),
    .ap_ready(grp_bin_conv_fu_506_ap_ready),
    .Input_1_V_V(Input_1_V_V),
    .Input_1_V_V_ap_vld(Input_1_V_V_ap_vld),
    .Input_1_V_V_ap_ack(grp_bin_conv_fu_506_Input_1_V_V_ap_ack),
    .nc_V(nc_V_reg_1306),
    .dmem_0_0_V_address0(grp_bin_conv_fu_506_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_bin_conv_fu_506_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_bin_conv_fu_506_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_bin_conv_fu_506_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_bin_conv_fu_506_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_bin_conv_fu_506_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_bin_conv_fu_506_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_bin_conv_fu_506_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_bin_conv_fu_506_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_bin_conv_fu_506_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_bin_conv_fu_506_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_bin_conv_fu_506_dmem_1_0_V_d0),
    .dmem_1_0_V_q0(dmem_V_1_0_q0),
    .dmem_1_1_V_address0(grp_bin_conv_fu_506_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_bin_conv_fu_506_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_bin_conv_fu_506_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_bin_conv_fu_506_dmem_1_1_V_d0),
    .dmem_1_1_V_q0(dmem_V_1_1_q0),
    .d_i_idx_V(d_i_idx_list_V_load_reg_1251),
    .d_o_idx_V(d_o_idx_list_V_load_reg_1256),
    .n_inputs(n_inputs_list_load_reg_1261),
    .o_index_V(t_V_1_reg_430),
    .new_batch_V(this_assign_1_reg_1297),
    .width_mode_V(grp_bin_conv_fu_506_width_mode_V),
    .norm_mode_V(norm_mode_list_load_reg_1271)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state11) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state11))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state11);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_901)) begin
            if ((1'b0 == ap_block_pp2_stage0_11001)) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
            end else if (((1'b0 == ap_block_pp2_stage0_01001) & (1'b1 == Output_1_V_V_ap_ack))) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bin_conv_fu_506_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_bin_conv_fu_506_ap_start_reg <= 1'b1;
        end else if ((grp_bin_conv_fu_506_ap_ready == 1'b1)) begin
            grp_bin_conv_fu_506_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_i5_reg_462 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_906_p2 == 1'd0))) begin
        dmem_i5_reg_462 <= dmem_i5_mid2_fu_988_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_566_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_i_reg_386 <= 2'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_i_reg_386 <= dmem_i_t_mid2_v_fu_603_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_j6_reg_484 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_906_p2 == 1'd0))) begin
        dmem_j6_reg_484 <= dmem_j6_mid2_fu_1040_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_566_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_j_reg_408 <= 2'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_j_reg_408 <= dmem_j_mid2_fu_675_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_k7_reg_495 <= 11'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_906_p2 == 1'd0))) begin
        dmem_k7_reg_495 <= dmem_k_2_fu_1056_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_566_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_k_reg_419 <= 11'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_k_reg_419 <= dmem_k_1_fu_691_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_566_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten1_reg_375 <= 13'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        indvar_flatten1_reg_375 <= indvar_flatten_next1_fu_577_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten2_reg_451 <= 13'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_906_p2 == 1'd0))) begin
        indvar_flatten2_reg_451 <= indvar_flatten_next3_fu_912_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten3_reg_473 <= 13'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_906_p2 == 1'd0))) begin
        indvar_flatten3_reg_473 <= indvar_flatten_next2_fu_1068_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_566_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten_reg_397 <= 13'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        indvar_flatten_reg_397 <= indvar_flatten_next_fu_703_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_549_p2 == 1'd0))) begin
        kh_i_reg_364 <= kh_i_1_fu_555_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        kh_i_reg_364 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        t_V_1_reg_430 <= o_index_V_1_reg_1311;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_1_reg_430 <= o_index_V_cast_reg_1165;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        t_V_reg_440 <= kh_index_V_reg_1280;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_440 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        bin_conv_cnt <= p_s_fu_1120_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bin_conv_cnt_load_reg_1134 <= bin_conv_cnt;
        tmp_s_reg_1141[31 : 0] <= tmp_s_fu_539_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_idx_list_V_load_reg_1251 <= d_i_idx_list_V_q0;
        d_o_idx_list_V_load_reg_1256 <= d_o_idx_list_V_q0;
        n_inputs_list_load_reg_1261 <= n_inputs_list_q0;
        norm_mode_list_load_reg_1271 <= norm_mode_list_q0;
        width_mode_list_load_reg_1266 <= width_mode_list_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_906_p2 == 1'd0))) begin
        dmem_i5_t_mid2_reg_1330 <= dmem_i5_t_mid2_fu_942_p3;
        not_exitcond_flatten_2_reg_1335 <= not_exitcond_flatten_2_fu_964_p2;
        sel_tmp3_mid1_reg_1350 <= sel_tmp3_mid1_fu_1020_p2;
        sel_tmp4_mid2_reg_1355 <= sel_tmp4_mid2_fu_1032_p3;
        tmp_15_mid_reg_1340 <= tmp_15_mid_fu_982_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        exitcond_flatten3_reg_1321 <= exitcond_flatten3_fu_906_p2;
        sel_tmp3_reg_1316 <= sel_tmp3_fu_894_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kh_index_V_reg_1280 <= kh_index_V_fu_728_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        n_outputs_V_reg_1170 <= n_outputs_list_q0;
        o_index_V_cast_reg_1165[8 : 0] <= o_index_V_cast_fu_545_p1[8 : 0];
        o_index_V_reg_1160 <= o_index_list_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        nc_V_reg_1306 <= nc_V_fu_865_p3;
        o_index_V_1_reg_1311 <= o_index_V_1_fu_874_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond_fu_723_p2 == 1'd0))) begin
        off_V_reg_1290 <= off_V_fu_749_p1;
        this_assign_1_reg_1297 <= this_assign_1_fu_753_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_13_reg_1246 <= tmp_13_fu_714_p2;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_549_p2 == 1'd0))) begin
        Input_1_V_V_ap_ack = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        Input_1_V_V_ap_ack = grp_bin_conv_fu_506_Input_1_V_V_ap_ack;
    end else begin
        Input_1_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_549_p2 == 1'd0))) begin
        Input_1_V_V_blk_n = Input_1_V_V_ap_vld;
    end else begin
        Input_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        Input_2_V_V_ap_ack = 1'b1;
    end else begin
        Input_2_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        Input_2_V_V_blk_n = Input_2_V_V_ap_vld;
    end else begin
        Input_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_01001) & (ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_reg_1321 == 1'd0))) begin
        Output_1_V_V_ap_vld = 1'b1;
    end else begin
        Output_1_V_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0) & (exitcond_flatten3_reg_1321 == 1'd0))) begin
        Output_1_V_V_blk_n = Output_1_V_V_ap_ack;
    end else begin
        Output_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond_flatten3_fu_906_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0)) begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = Output_1_V_V_ap_ack;
    end else begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_idx_list_V_ce0 = 1'b1;
    end else begin
        d_i_idx_list_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_idx_list_V_ce0 = 1'b1;
    end else begin
        d_o_idx_list_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_0_address0 = tmp_10_fu_1048_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_0_address0 = tmp_4_fu_683_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_address0 = grp_bin_conv_fu_506_dmem_0_0_V_address0;
    end else begin
        dmem_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_0_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_ce0 = grp_bin_conv_fu_506_dmem_0_0_V_ce0;
    end else begin
        dmem_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_0_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_d0 = grp_bin_conv_fu_506_dmem_0_0_V_d0;
    end else begin
        dmem_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (dmem_j_t_mid2_fu_667_p3 == 1'd0) & (tmp_1036_fu_611_p1 == 1'd0) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_V_0_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_we0 = grp_bin_conv_fu_506_dmem_0_0_V_we0;
    end else begin
        dmem_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_1_address0 = tmp_10_fu_1048_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_1_address0 = tmp_4_fu_683_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_address0 = grp_bin_conv_fu_506_dmem_0_1_V_address0;
    end else begin
        dmem_V_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_0_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_ce0 = grp_bin_conv_fu_506_dmem_0_1_V_ce0;
    end else begin
        dmem_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_1_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_d0 = grp_bin_conv_fu_506_dmem_0_1_V_d0;
    end else begin
        dmem_V_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (dmem_j_t_mid2_fu_667_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_1036_fu_611_p1 == 1'd0) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_V_0_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_we0 = grp_bin_conv_fu_506_dmem_0_1_V_we0;
    end else begin
        dmem_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_0_address0 = tmp_10_fu_1048_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_0_address0 = tmp_4_fu_683_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_address0 = grp_bin_conv_fu_506_dmem_1_0_V_address0;
    end else begin
        dmem_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_1_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_ce0 = grp_bin_conv_fu_506_dmem_1_0_V_ce0;
    end else begin
        dmem_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_0_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_d0 = grp_bin_conv_fu_506_dmem_1_0_V_d0;
    end else begin
        dmem_V_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (tmp_1036_fu_611_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (dmem_j_t_mid2_fu_667_p3 == 1'd0) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_V_1_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_we0 = grp_bin_conv_fu_506_dmem_1_0_V_we0;
    end else begin
        dmem_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_1_address0 = tmp_10_fu_1048_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_1_address0 = tmp_4_fu_683_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_address0 = grp_bin_conv_fu_506_dmem_1_1_V_address0;
    end else begin
        dmem_V_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_ce0 = grp_bin_conv_fu_506_dmem_1_1_V_ce0;
    end else begin
        dmem_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_1_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_d0 = grp_bin_conv_fu_506_dmem_1_1_V_d0;
    end else begin
        dmem_V_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (dmem_j_t_mid2_fu_667_p3 == 1'd1) & (tmp_1036_fu_611_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
        dmem_V_1_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_we0 = grp_bin_conv_fu_506_dmem_1_1_V_we0;
    end else begin
        dmem_V_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kh_mem_V_address0 = tmp_i_fu_744_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kh_mem_V_address0 = tmp_3_fu_561_p1;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3)))) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_549_p2 == 1'd0))) begin
        kh_mem_V_we0 = 1'b1;
    end else begin
        kh_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        n_inputs_list_ce0 = 1'b1;
    end else begin
        n_inputs_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        n_outputs_list_ce0 = 1'b1;
    end else begin
        n_outputs_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        norm_mode_list_ce0 = 1'b1;
    end else begin
        norm_mode_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_index_list_ce0 = 1'b1;
    end else begin
        o_index_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        width_mode_list_ce0 = 1'b1;
    end else begin
        width_mode_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_549_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_549_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((tmp_2_fu_566_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_571_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((tmp_5_fu_759_p2 == 1'd1) & (exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((exitcond_fu_723_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8) & (tmp_5_fu_759_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_bin_conv_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond_flatten3_fu_906_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond_flatten3_fu_906_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_1_V_V = ((dmem_i5_t_mid2_reg_1330[0:0] === 1'b1) ? newSel3_fu_1086_p3 : newSel4_fu_1093_p3);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_state11_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_io = ((ap_sig_ioackin_Output_1_V_V_ap_ack == 1'b0) & (exitcond_flatten3_reg_1321 == 1'd0));
end

assign ap_block_state12_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3 = ((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_549_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state5 = ((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_571_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_901 = ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_reg_1321 == 1'd0));
end

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign d_i_idx_list_V_address0 = tmp_s_reg_1141;

assign d_o_idx_list_V_address0 = tmp_s_reg_1141;

assign dmem_i5_mid2_fu_988_p3 = ((exitcond_flatten2_fu_918_p2[0:0] === 1'b1) ? dmem_i_1_fu_932_p2 : dmem_i5_reg_462);

assign dmem_i5_t_mid2_fu_942_p3 = ((exitcond_flatten2_fu_918_p2[0:0] === 1'b1) ? tmp_1045_fu_938_p1 : tmp_1043_fu_880_p1);

assign dmem_i_1_fu_932_p2 = (2'd1 + dmem_i5_reg_462);

assign dmem_i_s_fu_597_p2 = (2'd1 + dmem_i_reg_386);

assign dmem_i_t_mid2_v_fu_603_p3 = ((exitcond_flatten_fu_583_p2[0:0] === 1'b1) ? dmem_i_s_fu_597_p2 : dmem_i_reg_386);

assign dmem_j6_mid2_fu_1040_p3 = ((tmp_15_mid_fu_982_p2[0:0] === 1'b1) ? dmem_j_2_fu_996_p2 : dmem_j6_mid_fu_924_p3);

assign dmem_j6_mid_fu_924_p3 = ((exitcond_flatten2_fu_918_p2[0:0] === 1'b1) ? 2'd0 : dmem_j6_reg_484);

assign dmem_j_1_fu_643_p2 = (2'd1 + dmem_j_mid_fu_589_p3);

assign dmem_j_2_fu_996_p2 = (2'd1 + dmem_j6_mid_fu_924_p3);

assign dmem_j_mid2_fu_675_p3 = ((tmp_9_mid_fu_637_p2[0:0] === 1'b1) ? dmem_j_1_fu_643_p2 : dmem_j_mid_fu_589_p3);

assign dmem_j_mid_fu_589_p3 = ((exitcond_flatten_fu_583_p2[0:0] === 1'b1) ? 2'd0 : dmem_j_reg_408);

assign dmem_j_t_mid2_fu_667_p3 = ((tmp_9_mid_fu_637_p2[0:0] === 1'b1) ? tmp_1038_fu_663_p1 : dmem_j_t_mid_fu_625_p2);

assign dmem_j_t_mid_fu_625_p2 = (tmp_1037_fu_621_p1 & not_exitcond_flatten_fu_615_p2);

assign dmem_k7_mid2_fu_1008_p3 = ((tmp_15_fu_1002_p2[0:0] === 1'b1) ? 11'd0 : dmem_k7_reg_495);

assign dmem_k_1_fu_691_p2 = (dmem_k_mid2_fu_655_p3 + 11'd1);

assign dmem_k_2_fu_1056_p2 = (11'd1 + dmem_k7_mid2_fu_1008_p3);

assign dmem_k_mid2_fu_655_p3 = ((tmp_9_fu_649_p2[0:0] === 1'b1) ? 11'd0 : dmem_k_reg_419);

assign exitcond_flatten1_fu_571_p2 = ((indvar_flatten1_reg_375 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_918_p2 = ((indvar_flatten3_reg_473 == 13'd2048) ? 1'b1 : 1'b0);

assign exitcond_flatten3_fu_906_p2 = ((indvar_flatten2_reg_451 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_583_p2 = ((indvar_flatten_reg_397 == 13'd2048) ? 1'b1 : 1'b0);

assign exitcond_fu_723_p2 = ((tmp_1040_fu_719_p1 == tmp_13_reg_1246) ? 1'b1 : 1'b0);

assign grp_bin_conv_fu_506_ap_start = grp_bin_conv_fu_506_ap_start_reg;

assign grp_bin_conv_fu_506_width_mode_V = width_mode_list_load_reg_1266;

assign indvar_flatten20_op_fu_1062_p2 = (13'd1 + indvar_flatten3_reg_473);

assign indvar_flatten_next1_fu_577_p2 = (indvar_flatten1_reg_375 + 13'd1);

assign indvar_flatten_next2_fu_1068_p3 = ((exitcond_flatten2_fu_918_p2[0:0] === 1'b1) ? 13'd1 : indvar_flatten20_op_fu_1062_p2);

assign indvar_flatten_next3_fu_912_p2 = (13'd1 + indvar_flatten2_reg_451);

assign indvar_flatten_next_fu_703_p3 = ((exitcond_flatten_fu_583_p2[0:0] === 1'b1) ? 13'd1 : indvar_flatten_op_fu_697_p2);

assign indvar_flatten_op_fu_697_p2 = (indvar_flatten_reg_397 + 13'd1);

assign kh_i_1_fu_555_p2 = (kh_i_reg_364 + 7'd1);

assign kh_index_V_fu_728_p2 = (8'd1 + t_V_reg_440);

assign loc_V_1_fu_778_p4 = {{kh_mem_V_q0[31:16]}};

assign loc_V_2_fu_793_p4 = {{kh_mem_V_q0[47:32]}};

assign loc_V_3_fu_803_p4 = {{kh_mem_V_q0[63:48]}};

assign loc_V_fu_769_p1 = kh_mem_V_q0[15:0];

assign n_inputs_list_address0 = tmp_s_reg_1141;

assign n_outputs_list_address0 = tmp_s_fu_539_p1;

assign nc_V_fu_865_p3 = ((or_cond_fu_851_p2[0:0] === 1'b1) ? newSel_fu_843_p3 : newSel1_fu_857_p3);

assign newSel1_fu_857_p3 = ((tmp_3_i_fu_764_p2[0:0] === 1'b1) ? loc_V_fu_769_p1 : loc_V_3_fu_803_p4);

assign newSel3_fu_1086_p3 = ((sel_tmp4_mid2_reg_1355[0:0] === 1'b1) ? dmem_V_1_1_q0 : dmem_V_1_0_q0);

assign newSel4_fu_1093_p3 = ((sel_tmp3_mid2_fu_1080_p3[0:0] === 1'b1) ? dmem_V_0_1_q0 : dmem_V_0_0_q0);

assign newSel_fu_843_p3 = ((sel_tmp7_fu_837_p2[0:0] === 1'b1) ? loc_V_2_fu_793_p4 : loc_V_1_fu_778_p4);

assign norm_mode_list_address0 = tmp_s_reg_1141;

assign not_exitcond_flatten_2_fu_964_p2 = (exitcond_flatten2_fu_918_p2 ^ 1'd1);

assign not_exitcond_flatten_fu_615_p2 = (exitcond_flatten_fu_583_p2 ^ 1'd1);

assign o_index_V_1_fu_874_p2 = (10'd1 + t_V_1_reg_430);

assign o_index_V_cast_fu_545_p1 = o_index_list_q0;

assign o_index_list_address0 = tmp_s_fu_539_p1;

assign off_V_fu_749_p1 = t_V_reg_440[1:0];

assign or_cond_fu_851_p2 = (sel_tmp7_fu_837_p2 | sel_tmp2_fu_819_p2);

assign p_s_fu_1120_p3 = ((tmp_12_fu_1114_p2[0:0] === 1'b1) ? 32'd0 : tmp_11_fu_1109_p2);

assign r_V_fu_734_p4 = {{t_V_reg_440[7:2]}};

assign sel_tmp1_fu_813_p2 = (tmp_3_i_fu_764_p2 ^ 1'd1);

assign sel_tmp2_fu_819_p2 = (tmp_4_i_fu_773_p2 & sel_tmp1_fu_813_p2);

assign sel_tmp3_fu_894_p2 = (tmp_1044_fu_890_p1 & sel_tmp_fu_884_p2);

assign sel_tmp3_mid1_fu_1020_p2 = (tmp_1046_fu_1016_p1 & sel_tmp_mid2_fu_956_p3);

assign sel_tmp3_mid2_fu_1080_p3 = ((tmp_15_mid_reg_1340[0:0] === 1'b1) ? sel_tmp3_mid1_reg_1350 : sel_tmp3_mid_fu_1076_p2);

assign sel_tmp3_mid_fu_1076_p2 = (sel_tmp3_reg_1316 & not_exitcond_flatten_2_reg_1335);

assign sel_tmp4_fu_900_p2 = (tmp_1044_fu_890_p1 & tmp_1043_fu_880_p1);

assign sel_tmp4_mid1_fu_1026_p2 = (tmp_1046_fu_1016_p1 & dmem_i5_t_mid2_fu_942_p3);

assign sel_tmp4_mid2_fu_1032_p3 = ((tmp_15_mid_fu_982_p2[0:0] === 1'b1) ? sel_tmp4_mid1_fu_1026_p2 : sel_tmp4_mid_fu_970_p2);

assign sel_tmp4_mid_fu_970_p2 = (sel_tmp4_fu_900_p2 & not_exitcond_flatten_2_fu_964_p2);

assign sel_tmp6_demorgan_fu_825_p2 = (tmp_4_i_fu_773_p2 | tmp_3_i_fu_764_p2);

assign sel_tmp6_fu_831_p2 = (sel_tmp6_demorgan_fu_825_p2 ^ 1'd1);

assign sel_tmp7_fu_837_p2 = (tmp_5_i_fu_788_p2 & sel_tmp6_fu_831_p2);

assign sel_tmp_fu_884_p2 = (tmp_1043_fu_880_p1 ^ 1'd1);

assign sel_tmp_mid1_fu_950_p2 = (tmp_1045_fu_938_p1 ^ 1'd1);

assign sel_tmp_mid2_fu_956_p3 = ((exitcond_flatten2_fu_918_p2[0:0] === 1'b1) ? sel_tmp_mid1_fu_950_p2 : sel_tmp_fu_884_p2);

assign this_assign_1_fu_753_p2 = ((t_V_reg_440 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_1036_fu_611_p1 = dmem_i_t_mid2_v_fu_603_p3[0:0];

assign tmp_1037_fu_621_p1 = dmem_j_reg_408[0:0];

assign tmp_1038_fu_663_p1 = dmem_j_1_fu_643_p2[0:0];

assign tmp_1039_fu_711_p1 = o_index_V_reg_1160[7:0];

assign tmp_1040_fu_719_p1 = t_V_1_reg_430[7:0];

assign tmp_1043_fu_880_p1 = dmem_i5_reg_462[0:0];

assign tmp_1044_fu_890_p1 = dmem_j6_reg_484[0:0];

assign tmp_1045_fu_938_p1 = dmem_i_1_fu_932_p2[0:0];

assign tmp_1046_fu_1016_p1 = dmem_j_2_fu_996_p2[0:0];

assign tmp_10_fu_1048_p1 = dmem_k7_mid2_fu_1008_p3;

assign tmp_11_fu_1109_p2 = (bin_conv_cnt_load_reg_1134 + 32'd1);

assign tmp_12_fu_1114_p2 = ((tmp_11_fu_1109_p2 == 32'd7) ? 1'b1 : 1'b0);

assign tmp_13_fu_714_p2 = (tmp_1039_fu_711_p1 + n_outputs_V_reg_1170);

assign tmp_14_fu_976_p2 = ((dmem_k7_reg_495 == 11'd1024) ? 1'b1 : 1'b0);

assign tmp_15_fu_1002_p2 = (tmp_15_mid_fu_982_p2 | exitcond_flatten2_fu_918_p2);

assign tmp_15_mid_fu_982_p2 = (tmp_14_fu_976_p2 & not_exitcond_flatten_2_fu_964_p2);

assign tmp_1_fu_549_p2 = ((kh_i_reg_364 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_2_fu_566_p2 = ((bin_conv_cnt_load_reg_1134 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_561_p1 = kh_i_reg_364;

assign tmp_3_i_fu_764_p2 = ((off_V_reg_1290 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_683_p1 = dmem_k_mid2_fu_655_p3;

assign tmp_4_i_fu_773_p2 = ((off_V_reg_1290 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_5_fu_759_p2 = ((bin_conv_cnt_load_reg_1134 == 32'd6) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_788_p2 = ((off_V_reg_1290 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_6_fu_631_p2 = ((dmem_k_reg_419 == 11'd1024) ? 1'b1 : 1'b0);

assign tmp_9_fu_649_p2 = (tmp_9_mid_fu_637_p2 | exitcond_flatten_fu_583_p2);

assign tmp_9_mid_fu_637_p2 = (tmp_6_fu_631_p2 & not_exitcond_flatten_fu_615_p2);

assign tmp_i_fu_744_p1 = r_V_fu_734_p4;

assign tmp_s_fu_539_p1 = bin_conv_cnt;

assign width_mode_list_address0 = tmp_s_reg_1141;

always @ (posedge ap_clk) begin
    tmp_s_reg_1141[63:32] <= 32'b00000000000000000000000000000000;
    o_index_V_cast_reg_1165[9] <= 1'b0;
end

endmodule //bin_conv_1
