// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bin_conv_wrapper,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.749500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=40,HLS_SYN_DSP=1,HLS_SYN_FF=6382,HLS_SYN_LUT=36371,HLS_VERSION=2018_2}" *)

module bin_conv_wrapper (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_V_V,
        Input_1_V_V_ap_vld,
        Input_1_V_V_ap_ack,
        Input_2_V_V,
        Input_2_V_V_ap_vld,
        Input_2_V_V_ap_ack,
        Output_1_V_V,
        Output_1_V_V_ap_vld,
        Output_1_V_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_pp2_stage0 = 13'd2048;
parameter    ap_ST_fsm_state14 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] Input_1_V_V;
input   Input_1_V_V_ap_vld;
output   Input_1_V_V_ap_ack;
input  [63:0] Input_2_V_V;
input   Input_2_V_V_ap_vld;
output   Input_2_V_V_ap_ack;
output  [63:0] Output_1_V_V;
output   Output_1_V_V_ap_vld;
input   Output_1_V_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Input_1_V_V_ap_ack;
reg Input_2_V_V_ap_ack;
reg Output_1_V_V_ap_vld;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] bin_conv_cnt;
wire   [3:0] o_index_list_address0;
reg    o_index_list_ce0;
wire   [8:0] o_index_list_q0;
wire   [3:0] n_outputs_list_address0;
reg    n_outputs_list_ce0;
wire   [8:0] n_outputs_list_q0;
wire   [3:0] d_i_idx_list_V_address0;
reg    d_i_idx_list_V_ce0;
wire   [0:0] d_i_idx_list_V_q0;
wire   [3:0] d_o_idx_list_V_address0;
reg    d_o_idx_list_V_ce0;
wire   [0:0] d_o_idx_list_V_q0;
wire   [3:0] n_inputs_list_address0;
reg    n_inputs_list_ce0;
wire   [9:0] n_inputs_list_q0;
wire   [3:0] width_mode_list_address0;
reg    width_mode_list_ce0;
wire   [1:0] width_mode_list_q0;
wire   [3:0] norm_mode_list_address0;
reg    norm_mode_list_ce0;
wire   [1:0] norm_mode_list_q0;
reg   [9:0] dmem_V_0_0_address0;
reg    dmem_V_0_0_ce0;
reg    dmem_V_0_0_we0;
reg   [63:0] dmem_V_0_0_d0;
wire   [63:0] dmem_V_0_0_q0;
reg   [9:0] dmem_V_0_1_address0;
reg    dmem_V_0_1_ce0;
reg    dmem_V_0_1_we0;
reg   [63:0] dmem_V_0_1_d0;
wire   [63:0] dmem_V_0_1_q0;
reg   [9:0] dmem_V_1_0_address0;
reg    dmem_V_1_0_ce0;
reg    dmem_V_1_0_we0;
wire   [63:0] dmem_V_1_0_q0;
reg   [9:0] dmem_V_1_1_address0;
reg    dmem_V_1_1_ce0;
reg    dmem_V_1_1_we0;
wire   [63:0] dmem_V_1_1_q0;
reg    Input_1_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_1_fu_511_p2;
reg    Input_2_V_V_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_flatten_fu_533_p2;
reg    Output_1_V_V_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] exitcond_flatten1_reg_1181;
reg   [8:0] indvar_flatten1_reg_413;
reg   [1:0] dmem_i_reg_424;
reg   [8:0] indvar_flatten6_reg_435;
reg   [1:0] dmem_j5_reg_446;
reg   [6:0] dmem_k6_reg_457;
reg   [31:0] bin_conv_cnt_load_reg_1007;
wire   [63:0] tmp_s_fu_501_p1;
reg   [63:0] tmp_s_reg_1014;
reg   [8:0] o_index_V_reg_1033;
wire    ap_CS_fsm_state2;
wire   [9:0] o_index_V_cast_fu_507_p1;
reg   [9:0] o_index_V_cast_reg_1038;
reg   [8:0] n_outputs_V_reg_1043;
wire   [6:0] kh_i_1_fu_517_p2;
reg    ap_block_state3;
wire   [0:0] tmp_2_fu_528_p2;
wire    ap_CS_fsm_state4;
wire   [11:0] indvar_flatten_next_fu_539_p2;
reg    ap_block_state5;
wire   [1:0] dmem_j_t_mid2_v_fu_565_p3;
wire   [10:0] dmem_k_1_fu_583_p2;
wire    ap_CS_fsm_state6;
wire   [8:0] tmp_6_fu_589_p2;
reg   [8:0] tmp_6_reg_1106;
reg   [0:0] d_i_idx_list_V_load_reg_1111;
wire    ap_CS_fsm_state7;
reg   [0:0] d_o_idx_list_V_load_reg_1116;
reg   [9:0] n_inputs_list_load_reg_1121;
reg   [1:0] width_mode_list_load_reg_1126;
reg   [1:0] norm_mode_list_load_reg_1131;
wire   [0:0] exitcond_fu_597_p2;
wire    ap_CS_fsm_state8;
wire   [8:0] kh_index_V_fu_602_p2;
reg   [8:0] kh_index_V_reg_1140;
wire   [1:0] off_V_fu_623_p1;
reg   [1:0] off_V_reg_1150;
wire   [0:0] this_assign_1_fu_627_p2;
reg   [0:0] this_assign_1_reg_1157;
wire   [0:0] tmp_7_fu_633_p2;
wire   [15:0] nc_V_fu_739_p3;
reg   [15:0] nc_V_reg_1166;
wire    ap_CS_fsm_state9;
wire   [9:0] o_index_V_1_fu_747_p2;
reg   [9:0] o_index_V_1_reg_1171;
wire    ap_CS_fsm_state10;
wire   [0:0] sel_tmp3_fu_767_p2;
reg   [0:0] sel_tmp3_reg_1176;
wire    ap_block_state12_pp2_stage0_iter0;
wire    ap_block_state13_pp2_stage0_iter1;
reg    ap_sig_ioackin_Output_1_V_V_ap_ack;
reg    ap_block_state13_io;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] exitcond_flatten1_fu_779_p2;
wire   [8:0] indvar_flatten_next1_fu_785_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] dmem_i_t_mid2_fu_815_p3;
reg   [0:0] dmem_i_t_mid2_reg_1190;
wire   [0:0] not_exitcond_flatten_fu_837_p2;
reg   [0:0] not_exitcond_flatten_reg_1195;
wire   [0:0] tmp_14_mid_fu_855_p2;
reg   [0:0] tmp_14_mid_reg_1200;
wire   [1:0] dmem_i_mid2_fu_861_p3;
wire   [0:0] sel_tmp3_mid1_fu_893_p2;
reg   [0:0] sel_tmp3_mid1_reg_1210;
wire   [0:0] sel_tmp4_mid2_fu_905_p3;
reg   [0:0] sel_tmp4_mid2_reg_1215;
wire   [1:0] dmem_j5_mid2_fu_913_p3;
wire   [6:0] dmem_k_2_fu_929_p2;
wire   [8:0] indvar_flatten_next7_fu_941_p3;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state12;
reg   [5:0] kh_mem_V_address0;
reg    kh_mem_V_ce0;
reg    kh_mem_V_we0;
wire   [63:0] kh_mem_V_q0;
wire    grp_bin_conv_fu_468_ap_start;
wire    grp_bin_conv_fu_468_ap_done;
wire    grp_bin_conv_fu_468_ap_idle;
wire    grp_bin_conv_fu_468_ap_ready;
wire    grp_bin_conv_fu_468_Input_1_V_V_ap_ack;
wire   [9:0] grp_bin_conv_fu_468_dmem_0_0_V_address0;
wire    grp_bin_conv_fu_468_dmem_0_0_V_ce0;
wire    grp_bin_conv_fu_468_dmem_0_0_V_we0;
wire   [63:0] grp_bin_conv_fu_468_dmem_0_0_V_d0;
wire   [9:0] grp_bin_conv_fu_468_dmem_0_1_V_address0;
wire    grp_bin_conv_fu_468_dmem_0_1_V_ce0;
wire    grp_bin_conv_fu_468_dmem_0_1_V_we0;
wire   [63:0] grp_bin_conv_fu_468_dmem_0_1_V_d0;
wire   [9:0] grp_bin_conv_fu_468_dmem_1_0_V_address0;
wire    grp_bin_conv_fu_468_dmem_1_0_V_ce0;
wire    grp_bin_conv_fu_468_dmem_1_0_V_we0;
wire   [63:0] grp_bin_conv_fu_468_dmem_1_0_V_d0;
wire   [9:0] grp_bin_conv_fu_468_dmem_1_1_V_address0;
wire    grp_bin_conv_fu_468_dmem_1_1_V_ce0;
wire    grp_bin_conv_fu_468_dmem_1_1_V_we0;
wire   [63:0] grp_bin_conv_fu_468_dmem_1_1_V_d0;
reg   [6:0] kh_i_reg_348;
reg   [11:0] indvar_flatten_reg_359;
reg   [1:0] dmem_j_reg_370;
reg   [10:0] dmem_k_reg_381;
reg   [9:0] t_V_1_reg_392;
wire    ap_CS_fsm_state11;
reg   [8:0] t_V_reg_402;
reg    grp_bin_conv_fu_468_ap_start_reg;
wire   [63:0] tmp_3_fu_523_p1;
wire   [63:0] tmp_9_fu_577_p1;
wire   [63:0] tmp_i_fu_618_p1;
wire   [63:0] tmp_10_fu_921_p1;
wire   [31:0] p_s_fu_993_p3;
wire    ap_CS_fsm_state14;
wire    ap_block_pp2_stage0_01001;
reg    ap_reg_ioackin_Output_1_V_V_ap_ack;
wire   [0:0] tmp_1045_fu_573_p1;
wire   [0:0] tmp_4_fu_545_p2;
wire   [1:0] dmem_j_s_fu_559_p2;
wire   [10:0] dmem_k_mid2_fu_551_p3;
wire   [8:0] tmp_1046_fu_593_p1;
wire   [6:0] r_V_fu_608_p4;
wire   [0:0] tmp_3_i_fu_638_p2;
wire   [0:0] tmp_4_i_fu_647_p2;
wire   [0:0] sel_tmp1_fu_687_p2;
wire   [0:0] sel_tmp6_demorgan_fu_699_p2;
wire   [0:0] tmp_5_i_fu_662_p2;
wire   [0:0] sel_tmp6_fu_705_p2;
wire   [0:0] sel_tmp7_fu_711_p2;
wire   [15:0] loc_V_2_fu_667_p4;
wire   [15:0] loc_V_1_fu_652_p4;
wire   [0:0] sel_tmp2_fu_693_p2;
wire   [15:0] loc_V_fu_643_p1;
wire   [15:0] loc_V_3_fu_677_p4;
wire   [0:0] or_cond_fu_725_p2;
wire   [15:0] newSel_fu_717_p3;
wire   [15:0] newSel1_fu_731_p3;
wire   [0:0] tmp_1049_fu_753_p1;
wire   [0:0] tmp_1050_fu_763_p1;
wire   [0:0] sel_tmp_fu_757_p2;
wire   [0:0] exitcond_flatten2_fu_791_p2;
wire   [1:0] dmem_i_s_fu_805_p2;
wire   [0:0] tmp_1051_fu_811_p1;
wire   [0:0] sel_tmp_mid1_fu_823_p2;
wire   [0:0] sel_tmp4_fu_773_p2;
wire   [0:0] tmp_13_fu_849_p2;
wire   [1:0] dmem_j5_mid_fu_797_p3;
wire   [0:0] tmp_14_fu_875_p2;
wire   [1:0] dmem_j_1_fu_869_p2;
wire   [0:0] tmp_1052_fu_889_p1;
wire   [0:0] sel_tmp_mid2_fu_829_p3;
wire   [0:0] sel_tmp4_mid1_fu_899_p2;
wire   [0:0] sel_tmp4_mid_fu_843_p2;
wire   [6:0] dmem_k6_mid2_fu_881_p3;
wire   [8:0] indvar_flatten6_op_fu_935_p2;
wire   [0:0] sel_tmp3_mid_fu_949_p2;
wire   [0:0] sel_tmp3_mid2_fu_953_p3;
wire   [63:0] newSel3_fu_959_p3;
wire   [63:0] newSel4_fu_966_p3;
wire   [31:0] tmp_11_fu_982_p2;
wire   [0:0] tmp_12_fu_987_p2;
reg   [12:0] ap_NS_fsm;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_condition_837;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 bin_conv_cnt = 32'd0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 grp_bin_conv_fu_468_ap_start_reg = 1'b0;
#0 ap_reg_ioackin_Output_1_V_V_ap_ack = 1'b0;
end

bin_conv_wrapper_fYi #(
    .DataWidth( 9 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
o_index_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(o_index_list_address0),
    .ce0(o_index_list_ce0),
    .q0(o_index_list_q0)
);

bin_conv_wrapper_g8j #(
    .DataWidth( 9 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
n_outputs_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(n_outputs_list_address0),
    .ce0(n_outputs_list_ce0),
    .q0(n_outputs_list_q0)
);

bin_conv_wrapper_hbi #(
    .DataWidth( 1 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
d_i_idx_list_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(d_i_idx_list_V_address0),
    .ce0(d_i_idx_list_V_ce0),
    .q0(d_i_idx_list_V_q0)
);

bin_conv_wrapper_ibs #(
    .DataWidth( 1 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
d_o_idx_list_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(d_o_idx_list_V_address0),
    .ce0(d_o_idx_list_V_ce0),
    .q0(d_o_idx_list_V_q0)
);

bin_conv_wrapper_jbC #(
    .DataWidth( 10 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
n_inputs_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(n_inputs_list_address0),
    .ce0(n_inputs_list_ce0),
    .q0(n_inputs_list_q0)
);

bin_conv_wrapper_kbM #(
    .DataWidth( 2 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
width_mode_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(width_mode_list_address0),
    .ce0(width_mode_list_ce0),
    .q0(width_mode_list_q0)
);

bin_conv_wrapper_lbW #(
    .DataWidth( 2 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
norm_mode_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(norm_mode_list_address0),
    .ce0(norm_mode_list_ce0),
    .q0(norm_mode_list_q0)
);

bin_conv_wrapper_mb6 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_0_address0),
    .ce0(dmem_V_0_0_ce0),
    .we0(dmem_V_0_0_we0),
    .d0(dmem_V_0_0_d0),
    .q0(dmem_V_0_0_q0)
);

bin_conv_wrapper_mb6 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_1_address0),
    .ce0(dmem_V_0_1_ce0),
    .we0(dmem_V_0_1_we0),
    .d0(dmem_V_0_1_d0),
    .q0(dmem_V_0_1_q0)
);

bin_conv_wrapper_mb6 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_0_address0),
    .ce0(dmem_V_1_0_ce0),
    .we0(dmem_V_1_0_we0),
    .d0(grp_bin_conv_fu_468_dmem_1_0_V_d0),
    .q0(dmem_V_1_0_q0)
);

bin_conv_wrapper_mb6 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_1_address0),
    .ce0(dmem_V_1_1_ce0),
    .we0(dmem_V_1_1_we0),
    .d0(grp_bin_conv_fu_468_dmem_1_1_V_d0),
    .q0(dmem_V_1_1_q0)
);

bin_conv_wrapper_qcK #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kh_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kh_mem_V_address0),
    .ce0(kh_mem_V_ce0),
    .we0(kh_mem_V_we0),
    .d0(Input_1_V_V),
    .q0(kh_mem_V_q0)
);

bin_conv grp_bin_conv_fu_468(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_conv_fu_468_ap_start),
    .ap_done(grp_bin_conv_fu_468_ap_done),
    .ap_idle(grp_bin_conv_fu_468_ap_idle),
    .ap_ready(grp_bin_conv_fu_468_ap_ready),
    .Input_1_V_V(Input_1_V_V),
    .Input_1_V_V_ap_vld(Input_1_V_V_ap_vld),
    .Input_1_V_V_ap_ack(grp_bin_conv_fu_468_Input_1_V_V_ap_ack),
    .nc_V(nc_V_reg_1166),
    .dmem_0_0_V_address0(grp_bin_conv_fu_468_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_bin_conv_fu_468_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_bin_conv_fu_468_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_bin_conv_fu_468_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_bin_conv_fu_468_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_bin_conv_fu_468_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_bin_conv_fu_468_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_bin_conv_fu_468_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_bin_conv_fu_468_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_bin_conv_fu_468_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_bin_conv_fu_468_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_bin_conv_fu_468_dmem_1_0_V_d0),
    .dmem_1_0_V_q0(dmem_V_1_0_q0),
    .dmem_1_1_V_address0(grp_bin_conv_fu_468_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_bin_conv_fu_468_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_bin_conv_fu_468_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_bin_conv_fu_468_dmem_1_1_V_d0),
    .dmem_1_1_V_q0(dmem_V_1_1_q0),
    .d_i_idx_V(d_i_idx_list_V_load_reg_1111),
    .d_o_idx_V(d_o_idx_list_V_load_reg_1116),
    .n_inputs(n_inputs_list_load_reg_1121),
    .o_index_V(t_V_1_reg_392),
    .new_batch_V(this_assign_1_reg_1157),
    .width_mode_V(width_mode_list_load_reg_1126),
    .norm_mode_V(norm_mode_list_load_reg_1131)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state12) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state12))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state12);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_837)) begin
            if ((1'b0 == ap_block_pp2_stage0_11001)) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
            end else if (((1'b0 == ap_block_pp2_stage0_01001) & (1'b1 == Output_1_V_V_ap_ack))) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bin_conv_fu_468_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_bin_conv_fu_468_ap_start_reg <= 1'b1;
        end else if ((grp_bin_conv_fu_468_ap_ready == 1'b1)) begin
            grp_bin_conv_fu_468_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_i_reg_424 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_fu_779_p2 == 1'd0))) begin
        dmem_i_reg_424 <= dmem_i_mid2_fu_861_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_j5_reg_446 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_fu_779_p2 == 1'd0))) begin
        dmem_j5_reg_446 <= dmem_j5_mid2_fu_913_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_528_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_j_reg_370 <= 2'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        dmem_j_reg_370 <= dmem_j_t_mid2_v_fu_565_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_k6_reg_457 <= 7'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_fu_779_p2 == 1'd0))) begin
        dmem_k6_reg_457 <= dmem_k_2_fu_929_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_528_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_k_reg_381 <= 11'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        dmem_k_reg_381 <= dmem_k_1_fu_583_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten1_reg_413 <= 9'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_fu_779_p2 == 1'd0))) begin
        indvar_flatten1_reg_413 <= indvar_flatten_next1_fu_785_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten6_reg_435 <= 9'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_fu_779_p2 == 1'd0))) begin
        indvar_flatten6_reg_435 <= indvar_flatten_next7_fu_941_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_528_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten_reg_359 <= 12'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        indvar_flatten_reg_359 <= indvar_flatten_next_fu_539_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_511_p2 == 1'd0))) begin
        kh_i_reg_348 <= kh_i_1_fu_517_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        kh_i_reg_348 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_468_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        t_V_1_reg_392 <= o_index_V_1_reg_1171;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_1_reg_392 <= o_index_V_cast_reg_1038;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_468_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        t_V_reg_402 <= kh_index_V_reg_1140;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_402 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        bin_conv_cnt <= p_s_fu_993_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bin_conv_cnt_load_reg_1007 <= bin_conv_cnt;
        tmp_s_reg_1014[31 : 0] <= tmp_s_fu_501_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_idx_list_V_load_reg_1111 <= d_i_idx_list_V_q0;
        d_o_idx_list_V_load_reg_1116 <= d_o_idx_list_V_q0;
        n_inputs_list_load_reg_1121 <= n_inputs_list_q0;
        norm_mode_list_load_reg_1131 <= norm_mode_list_q0;
        width_mode_list_load_reg_1126 <= width_mode_list_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_fu_779_p2 == 1'd0))) begin
        dmem_i_t_mid2_reg_1190 <= dmem_i_t_mid2_fu_815_p3;
        not_exitcond_flatten_reg_1195 <= not_exitcond_flatten_fu_837_p2;
        sel_tmp3_mid1_reg_1210 <= sel_tmp3_mid1_fu_893_p2;
        sel_tmp4_mid2_reg_1215 <= sel_tmp4_mid2_fu_905_p3;
        tmp_14_mid_reg_1200 <= tmp_14_mid_fu_855_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        exitcond_flatten1_reg_1181 <= exitcond_flatten1_fu_779_p2;
        sel_tmp3_reg_1176 <= sel_tmp3_fu_767_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kh_index_V_reg_1140 <= kh_index_V_fu_602_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        n_outputs_V_reg_1043 <= n_outputs_list_q0;
        o_index_V_cast_reg_1038[8 : 0] <= o_index_V_cast_fu_507_p1[8 : 0];
        o_index_V_reg_1033 <= o_index_list_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        nc_V_reg_1166 <= nc_V_fu_739_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        o_index_V_1_reg_1171 <= o_index_V_1_fu_747_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond_fu_597_p2 == 1'd0))) begin
        off_V_reg_1150 <= off_V_fu_623_p1;
        this_assign_1_reg_1157 <= this_assign_1_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_6_reg_1106 <= tmp_6_fu_589_p2;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_511_p2 == 1'd0))) begin
        Input_1_V_V_ap_ack = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        Input_1_V_V_ap_ack = grp_bin_conv_fu_468_Input_1_V_V_ap_ack;
    end else begin
        Input_1_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_511_p2 == 1'd0))) begin
        Input_1_V_V_blk_n = Input_1_V_V_ap_vld;
    end else begin
        Input_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        Input_2_V_V_ap_ack = 1'b1;
    end else begin
        Input_2_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        Input_2_V_V_blk_n = Input_2_V_V_ap_vld;
    end else begin
        Input_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_01001) & (ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_reg_1181 == 1'd0))) begin
        Output_1_V_V_ap_vld = 1'b1;
    end else begin
        Output_1_V_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0) & (exitcond_flatten1_reg_1181 == 1'd0))) begin
        Output_1_V_V_blk_n = Output_1_V_V_ap_ack;
    end else begin
        Output_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond_flatten1_fu_779_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state12 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0)) begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = Output_1_V_V_ap_ack;
    end else begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_idx_list_V_ce0 = 1'b1;
    end else begin
        d_i_idx_list_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_idx_list_V_ce0 = 1'b1;
    end else begin
        d_o_idx_list_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_0_address0 = tmp_10_fu_921_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_0_address0 = tmp_9_fu_577_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_0_address0 = grp_bin_conv_fu_468_dmem_0_0_V_address0;
    end else begin
        dmem_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_0_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_0_ce0 = grp_bin_conv_fu_468_dmem_0_0_V_ce0;
    end else begin
        dmem_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_0_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_0_d0 = grp_bin_conv_fu_468_dmem_0_0_V_d0;
    end else begin
        dmem_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (tmp_1045_fu_573_p1 == 1'd0) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        dmem_V_0_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_0_we0 = grp_bin_conv_fu_468_dmem_0_0_V_we0;
    end else begin
        dmem_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_1_address0 = tmp_10_fu_921_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_1_address0 = tmp_9_fu_577_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_1_address0 = grp_bin_conv_fu_468_dmem_0_1_V_address0;
    end else begin
        dmem_V_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_0_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_1_ce0 = grp_bin_conv_fu_468_dmem_0_1_V_ce0;
    end else begin
        dmem_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_1_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_1_d0 = grp_bin_conv_fu_468_dmem_0_1_V_d0;
    end else begin
        dmem_V_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (tmp_1045_fu_573_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
        dmem_V_0_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_0_1_we0 = grp_bin_conv_fu_468_dmem_0_1_V_we0;
    end else begin
        dmem_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_0_address0 = tmp_10_fu_921_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_1_0_address0 = grp_bin_conv_fu_468_dmem_1_0_V_address0;
    end else begin
        dmem_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_V_1_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_1_0_ce0 = grp_bin_conv_fu_468_dmem_1_0_V_ce0;
    end else begin
        dmem_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_1_0_we0 = grp_bin_conv_fu_468_dmem_1_0_V_we0;
    end else begin
        dmem_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_1_address0 = tmp_10_fu_921_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_1_1_address0 = grp_bin_conv_fu_468_dmem_1_1_V_address0;
    end else begin
        dmem_V_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_V_1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_1_1_ce0 = grp_bin_conv_fu_468_dmem_1_1_V_ce0;
    end else begin
        dmem_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        dmem_V_1_1_we0 = grp_bin_conv_fu_468_dmem_1_1_V_we0;
    end else begin
        dmem_V_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kh_mem_V_address0 = tmp_i_fu_618_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kh_mem_V_address0 = tmp_3_fu_523_p1;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3)))) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_511_p2 == 1'd0))) begin
        kh_mem_V_we0 = 1'b1;
    end else begin
        kh_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        n_inputs_list_ce0 = 1'b1;
    end else begin
        n_inputs_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        n_outputs_list_ce0 = 1'b1;
    end else begin
        n_outputs_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        norm_mode_list_ce0 = 1'b1;
    end else begin
        norm_mode_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_index_list_ce0 = 1'b1;
    end else begin
        o_index_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        width_mode_list_ce0 = 1'b1;
    end else begin
        width_mode_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_511_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_511_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((tmp_2_fu_528_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten_fu_533_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((tmp_7_fu_633_p2 == 1'd1) & (exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((exitcond_fu_597_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8) & (tmp_7_fu_633_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_bin_conv_fu_468_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond_flatten1_fu_779_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond_flatten1_fu_779_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_1_V_V = ((dmem_i_t_mid2_reg_1190[0:0] === 1'b1) ? newSel3_fu_959_p3 : newSel4_fu_966_p3);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((1'b1 == ap_block_state13_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((1'b1 == ap_block_state13_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_state12_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_io = ((ap_sig_ioackin_Output_1_V_V_ap_ack == 1'b0) & (exitcond_flatten1_reg_1181 == 1'd0));
end

assign ap_block_state13_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3 = ((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_511_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state5 = ((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten_fu_533_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_837 = ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten1_reg_1181 == 1'd0));
end

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign d_i_idx_list_V_address0 = tmp_s_reg_1014;

assign d_o_idx_list_V_address0 = tmp_s_reg_1014;

assign dmem_i_mid2_fu_861_p3 = ((exitcond_flatten2_fu_791_p2[0:0] === 1'b1) ? dmem_i_s_fu_805_p2 : dmem_i_reg_424);

assign dmem_i_s_fu_805_p2 = (2'd1 + dmem_i_reg_424);

assign dmem_i_t_mid2_fu_815_p3 = ((exitcond_flatten2_fu_791_p2[0:0] === 1'b1) ? tmp_1051_fu_811_p1 : tmp_1049_fu_753_p1);

assign dmem_j5_mid2_fu_913_p3 = ((tmp_14_mid_fu_855_p2[0:0] === 1'b1) ? dmem_j_1_fu_869_p2 : dmem_j5_mid_fu_797_p3);

assign dmem_j5_mid_fu_797_p3 = ((exitcond_flatten2_fu_791_p2[0:0] === 1'b1) ? 2'd0 : dmem_j5_reg_446);

assign dmem_j_1_fu_869_p2 = (2'd1 + dmem_j5_mid_fu_797_p3);

assign dmem_j_s_fu_559_p2 = (2'd1 + dmem_j_reg_370);

assign dmem_j_t_mid2_v_fu_565_p3 = ((tmp_4_fu_545_p2[0:0] === 1'b1) ? dmem_j_s_fu_559_p2 : dmem_j_reg_370);

assign dmem_k6_mid2_fu_881_p3 = ((tmp_14_fu_875_p2[0:0] === 1'b1) ? 7'd0 : dmem_k6_reg_457);

assign dmem_k_1_fu_583_p2 = (dmem_k_mid2_fu_551_p3 + 11'd1);

assign dmem_k_2_fu_929_p2 = (7'd1 + dmem_k6_mid2_fu_881_p3);

assign dmem_k_mid2_fu_551_p3 = ((tmp_4_fu_545_p2[0:0] === 1'b1) ? 11'd0 : dmem_k_reg_381);

assign exitcond_flatten1_fu_779_p2 = ((indvar_flatten1_reg_413 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_791_p2 = ((indvar_flatten6_reg_435 == 9'd128) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_533_p2 = ((indvar_flatten_reg_359 == 12'd2048) ? 1'b1 : 1'b0);

assign exitcond_fu_597_p2 = ((tmp_1046_fu_593_p1 == tmp_6_reg_1106) ? 1'b1 : 1'b0);

assign grp_bin_conv_fu_468_ap_start = grp_bin_conv_fu_468_ap_start_reg;

assign indvar_flatten6_op_fu_935_p2 = (9'd1 + indvar_flatten6_reg_435);

assign indvar_flatten_next1_fu_785_p2 = (9'd1 + indvar_flatten1_reg_413);

assign indvar_flatten_next7_fu_941_p3 = ((exitcond_flatten2_fu_791_p2[0:0] === 1'b1) ? 9'd1 : indvar_flatten6_op_fu_935_p2);

assign indvar_flatten_next_fu_539_p2 = (indvar_flatten_reg_359 + 12'd1);

assign kh_i_1_fu_517_p2 = (kh_i_reg_348 + 7'd1);

assign kh_index_V_fu_602_p2 = (9'd1 + t_V_reg_402);

assign loc_V_1_fu_652_p4 = {{kh_mem_V_q0[31:16]}};

assign loc_V_2_fu_667_p4 = {{kh_mem_V_q0[47:32]}};

assign loc_V_3_fu_677_p4 = {{kh_mem_V_q0[63:48]}};

assign loc_V_fu_643_p1 = kh_mem_V_q0[15:0];

assign n_inputs_list_address0 = tmp_s_reg_1014;

assign n_outputs_list_address0 = tmp_s_fu_501_p1;

assign nc_V_fu_739_p3 = ((or_cond_fu_725_p2[0:0] === 1'b1) ? newSel_fu_717_p3 : newSel1_fu_731_p3);

assign newSel1_fu_731_p3 = ((tmp_3_i_fu_638_p2[0:0] === 1'b1) ? loc_V_fu_643_p1 : loc_V_3_fu_677_p4);

assign newSel3_fu_959_p3 = ((sel_tmp4_mid2_reg_1215[0:0] === 1'b1) ? dmem_V_1_1_q0 : dmem_V_1_0_q0);

assign newSel4_fu_966_p3 = ((sel_tmp3_mid2_fu_953_p3[0:0] === 1'b1) ? dmem_V_0_1_q0 : dmem_V_0_0_q0);

assign newSel_fu_717_p3 = ((sel_tmp7_fu_711_p2[0:0] === 1'b1) ? loc_V_2_fu_667_p4 : loc_V_1_fu_652_p4);

assign norm_mode_list_address0 = tmp_s_reg_1014;

assign not_exitcond_flatten_fu_837_p2 = (exitcond_flatten2_fu_791_p2 ^ 1'd1);

assign o_index_V_1_fu_747_p2 = (10'd1 + t_V_1_reg_392);

assign o_index_V_cast_fu_507_p1 = o_index_list_q0;

assign o_index_list_address0 = tmp_s_fu_501_p1;

assign off_V_fu_623_p1 = t_V_reg_402[1:0];

assign or_cond_fu_725_p2 = (sel_tmp7_fu_711_p2 | sel_tmp2_fu_693_p2);

assign p_s_fu_993_p3 = ((tmp_12_fu_987_p2[0:0] === 1'b1) ? 32'd0 : tmp_11_fu_982_p2);

assign r_V_fu_608_p4 = {{t_V_reg_402[8:2]}};

assign sel_tmp1_fu_687_p2 = (tmp_3_i_fu_638_p2 ^ 1'd1);

assign sel_tmp2_fu_693_p2 = (tmp_4_i_fu_647_p2 & sel_tmp1_fu_687_p2);

assign sel_tmp3_fu_767_p2 = (tmp_1050_fu_763_p1 & sel_tmp_fu_757_p2);

assign sel_tmp3_mid1_fu_893_p2 = (tmp_1052_fu_889_p1 & sel_tmp_mid2_fu_829_p3);

assign sel_tmp3_mid2_fu_953_p3 = ((tmp_14_mid_reg_1200[0:0] === 1'b1) ? sel_tmp3_mid1_reg_1210 : sel_tmp3_mid_fu_949_p2);

assign sel_tmp3_mid_fu_949_p2 = (sel_tmp3_reg_1176 & not_exitcond_flatten_reg_1195);

assign sel_tmp4_fu_773_p2 = (tmp_1050_fu_763_p1 & tmp_1049_fu_753_p1);

assign sel_tmp4_mid1_fu_899_p2 = (tmp_1052_fu_889_p1 & dmem_i_t_mid2_fu_815_p3);

assign sel_tmp4_mid2_fu_905_p3 = ((tmp_14_mid_fu_855_p2[0:0] === 1'b1) ? sel_tmp4_mid1_fu_899_p2 : sel_tmp4_mid_fu_843_p2);

assign sel_tmp4_mid_fu_843_p2 = (sel_tmp4_fu_773_p2 & not_exitcond_flatten_fu_837_p2);

assign sel_tmp6_demorgan_fu_699_p2 = (tmp_4_i_fu_647_p2 | tmp_3_i_fu_638_p2);

assign sel_tmp6_fu_705_p2 = (sel_tmp6_demorgan_fu_699_p2 ^ 1'd1);

assign sel_tmp7_fu_711_p2 = (tmp_5_i_fu_662_p2 & sel_tmp6_fu_705_p2);

assign sel_tmp_fu_757_p2 = (tmp_1049_fu_753_p1 ^ 1'd1);

assign sel_tmp_mid1_fu_823_p2 = (tmp_1051_fu_811_p1 ^ 1'd1);

assign sel_tmp_mid2_fu_829_p3 = ((exitcond_flatten2_fu_791_p2[0:0] === 1'b1) ? sel_tmp_mid1_fu_823_p2 : sel_tmp_fu_757_p2);

assign this_assign_1_fu_627_p2 = ((t_V_reg_402 == 9'd0) ? 1'b1 : 1'b0);

assign tmp_1045_fu_573_p1 = dmem_j_t_mid2_v_fu_565_p3[0:0];

assign tmp_1046_fu_593_p1 = t_V_1_reg_392[8:0];

assign tmp_1049_fu_753_p1 = dmem_i_reg_424[0:0];

assign tmp_1050_fu_763_p1 = dmem_j5_reg_446[0:0];

assign tmp_1051_fu_811_p1 = dmem_i_s_fu_805_p2[0:0];

assign tmp_1052_fu_889_p1 = dmem_j_1_fu_869_p2[0:0];

assign tmp_10_fu_921_p1 = dmem_k6_mid2_fu_881_p3;

assign tmp_11_fu_982_p2 = (bin_conv_cnt_load_reg_1007 + 32'd1);

assign tmp_12_fu_987_p2 = ((tmp_11_fu_982_p2 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_13_fu_849_p2 = ((dmem_k6_reg_457 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_14_fu_875_p2 = (tmp_14_mid_fu_855_p2 | exitcond_flatten2_fu_791_p2);

assign tmp_14_mid_fu_855_p2 = (tmp_13_fu_849_p2 & not_exitcond_flatten_fu_837_p2);

assign tmp_1_fu_511_p2 = ((kh_i_reg_348 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_2_fu_528_p2 = ((bin_conv_cnt_load_reg_1007 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_523_p1 = kh_i_reg_348;

assign tmp_3_i_fu_638_p2 = ((off_V_reg_1150 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_545_p2 = ((dmem_k_reg_381 == 11'd1024) ? 1'b1 : 1'b0);

assign tmp_4_i_fu_647_p2 = ((off_V_reg_1150 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_662_p2 = ((off_V_reg_1150 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_6_fu_589_p2 = (o_index_V_reg_1033 + n_outputs_V_reg_1043);

assign tmp_7_fu_633_p2 = ((bin_conv_cnt_load_reg_1007 == 32'd15) ? 1'b1 : 1'b0);

assign tmp_9_fu_577_p1 = dmem_k_mid2_fu_551_p3;

assign tmp_i_fu_618_p1 = r_V_fu_608_p4;

assign tmp_s_fu_501_p1 = bin_conv_cnt;

assign width_mode_list_address0 = tmp_s_reg_1014;

always @ (posedge ap_clk) begin
    tmp_s_reg_1014[63:32] <= 32'b00000000000000000000000000000000;
    o_index_V_cast_reg_1038[9] <= 1'b0;
end

endmodule //bin_conv_wrapper
