// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bin_conv_2,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.451500,HLS_SYN_LAT=5284425,HLS_SYN_TPT=none,HLS_SYN_MEM=40,HLS_SYN_DSP=0,HLS_SYN_FF=3222,HLS_SYN_LUT=22360,HLS_VERSION=2018_2}" *)

module bin_conv_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_V_V,
        Input_1_V_V_ap_vld,
        Input_1_V_V_ap_ack,
        Input_2_V_V,
        Input_2_V_V_ap_vld,
        Input_2_V_V_ap_ack,
        Output_1_V_V,
        Output_1_V_V_ap_vld,
        Output_1_V_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_pp2_stage0 = 12'd1024;
parameter    ap_ST_fsm_state13 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] Input_1_V_V;
input   Input_1_V_V_ap_vld;
output   Input_1_V_V_ap_ack;
input  [63:0] Input_2_V_V;
input   Input_2_V_V_ap_vld;
output   Input_2_V_V_ap_ack;
output  [63:0] Output_1_V_V;
output   Output_1_V_V_ap_vld;
input   Output_1_V_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Input_1_V_V_ap_ack;
reg Input_2_V_V_ap_ack;
reg Output_1_V_V_ap_vld;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] bin_conv_cnt;
wire   [2:0] o_index_list_address0;
reg    o_index_list_ce0;
wire   [8:0] o_index_list_q0;
wire   [2:0] d_o_idx_list_V_address0;
reg    d_o_idx_list_V_ce0;
wire   [0:0] d_o_idx_list_V_q0;
wire   [2:0] n_inputs_list_address0;
reg    n_inputs_list_ce0;
wire   [9:0] n_inputs_list_q0;
reg   [9:0] dmem_V_0_0_address0;
reg    dmem_V_0_0_ce0;
reg    dmem_V_0_0_we0;
reg   [63:0] dmem_V_0_0_d0;
wire   [63:0] dmem_V_0_0_q0;
reg   [9:0] dmem_V_0_1_address0;
reg    dmem_V_0_1_ce0;
reg    dmem_V_0_1_we0;
reg   [63:0] dmem_V_0_1_d0;
wire   [63:0] dmem_V_0_1_q0;
reg   [9:0] dmem_V_1_0_address0;
reg    dmem_V_1_0_ce0;
reg    dmem_V_1_0_we0;
reg   [63:0] dmem_V_1_0_d0;
wire   [63:0] dmem_V_1_0_q0;
reg   [9:0] dmem_V_1_1_address0;
reg    dmem_V_1_1_ce0;
reg    dmem_V_1_1_we0;
reg   [63:0] dmem_V_1_1_d0;
wire   [63:0] dmem_V_1_1_q0;
reg    Input_1_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_1_fu_487_p2;
reg    Input_2_V_V_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_flatten1_fu_509_p2;
reg    Output_1_V_V_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] exitcond_flatten3_reg_1221;
reg   [8:0] indvar_flatten2_reg_393;
reg   [1:0] dmem_i5_reg_404;
reg   [8:0] indvar_flatten3_reg_415;
reg   [1:0] dmem_j6_reg_426;
reg   [6:0] dmem_k7_reg_437;
reg   [31:0] bin_conv_cnt_load_reg_1072;
wire   [63:0] tmp_s_fu_478_p1;
reg   [63:0] tmp_s_reg_1079;
reg   [8:0] o_index_V_reg_1090;
wire    ap_CS_fsm_state2;
wire   [9:0] o_index_V_cast_fu_483_p1;
reg   [9:0] o_index_V_cast_reg_1095;
wire   [6:0] kh_i_1_fu_493_p2;
reg    ap_block_state3;
wire   [0:0] tmp_2_fu_504_p2;
wire    ap_CS_fsm_state4;
wire   [12:0] indvar_flatten_next1_fu_515_p2;
reg    ap_block_state5;
wire   [1:0] dmem_i_t_mid2_v_fu_541_p3;
wire   [1:0] dmem_j_mid2_fu_613_p3;
wire   [10:0] dmem_k_1_fu_629_p2;
wire   [12:0] indvar_flatten_next_fu_641_p3;
wire    ap_CS_fsm_state6;
wire   [6:0] tmp_916_fu_649_p1;
reg   [6:0] tmp_916_reg_1156;
reg   [0:0] d_o_idx_list_V_load_reg_1161;
wire    ap_CS_fsm_state7;
reg   [9:0] n_inputs_list_load_reg_1166;
wire   [6:0] tmp_13_fu_652_p2;
reg   [6:0] tmp_13_reg_1171;
wire   [0:0] exitcond_fu_661_p2;
wire    ap_CS_fsm_state8;
wire   [6:0] kh_index_V_fu_666_p2;
reg   [6:0] kh_index_V_reg_1180;
wire   [1:0] off_V_fu_687_p1;
reg   [1:0] off_V_reg_1190;
wire   [0:0] this_assign_1_fu_691_p2;
reg   [0:0] this_assign_1_reg_1197;
wire   [0:0] tmp_5_fu_697_p2;
wire   [15:0] nc_V_fu_803_p3;
reg   [15:0] nc_V_reg_1206;
wire    ap_CS_fsm_state9;
wire   [9:0] o_index_V_1_fu_812_p2;
reg   [9:0] o_index_V_1_reg_1211;
wire   [0:0] sel_tmp3_fu_832_p2;
reg   [0:0] sel_tmp3_reg_1216;
wire    ap_block_state11_pp2_stage0_iter0;
wire    ap_block_state12_pp2_stage0_iter1;
reg    ap_sig_ioackin_Output_1_V_V_ap_ack;
reg    ap_block_state12_io;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] exitcond_flatten3_fu_844_p2;
wire   [8:0] indvar_flatten_next3_fu_850_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] dmem_i5_t_mid2_fu_880_p3;
reg   [0:0] dmem_i5_t_mid2_reg_1230;
wire   [0:0] not_exitcond_flatten_2_fu_902_p2;
reg   [0:0] not_exitcond_flatten_2_reg_1235;
wire   [0:0] tmp_15_mid_fu_920_p2;
reg   [0:0] tmp_15_mid_reg_1240;
wire   [1:0] dmem_i5_mid2_fu_926_p3;
wire   [0:0] sel_tmp3_mid1_fu_958_p2;
reg   [0:0] sel_tmp3_mid1_reg_1250;
wire   [0:0] sel_tmp4_mid2_fu_970_p3;
reg   [0:0] sel_tmp4_mid2_reg_1255;
wire   [1:0] dmem_j6_mid2_fu_978_p3;
wire   [6:0] dmem_k_2_fu_994_p2;
wire   [8:0] indvar_flatten_next2_fu_1006_p3;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state11;
reg   [5:0] kh_mem_V_address0;
reg    kh_mem_V_ce0;
reg    kh_mem_V_we0;
wire   [63:0] kh_mem_V_q0;
wire    grp_bin_conv_fu_448_ap_start;
wire    grp_bin_conv_fu_448_ap_done;
wire    grp_bin_conv_fu_448_ap_idle;
wire    grp_bin_conv_fu_448_ap_ready;
wire    grp_bin_conv_fu_448_Input_1_V_V_ap_ack;
wire   [9:0] grp_bin_conv_fu_448_dmem_0_0_V_address0;
wire    grp_bin_conv_fu_448_dmem_0_0_V_ce0;
wire    grp_bin_conv_fu_448_dmem_0_0_V_we0;
wire   [63:0] grp_bin_conv_fu_448_dmem_0_0_V_d0;
wire   [9:0] grp_bin_conv_fu_448_dmem_0_1_V_address0;
wire    grp_bin_conv_fu_448_dmem_0_1_V_ce0;
wire    grp_bin_conv_fu_448_dmem_0_1_V_we0;
wire   [63:0] grp_bin_conv_fu_448_dmem_0_1_V_d0;
wire   [9:0] grp_bin_conv_fu_448_dmem_1_0_V_address0;
wire    grp_bin_conv_fu_448_dmem_1_0_V_ce0;
wire    grp_bin_conv_fu_448_dmem_1_0_V_we0;
wire   [63:0] grp_bin_conv_fu_448_dmem_1_0_V_d0;
wire   [9:0] grp_bin_conv_fu_448_dmem_1_1_V_address0;
wire    grp_bin_conv_fu_448_dmem_1_1_V_ce0;
wire    grp_bin_conv_fu_448_dmem_1_1_V_we0;
wire   [63:0] grp_bin_conv_fu_448_dmem_1_1_V_d0;
reg   [6:0] kh_i_reg_306;
reg   [12:0] indvar_flatten1_reg_317;
reg   [1:0] dmem_i_reg_328;
reg   [12:0] indvar_flatten_reg_339;
reg   [1:0] dmem_j_reg_350;
reg   [10:0] dmem_k_reg_361;
reg   [9:0] t_V_1_reg_372;
wire    ap_CS_fsm_state10;
reg   [6:0] t_V_reg_382;
reg    grp_bin_conv_fu_448_ap_start_reg;
wire   [63:0] tmp_3_fu_499_p1;
wire   [63:0] tmp_4_fu_621_p1;
wire   [63:0] tmp_i_fu_682_p1;
wire   [63:0] tmp_10_fu_986_p1;
wire   [31:0] p_s_fu_1058_p3;
wire    ap_CS_fsm_state13;
wire    ap_block_pp2_stage0_01001;
reg    ap_reg_ioackin_Output_1_V_V_ap_ack;
wire   [0:0] tmp_913_fu_549_p1;
wire   [0:0] dmem_j_t_mid2_fu_605_p3;
wire   [0:0] exitcond_flatten_fu_521_p2;
wire   [1:0] dmem_i_s_fu_535_p2;
wire   [0:0] tmp_914_fu_559_p1;
wire   [0:0] not_exitcond_flatten_fu_553_p2;
wire   [0:0] tmp_6_fu_569_p2;
wire   [1:0] dmem_j_mid_fu_527_p3;
wire   [0:0] tmp_9_mid_fu_575_p2;
wire   [0:0] tmp_9_fu_587_p2;
wire   [1:0] dmem_j_1_fu_581_p2;
wire   [0:0] tmp_915_fu_601_p1;
wire   [0:0] dmem_j_t_mid_fu_563_p2;
wire   [10:0] dmem_k_mid2_fu_593_p3;
wire   [12:0] indvar_flatten_op_fu_635_p2;
wire   [6:0] tmp_917_fu_657_p1;
wire   [4:0] r_V_fu_672_p4;
wire   [0:0] tmp_3_i_fu_702_p2;
wire   [0:0] tmp_4_i_fu_711_p2;
wire   [0:0] sel_tmp1_fu_751_p2;
wire   [0:0] sel_tmp6_demorgan_fu_763_p2;
wire   [0:0] tmp_5_i_fu_726_p2;
wire   [0:0] sel_tmp6_fu_769_p2;
wire   [0:0] sel_tmp7_fu_775_p2;
wire   [15:0] loc_V_2_fu_731_p4;
wire   [15:0] loc_V_1_fu_716_p4;
wire   [0:0] sel_tmp2_fu_757_p2;
wire   [15:0] loc_V_fu_707_p1;
wire   [15:0] loc_V_3_fu_741_p4;
wire   [0:0] or_cond_fu_789_p2;
wire   [15:0] newSel_fu_781_p3;
wire   [15:0] newSel1_fu_795_p3;
wire   [0:0] tmp_920_fu_818_p1;
wire   [0:0] tmp_921_fu_828_p1;
wire   [0:0] sel_tmp_fu_822_p2;
wire   [0:0] exitcond_flatten2_fu_856_p2;
wire   [1:0] dmem_i_1_fu_870_p2;
wire   [0:0] tmp_922_fu_876_p1;
wire   [0:0] sel_tmp_mid1_fu_888_p2;
wire   [0:0] sel_tmp4_fu_838_p2;
wire   [0:0] tmp_14_fu_914_p2;
wire   [1:0] dmem_j6_mid_fu_862_p3;
wire   [0:0] tmp_15_fu_940_p2;
wire   [1:0] dmem_j_2_fu_934_p2;
wire   [0:0] tmp_923_fu_954_p1;
wire   [0:0] sel_tmp_mid2_fu_894_p3;
wire   [0:0] sel_tmp4_mid1_fu_964_p2;
wire   [0:0] sel_tmp4_mid_fu_908_p2;
wire   [6:0] dmem_k7_mid2_fu_946_p3;
wire   [8:0] indvar_flatten20_op_fu_1000_p2;
wire   [0:0] sel_tmp3_mid_fu_1014_p2;
wire   [0:0] sel_tmp3_mid2_fu_1018_p3;
wire   [63:0] newSel3_fu_1024_p3;
wire   [63:0] newSel4_fu_1031_p3;
wire   [31:0] tmp_11_fu_1047_p2;
wire   [0:0] tmp_12_fu_1052_p2;
reg   [11:0] ap_NS_fsm;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_condition_859;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 bin_conv_cnt = 32'd0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 grp_bin_conv_fu_448_ap_start_reg = 1'b0;
#0 ap_reg_ioackin_Output_1_V_V_ap_ack = 1'b0;
end

bin_conv_2_o_indedEe #(
    .DataWidth( 9 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
o_index_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(o_index_list_address0),
    .ce0(o_index_list_ce0),
    .q0(o_index_list_q0)
);

bin_conv_2_d_o_ideOg #(
    .DataWidth( 1 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
d_o_idx_list_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(d_o_idx_list_V_address0),
    .ce0(d_o_idx_list_V_ce0),
    .q0(d_o_idx_list_V_q0)
);

bin_conv_2_n_inpufYi #(
    .DataWidth( 10 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
n_inputs_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(n_inputs_list_address0),
    .ce0(n_inputs_list_ce0),
    .q0(n_inputs_list_q0)
);

bin_conv_2_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_0_address0),
    .ce0(dmem_V_0_0_ce0),
    .we0(dmem_V_0_0_we0),
    .d0(dmem_V_0_0_d0),
    .q0(dmem_V_0_0_q0)
);

bin_conv_2_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_1_address0),
    .ce0(dmem_V_0_1_ce0),
    .we0(dmem_V_0_1_we0),
    .d0(dmem_V_0_1_d0),
    .q0(dmem_V_0_1_q0)
);

bin_conv_2_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_0_address0),
    .ce0(dmem_V_1_0_ce0),
    .we0(dmem_V_1_0_we0),
    .d0(dmem_V_1_0_d0),
    .q0(dmem_V_1_0_q0)
);

bin_conv_2_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_1_address0),
    .ce0(dmem_V_1_1_ce0),
    .we0(dmem_V_1_1_we0),
    .d0(dmem_V_1_1_d0),
    .q0(dmem_V_1_1_q0)
);

bin_conv_2_kh_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kh_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kh_mem_V_address0),
    .ce0(kh_mem_V_ce0),
    .we0(kh_mem_V_we0),
    .d0(Input_1_V_V),
    .q0(kh_mem_V_q0)
);

bin_conv grp_bin_conv_fu_448(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_conv_fu_448_ap_start),
    .ap_done(grp_bin_conv_fu_448_ap_done),
    .ap_idle(grp_bin_conv_fu_448_ap_idle),
    .ap_ready(grp_bin_conv_fu_448_ap_ready),
    .Input_1_V_V(Input_1_V_V),
    .Input_1_V_V_ap_vld(Input_1_V_V_ap_vld),
    .Input_1_V_V_ap_ack(grp_bin_conv_fu_448_Input_1_V_V_ap_ack),
    .nc_V(nc_V_reg_1206),
    .dmem_0_0_V_address0(grp_bin_conv_fu_448_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_bin_conv_fu_448_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_bin_conv_fu_448_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_bin_conv_fu_448_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_bin_conv_fu_448_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_bin_conv_fu_448_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_bin_conv_fu_448_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_bin_conv_fu_448_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_bin_conv_fu_448_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_bin_conv_fu_448_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_bin_conv_fu_448_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_bin_conv_fu_448_dmem_1_0_V_d0),
    .dmem_1_1_V_address0(grp_bin_conv_fu_448_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_bin_conv_fu_448_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_bin_conv_fu_448_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_bin_conv_fu_448_dmem_1_1_V_d0),
    .d_o_idx_V(d_o_idx_list_V_load_reg_1161),
    .n_inputs(n_inputs_list_load_reg_1166),
    .o_index_V(t_V_1_reg_372),
    .new_batch_V(this_assign_1_reg_1197)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state11) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state11))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state11);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_859)) begin
            if ((1'b0 == ap_block_pp2_stage0_11001)) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
            end else if (((1'b0 == ap_block_pp2_stage0_01001) & (1'b1 == Output_1_V_V_ap_ack))) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bin_conv_fu_448_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_bin_conv_fu_448_ap_start_reg <= 1'b1;
        end else if ((grp_bin_conv_fu_448_ap_ready == 1'b1)) begin
            grp_bin_conv_fu_448_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_i5_reg_404 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_844_p2 == 1'd0))) begin
        dmem_i5_reg_404 <= dmem_i5_mid2_fu_926_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_2_fu_504_p2 == 1'd1))) begin
        dmem_i_reg_328 <= 2'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_i_reg_328 <= dmem_i_t_mid2_v_fu_541_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_j6_reg_426 <= 2'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_844_p2 == 1'd0))) begin
        dmem_j6_reg_426 <= dmem_j6_mid2_fu_978_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_2_fu_504_p2 == 1'd1))) begin
        dmem_j_reg_350 <= 2'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_j_reg_350 <= dmem_j_mid2_fu_613_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        dmem_k7_reg_437 <= 7'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_844_p2 == 1'd0))) begin
        dmem_k7_reg_437 <= dmem_k_2_fu_994_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_2_fu_504_p2 == 1'd1))) begin
        dmem_k_reg_361 <= 11'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_k_reg_361 <= dmem_k_1_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_2_fu_504_p2 == 1'd1))) begin
        indvar_flatten1_reg_317 <= 13'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        indvar_flatten1_reg_317 <= indvar_flatten_next1_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten2_reg_393 <= 9'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_844_p2 == 1'd0))) begin
        indvar_flatten2_reg_393 <= indvar_flatten_next3_fu_850_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten3_reg_415 <= 9'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_844_p2 == 1'd0))) begin
        indvar_flatten3_reg_415 <= indvar_flatten_next2_fu_1006_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_2_fu_504_p2 == 1'd1))) begin
        indvar_flatten_reg_339 <= 13'd0;
    end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        indvar_flatten_reg_339 <= indvar_flatten_next_fu_641_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_487_p2 == 1'd0))) begin
        kh_i_reg_306 <= kh_i_1_fu_493_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        kh_i_reg_306 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_448_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        t_V_1_reg_372 <= o_index_V_1_reg_1211;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_1_reg_372 <= o_index_V_cast_reg_1095;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_448_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        t_V_reg_382 <= kh_index_V_reg_1180;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_382 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        bin_conv_cnt <= p_s_fu_1058_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bin_conv_cnt_load_reg_1072 <= bin_conv_cnt;
        tmp_s_reg_1079[31 : 0] <= tmp_s_fu_478_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        d_o_idx_list_V_load_reg_1161 <= d_o_idx_list_V_q0;
        n_inputs_list_load_reg_1166 <= n_inputs_list_q0;
        tmp_13_reg_1171 <= tmp_13_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_fu_844_p2 == 1'd0))) begin
        dmem_i5_t_mid2_reg_1230 <= dmem_i5_t_mid2_fu_880_p3;
        not_exitcond_flatten_2_reg_1235 <= not_exitcond_flatten_2_fu_902_p2;
        sel_tmp3_mid1_reg_1250 <= sel_tmp3_mid1_fu_958_p2;
        sel_tmp4_mid2_reg_1255 <= sel_tmp4_mid2_fu_970_p3;
        tmp_15_mid_reg_1240 <= tmp_15_mid_fu_920_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        exitcond_flatten3_reg_1221 <= exitcond_flatten3_fu_844_p2;
        sel_tmp3_reg_1216 <= sel_tmp3_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kh_index_V_reg_1180 <= kh_index_V_fu_666_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        nc_V_reg_1206 <= nc_V_fu_803_p3;
        o_index_V_1_reg_1211 <= o_index_V_1_fu_812_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        o_index_V_cast_reg_1095[8 : 0] <= o_index_V_cast_fu_483_p1[8 : 0];
        o_index_V_reg_1090 <= o_index_list_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond_fu_661_p2 == 1'd0))) begin
        off_V_reg_1190 <= off_V_fu_687_p1;
        this_assign_1_reg_1197 <= this_assign_1_fu_691_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_916_reg_1156 <= tmp_916_fu_649_p1;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_487_p2 == 1'd0))) begin
        Input_1_V_V_ap_ack = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        Input_1_V_V_ap_ack = grp_bin_conv_fu_448_Input_1_V_V_ap_ack;
    end else begin
        Input_1_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_487_p2 == 1'd0))) begin
        Input_1_V_V_blk_n = Input_1_V_V_ap_vld;
    end else begin
        Input_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        Input_2_V_V_ap_ack = 1'b1;
    end else begin
        Input_2_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        Input_2_V_V_blk_n = Input_2_V_V_ap_vld;
    end else begin
        Input_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_01001) & (ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_reg_1221 == 1'd0))) begin
        Output_1_V_V_ap_vld = 1'b1;
    end else begin
        Output_1_V_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0) & (exitcond_flatten3_reg_1221 == 1'd0))) begin
        Output_1_V_V_blk_n = Output_1_V_V_ap_ack;
    end else begin
        Output_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond_flatten3_fu_844_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0)) begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = Output_1_V_V_ap_ack;
    end else begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_o_idx_list_V_ce0 = 1'b1;
    end else begin
        d_o_idx_list_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_0_address0 = tmp_10_fu_986_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_0_address0 = tmp_4_fu_621_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_address0 = grp_bin_conv_fu_448_dmem_0_0_V_address0;
    end else begin
        dmem_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_0_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_ce0 = grp_bin_conv_fu_448_dmem_0_0_V_ce0;
    end else begin
        dmem_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_0_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_d0 = grp_bin_conv_fu_448_dmem_0_0_V_d0;
    end else begin
        dmem_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (dmem_j_t_mid2_fu_605_p3 == 1'd0) & (tmp_913_fu_549_p1 == 1'd0) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_V_0_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_0_we0 = grp_bin_conv_fu_448_dmem_0_0_V_we0;
    end else begin
        dmem_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_1_address0 = tmp_10_fu_986_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_1_address0 = tmp_4_fu_621_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_address0 = grp_bin_conv_fu_448_dmem_0_1_V_address0;
    end else begin
        dmem_V_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_0_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_ce0 = grp_bin_conv_fu_448_dmem_0_1_V_ce0;
    end else begin
        dmem_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_0_1_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_d0 = grp_bin_conv_fu_448_dmem_0_1_V_d0;
    end else begin
        dmem_V_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (dmem_j_t_mid2_fu_605_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_913_fu_549_p1 == 1'd0) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_V_0_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_0_1_we0 = grp_bin_conv_fu_448_dmem_0_1_V_we0;
    end else begin
        dmem_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_0_address0 = tmp_10_fu_986_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_0_address0 = tmp_4_fu_621_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_address0 = grp_bin_conv_fu_448_dmem_1_0_V_address0;
    end else begin
        dmem_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_1_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_ce0 = grp_bin_conv_fu_448_dmem_1_0_V_ce0;
    end else begin
        dmem_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_0_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_d0 = grp_bin_conv_fu_448_dmem_1_0_V_d0;
    end else begin
        dmem_V_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (tmp_913_fu_549_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (dmem_j_t_mid2_fu_605_p3 == 1'd0) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_V_1_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_0_we0 = grp_bin_conv_fu_448_dmem_1_0_V_we0;
    end else begin
        dmem_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_1_address0 = tmp_10_fu_986_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_1_address0 = tmp_4_fu_621_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_address0 = grp_bin_conv_fu_448_dmem_1_1_V_address0;
    end else begin
        dmem_V_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | (~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        dmem_V_1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_ce0 = grp_bin_conv_fu_448_dmem_1_1_V_ce0;
    end else begin
        dmem_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dmem_V_1_1_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_d0 = grp_bin_conv_fu_448_dmem_1_1_V_d0;
    end else begin
        dmem_V_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (dmem_j_t_mid2_fu_605_p3 == 1'd1) & (tmp_913_fu_549_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
        dmem_V_1_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dmem_V_1_1_we0 = grp_bin_conv_fu_448_dmem_1_1_V_we0;
    end else begin
        dmem_V_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kh_mem_V_address0 = tmp_i_fu_682_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kh_mem_V_address0 = tmp_3_fu_499_p1;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3)))) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_487_p2 == 1'd0))) begin
        kh_mem_V_we0 = 1'b1;
    end else begin
        kh_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        n_inputs_list_ce0 = 1'b1;
    end else begin
        n_inputs_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_index_list_ce0 = 1'b1;
    end else begin
        o_index_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_487_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_487_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (tmp_2_fu_504_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5) & (exitcond_flatten1_fu_509_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((tmp_5_fu_697_p2 == 1'd1) & (exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((exitcond_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8) & (tmp_5_fu_697_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_bin_conv_fu_448_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond_flatten3_fu_844_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (exitcond_flatten3_fu_844_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_1_V_V = ((dmem_i5_t_mid2_reg_1230[0:0] === 1'b1) ? newSel3_fu_1024_p3 : newSel4_fu_1031_p3);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_state11_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_io = ((ap_sig_ioackin_Output_1_V_V_ap_ack == 1'b0) & (exitcond_flatten3_reg_1221 == 1'd0));
end

assign ap_block_state12_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3 = ((1'b0 == Input_1_V_V_ap_vld) & (tmp_1_fu_487_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state5 = ((1'b0 == Input_2_V_V_ap_vld) & (exitcond_flatten1_fu_509_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_859 = ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (exitcond_flatten3_reg_1221 == 1'd0));
end

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign d_o_idx_list_V_address0 = tmp_s_reg_1079;

assign dmem_i5_mid2_fu_926_p3 = ((exitcond_flatten2_fu_856_p2[0:0] === 1'b1) ? dmem_i_1_fu_870_p2 : dmem_i5_reg_404);

assign dmem_i5_t_mid2_fu_880_p3 = ((exitcond_flatten2_fu_856_p2[0:0] === 1'b1) ? tmp_922_fu_876_p1 : tmp_920_fu_818_p1);

assign dmem_i_1_fu_870_p2 = (2'd1 + dmem_i5_reg_404);

assign dmem_i_s_fu_535_p2 = (2'd1 + dmem_i_reg_328);

assign dmem_i_t_mid2_v_fu_541_p3 = ((exitcond_flatten_fu_521_p2[0:0] === 1'b1) ? dmem_i_s_fu_535_p2 : dmem_i_reg_328);

assign dmem_j6_mid2_fu_978_p3 = ((tmp_15_mid_fu_920_p2[0:0] === 1'b1) ? dmem_j_2_fu_934_p2 : dmem_j6_mid_fu_862_p3);

assign dmem_j6_mid_fu_862_p3 = ((exitcond_flatten2_fu_856_p2[0:0] === 1'b1) ? 2'd0 : dmem_j6_reg_426);

assign dmem_j_1_fu_581_p2 = (2'd1 + dmem_j_mid_fu_527_p3);

assign dmem_j_2_fu_934_p2 = (2'd1 + dmem_j6_mid_fu_862_p3);

assign dmem_j_mid2_fu_613_p3 = ((tmp_9_mid_fu_575_p2[0:0] === 1'b1) ? dmem_j_1_fu_581_p2 : dmem_j_mid_fu_527_p3);

assign dmem_j_mid_fu_527_p3 = ((exitcond_flatten_fu_521_p2[0:0] === 1'b1) ? 2'd0 : dmem_j_reg_350);

assign dmem_j_t_mid2_fu_605_p3 = ((tmp_9_mid_fu_575_p2[0:0] === 1'b1) ? tmp_915_fu_601_p1 : dmem_j_t_mid_fu_563_p2);

assign dmem_j_t_mid_fu_563_p2 = (tmp_914_fu_559_p1 & not_exitcond_flatten_fu_553_p2);

assign dmem_k7_mid2_fu_946_p3 = ((tmp_15_fu_940_p2[0:0] === 1'b1) ? 7'd0 : dmem_k7_reg_437);

assign dmem_k_1_fu_629_p2 = (dmem_k_mid2_fu_593_p3 + 11'd1);

assign dmem_k_2_fu_994_p2 = (7'd1 + dmem_k7_mid2_fu_946_p3);

assign dmem_k_mid2_fu_593_p3 = ((tmp_9_fu_587_p2[0:0] === 1'b1) ? 11'd0 : dmem_k_reg_361);

assign exitcond_flatten1_fu_509_p2 = ((indvar_flatten1_reg_317 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_856_p2 = ((indvar_flatten3_reg_415 == 9'd128) ? 1'b1 : 1'b0);

assign exitcond_flatten3_fu_844_p2 = ((indvar_flatten2_reg_393 == 9'd256) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_521_p2 = ((indvar_flatten_reg_339 == 13'd2048) ? 1'b1 : 1'b0);

assign exitcond_fu_661_p2 = ((tmp_917_fu_657_p1 == tmp_13_reg_1171) ? 1'b1 : 1'b0);

assign grp_bin_conv_fu_448_ap_start = grp_bin_conv_fu_448_ap_start_reg;

assign indvar_flatten20_op_fu_1000_p2 = (9'd1 + indvar_flatten3_reg_415);

assign indvar_flatten_next1_fu_515_p2 = (indvar_flatten1_reg_317 + 13'd1);

assign indvar_flatten_next2_fu_1006_p3 = ((exitcond_flatten2_fu_856_p2[0:0] === 1'b1) ? 9'd1 : indvar_flatten20_op_fu_1000_p2);

assign indvar_flatten_next3_fu_850_p2 = (9'd1 + indvar_flatten2_reg_393);

assign indvar_flatten_next_fu_641_p3 = ((exitcond_flatten_fu_521_p2[0:0] === 1'b1) ? 13'd1 : indvar_flatten_op_fu_635_p2);

assign indvar_flatten_op_fu_635_p2 = (indvar_flatten_reg_339 + 13'd1);

assign kh_i_1_fu_493_p2 = (kh_i_reg_306 + 7'd1);

assign kh_index_V_fu_666_p2 = (7'd1 + t_V_reg_382);

assign loc_V_1_fu_716_p4 = {{kh_mem_V_q0[31:16]}};

assign loc_V_2_fu_731_p4 = {{kh_mem_V_q0[47:32]}};

assign loc_V_3_fu_741_p4 = {{kh_mem_V_q0[63:48]}};

assign loc_V_fu_707_p1 = kh_mem_V_q0[15:0];

assign n_inputs_list_address0 = tmp_s_reg_1079;

assign nc_V_fu_803_p3 = ((or_cond_fu_789_p2[0:0] === 1'b1) ? newSel_fu_781_p3 : newSel1_fu_795_p3);

assign newSel1_fu_795_p3 = ((tmp_3_i_fu_702_p2[0:0] === 1'b1) ? loc_V_fu_707_p1 : loc_V_3_fu_741_p4);

assign newSel3_fu_1024_p3 = ((sel_tmp4_mid2_reg_1255[0:0] === 1'b1) ? dmem_V_1_1_q0 : dmem_V_1_0_q0);

assign newSel4_fu_1031_p3 = ((sel_tmp3_mid2_fu_1018_p3[0:0] === 1'b1) ? dmem_V_0_1_q0 : dmem_V_0_0_q0);

assign newSel_fu_781_p3 = ((sel_tmp7_fu_775_p2[0:0] === 1'b1) ? loc_V_2_fu_731_p4 : loc_V_1_fu_716_p4);

assign not_exitcond_flatten_2_fu_902_p2 = (exitcond_flatten2_fu_856_p2 ^ 1'd1);

assign not_exitcond_flatten_fu_553_p2 = (exitcond_flatten_fu_521_p2 ^ 1'd1);

assign o_index_V_1_fu_812_p2 = (10'd1 + t_V_1_reg_372);

assign o_index_V_cast_fu_483_p1 = o_index_list_q0;

assign o_index_list_address0 = tmp_s_fu_478_p1;

assign off_V_fu_687_p1 = t_V_reg_382[1:0];

assign or_cond_fu_789_p2 = (sel_tmp7_fu_775_p2 | sel_tmp2_fu_757_p2);

assign p_s_fu_1058_p3 = ((tmp_12_fu_1052_p2[0:0] === 1'b1) ? 32'd0 : tmp_11_fu_1047_p2);

assign r_V_fu_672_p4 = {{t_V_reg_382[6:2]}};

assign sel_tmp1_fu_751_p2 = (tmp_3_i_fu_702_p2 ^ 1'd1);

assign sel_tmp2_fu_757_p2 = (tmp_4_i_fu_711_p2 & sel_tmp1_fu_751_p2);

assign sel_tmp3_fu_832_p2 = (tmp_921_fu_828_p1 & sel_tmp_fu_822_p2);

assign sel_tmp3_mid1_fu_958_p2 = (tmp_923_fu_954_p1 & sel_tmp_mid2_fu_894_p3);

assign sel_tmp3_mid2_fu_1018_p3 = ((tmp_15_mid_reg_1240[0:0] === 1'b1) ? sel_tmp3_mid1_reg_1250 : sel_tmp3_mid_fu_1014_p2);

assign sel_tmp3_mid_fu_1014_p2 = (sel_tmp3_reg_1216 & not_exitcond_flatten_2_reg_1235);

assign sel_tmp4_fu_838_p2 = (tmp_921_fu_828_p1 & tmp_920_fu_818_p1);

assign sel_tmp4_mid1_fu_964_p2 = (tmp_923_fu_954_p1 & dmem_i5_t_mid2_fu_880_p3);

assign sel_tmp4_mid2_fu_970_p3 = ((tmp_15_mid_fu_920_p2[0:0] === 1'b1) ? sel_tmp4_mid1_fu_964_p2 : sel_tmp4_mid_fu_908_p2);

assign sel_tmp4_mid_fu_908_p2 = (sel_tmp4_fu_838_p2 & not_exitcond_flatten_2_fu_902_p2);

assign sel_tmp6_demorgan_fu_763_p2 = (tmp_4_i_fu_711_p2 | tmp_3_i_fu_702_p2);

assign sel_tmp6_fu_769_p2 = (sel_tmp6_demorgan_fu_763_p2 ^ 1'd1);

assign sel_tmp7_fu_775_p2 = (tmp_5_i_fu_726_p2 & sel_tmp6_fu_769_p2);

assign sel_tmp_fu_822_p2 = (tmp_920_fu_818_p1 ^ 1'd1);

assign sel_tmp_mid1_fu_888_p2 = (tmp_922_fu_876_p1 ^ 1'd1);

assign sel_tmp_mid2_fu_894_p3 = ((exitcond_flatten2_fu_856_p2[0:0] === 1'b1) ? sel_tmp_mid1_fu_888_p2 : sel_tmp_fu_822_p2);

assign this_assign_1_fu_691_p2 = ((t_V_reg_382 == 7'd0) ? 1'b1 : 1'b0);

assign tmp_10_fu_986_p1 = dmem_k7_mid2_fu_946_p3;

assign tmp_11_fu_1047_p2 = (bin_conv_cnt_load_reg_1072 + 32'd1);

assign tmp_12_fu_1052_p2 = ((tmp_11_fu_1047_p2 == 32'd6) ? 1'b1 : 1'b0);

assign tmp_13_fu_652_p2 = (tmp_916_reg_1156 ^ 7'd64);

assign tmp_14_fu_914_p2 = ((dmem_k7_reg_437 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_15_fu_940_p2 = (tmp_15_mid_fu_920_p2 | exitcond_flatten2_fu_856_p2);

assign tmp_15_mid_fu_920_p2 = (tmp_14_fu_914_p2 & not_exitcond_flatten_2_fu_902_p2);

assign tmp_1_fu_487_p2 = ((kh_i_reg_306 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_2_fu_504_p2 = ((bin_conv_cnt_load_reg_1072 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_499_p1 = kh_i_reg_306;

assign tmp_3_i_fu_702_p2 = ((off_V_reg_1190 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_621_p1 = dmem_k_mid2_fu_593_p3;

assign tmp_4_i_fu_711_p2 = ((off_V_reg_1190 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_5_fu_697_p2 = ((bin_conv_cnt_load_reg_1072 == 32'd5) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_726_p2 = ((off_V_reg_1190 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_6_fu_569_p2 = ((dmem_k_reg_361 == 11'd1024) ? 1'b1 : 1'b0);

assign tmp_913_fu_549_p1 = dmem_i_t_mid2_v_fu_541_p3[0:0];

assign tmp_914_fu_559_p1 = dmem_j_reg_350[0:0];

assign tmp_915_fu_601_p1 = dmem_j_1_fu_581_p2[0:0];

assign tmp_916_fu_649_p1 = o_index_V_reg_1090[6:0];

assign tmp_917_fu_657_p1 = t_V_1_reg_372[6:0];

assign tmp_920_fu_818_p1 = dmem_i5_reg_404[0:0];

assign tmp_921_fu_828_p1 = dmem_j6_reg_426[0:0];

assign tmp_922_fu_876_p1 = dmem_i_1_fu_870_p2[0:0];

assign tmp_923_fu_954_p1 = dmem_j_2_fu_934_p2[0:0];

assign tmp_9_fu_587_p2 = (tmp_9_mid_fu_575_p2 | exitcond_flatten_fu_521_p2);

assign tmp_9_mid_fu_575_p2 = (tmp_6_fu_569_p2 & not_exitcond_flatten_fu_553_p2);

assign tmp_i_fu_682_p1 = r_V_fu_672_p4;

assign tmp_s_fu_478_p1 = bin_conv_cnt;

always @ (posedge ap_clk) begin
    tmp_s_reg_1079[63:32] <= 32'b00000000000000000000000000000000;
    o_index_V_cast_reg_1095[9] <= 1'b0;
end

endmodule //bin_conv_2
