// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bin_conv_0,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.749500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=40,HLS_SYN_DSP=2,HLS_SYN_FF=6348,HLS_SYN_LUT=35634,HLS_VERSION=2018_2}" *)

module bin_conv_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_V_V,
        Input_1_V_V_ap_vld,
        Input_1_V_V_ap_ack,
        Input_2_V_V,
        Input_2_V_V_ap_vld,
        Input_2_V_V_ap_ack,
        Output_1_V_V,
        Output_1_V_V_ap_vld,
        Output_1_V_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_pp2_stage0 = 11'd512;
parameter    ap_ST_fsm_state12 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] Input_1_V_V;
input   Input_1_V_V_ap_vld;
output   Input_1_V_V_ap_ack;
input  [63:0] Input_2_V_V;
input   Input_2_V_V_ap_vld;
output   Input_2_V_V_ap_ack;
output  [63:0] Output_1_V_V;
output   Output_1_V_V_ap_vld;
input   Output_1_V_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Input_1_V_V_ap_ack;
reg Input_2_V_V_ap_ack;
reg Output_1_V_V_ap_vld;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] bin_conv_cnt;
reg   [9:0] dmem_V_0_0_address0;
reg    dmem_V_0_0_ce0;
reg    dmem_V_0_0_we0;
reg   [63:0] dmem_V_0_0_d0;
wire   [63:0] dmem_V_0_0_q0;
reg   [9:0] dmem_V_0_1_address0;
reg    dmem_V_0_1_ce0;
reg    dmem_V_0_1_we0;
reg   [63:0] dmem_V_0_1_d0;
wire   [63:0] dmem_V_0_1_q0;
reg   [9:0] dmem_V_1_0_address0;
reg    dmem_V_1_0_ce0;
reg    dmem_V_1_0_we0;
wire   [63:0] dmem_V_1_0_q0;
reg   [9:0] dmem_V_1_1_address0;
reg    dmem_V_1_1_ce0;
reg    dmem_V_1_1_we0;
wire   [63:0] dmem_V_1_1_q0;
reg    Input_1_V_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_s_fu_434_p2;
reg    Input_2_V_V_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond_flatten_fu_456_p2;
reg    Output_1_V_V_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] exitcond_flatten1_reg_1102;
reg   [12:0] indvar_flatten1_reg_330;
reg   [1:0] dmem_i_reg_341;
reg   [12:0] indvar_flatten6_reg_352;
reg   [1:0] dmem_j5_reg_363;
reg   [10:0] dmem_k6_reg_374;
reg   [31:0] bin_conv_cnt_load_reg_985;
wire   [1:0] tmp_1045_fu_418_p1;
reg   [1:0] tmp_1045_reg_992;
wire   [15:0] n_outputs_V_fu_422_p5;
reg   [15:0] n_outputs_V_reg_1001;
wire   [6:0] kh_i_1_fu_440_p2;
reg    ap_block_state2;
wire   [0:0] tmp_1_fu_451_p2;
wire    ap_CS_fsm_state3;
wire   [11:0] indvar_flatten_next_fu_462_p2;
reg    ap_block_state4;
wire   [1:0] dmem_j_t_mid2_v_fu_488_p3;
wire   [10:0] dmem_k_1_fu_506_p2;
wire   [0:0] exitcond_fu_512_p2;
wire    ap_CS_fsm_state6;
wire   [15:0] kh_index_V_fu_517_p2;
reg   [15:0] kh_index_V_reg_1043;
wire   [0:0] this_assign_1_fu_538_p2;
reg   [0:0] this_assign_1_reg_1053;
wire   [9:0] i_V_fu_544_p2;
reg   [9:0] i_V_reg_1058;
wire   [0:0] tmp_6_fu_550_p2;
wire   [15:0] nc_V_fu_663_p3;
reg   [15:0] nc_V_reg_1067;
wire    ap_CS_fsm_state7;
wire   [0:0] tmp_3_fu_671_p5;
reg   [0:0] tmp_3_reg_1072;
wire    ap_CS_fsm_state8;
wire   [0:0] tmp_7_fu_683_p5;
reg   [0:0] tmp_7_reg_1077;
wire   [15:0] tmp_9_fu_695_p5;
reg   [15:0] tmp_9_reg_1082;
wire   [1:0] tmp_12_fu_707_p5;
reg   [1:0] tmp_12_reg_1087;
wire   [1:0] tmp_13_fu_719_p5;
reg   [1:0] tmp_13_reg_1092;
wire   [0:0] sel_tmp3_fu_745_p2;
reg   [0:0] sel_tmp3_reg_1097;
wire    ap_block_state10_pp2_stage0_iter0;
wire    ap_block_state11_pp2_stage0_iter1;
reg    ap_sig_ioackin_Output_1_V_V_ap_ack;
reg    ap_block_state11_io;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] exitcond_flatten1_fu_757_p2;
wire   [12:0] indvar_flatten_next1_fu_763_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] dmem_i_t_mid2_fu_793_p3;
reg   [0:0] dmem_i_t_mid2_reg_1111;
wire   [0:0] not_exitcond_flatten_fu_815_p2;
reg   [0:0] not_exitcond_flatten_reg_1116;
wire   [0:0] tmp_13_mid_fu_833_p2;
reg   [0:0] tmp_13_mid_reg_1121;
wire   [1:0] dmem_i_mid2_fu_839_p3;
wire   [0:0] sel_tmp3_mid1_fu_871_p2;
reg   [0:0] sel_tmp3_mid1_reg_1131;
wire   [0:0] sel_tmp4_mid2_fu_883_p3;
reg   [0:0] sel_tmp4_mid2_reg_1136;
wire   [1:0] dmem_j5_mid2_fu_891_p3;
wire   [10:0] dmem_k_2_fu_907_p2;
wire   [12:0] indvar_flatten_next7_fu_919_p3;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state10;
reg   [5:0] kh_mem_V_address0;
reg    kh_mem_V_ce0;
reg    kh_mem_V_we0;
wire   [63:0] kh_mem_V_q0;
wire    grp_bin_conv_fu_385_ap_start;
wire    grp_bin_conv_fu_385_ap_done;
wire    grp_bin_conv_fu_385_ap_idle;
wire    grp_bin_conv_fu_385_ap_ready;
wire    grp_bin_conv_fu_385_Input_1_V_V_ap_ack;
wire   [9:0] grp_bin_conv_fu_385_dmem_0_0_V_address0;
wire    grp_bin_conv_fu_385_dmem_0_0_V_ce0;
wire    grp_bin_conv_fu_385_dmem_0_0_V_we0;
wire   [63:0] grp_bin_conv_fu_385_dmem_0_0_V_d0;
wire   [9:0] grp_bin_conv_fu_385_dmem_0_1_V_address0;
wire    grp_bin_conv_fu_385_dmem_0_1_V_ce0;
wire    grp_bin_conv_fu_385_dmem_0_1_V_we0;
wire   [63:0] grp_bin_conv_fu_385_dmem_0_1_V_d0;
wire   [9:0] grp_bin_conv_fu_385_dmem_1_0_V_address0;
wire    grp_bin_conv_fu_385_dmem_1_0_V_ce0;
wire    grp_bin_conv_fu_385_dmem_1_0_V_we0;
wire   [63:0] grp_bin_conv_fu_385_dmem_1_0_V_d0;
wire   [9:0] grp_bin_conv_fu_385_dmem_1_1_V_address0;
wire    grp_bin_conv_fu_385_dmem_1_1_V_ce0;
wire    grp_bin_conv_fu_385_dmem_1_1_V_we0;
wire   [63:0] grp_bin_conv_fu_385_dmem_1_1_V_d0;
reg   [6:0] kh_i_reg_263;
reg   [11:0] indvar_flatten_reg_274;
reg   [1:0] dmem_j_reg_285;
reg   [10:0] dmem_k_reg_296;
reg   [15:0] t_V_reg_307;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state9;
reg   [9:0] p_2_reg_319;
reg    grp_bin_conv_fu_385_ap_start_reg;
wire   [63:0] tmp_2_fu_446_p1;
wire   [63:0] tmp_8_fu_500_p1;
wire   [63:0] tmp_i_fu_533_p1;
wire   [63:0] tmp_15_fu_899_p1;
wire   [31:0] p_s_fu_971_p3;
wire    ap_CS_fsm_state12;
wire    ap_block_pp2_stage0_01001;
reg    ap_reg_ioackin_Output_1_V_V_ap_ack;
wire   [0:0] tmp_1046_fu_496_p1;
wire   [1:0] n_outputs_V_fu_422_p4;
wire   [0:0] tmp_5_fu_468_p2;
wire   [1:0] dmem_j_s_fu_482_p2;
wire   [10:0] dmem_k_mid2_fu_474_p3;
wire   [13:0] r_V_fu_523_p4;
wire   [1:0] off_V_fu_555_p1;
wire   [0:0] tmp_3_i_fu_559_p2;
wire   [0:0] tmp_4_i_fu_569_p2;
wire   [0:0] sel_tmp1_fu_611_p2;
wire   [0:0] sel_tmp6_demorgan_fu_623_p2;
wire   [0:0] tmp_5_i_fu_585_p2;
wire   [0:0] sel_tmp6_fu_629_p2;
wire   [0:0] sel_tmp7_fu_635_p2;
wire   [15:0] loc_V_2_fu_591_p4;
wire   [15:0] loc_V_1_fu_575_p4;
wire   [0:0] sel_tmp2_fu_617_p2;
wire   [15:0] loc_V_fu_565_p1;
wire   [15:0] loc_V_3_fu_601_p4;
wire   [0:0] or_cond_fu_649_p2;
wire   [15:0] newSel_fu_641_p3;
wire   [15:0] newSel1_fu_655_p3;
wire   [0:0] tmp_1049_fu_731_p1;
wire   [0:0] tmp_1050_fu_741_p1;
wire   [0:0] sel_tmp_fu_735_p2;
wire   [0:0] exitcond_flatten2_fu_769_p2;
wire   [1:0] dmem_i_s_fu_783_p2;
wire   [0:0] tmp_1051_fu_789_p1;
wire   [0:0] sel_tmp_mid1_fu_801_p2;
wire   [0:0] sel_tmp4_fu_751_p2;
wire   [0:0] tmp_16_fu_827_p2;
wire   [1:0] dmem_j5_mid_fu_775_p3;
wire   [0:0] tmp_17_fu_853_p2;
wire   [1:0] dmem_j_1_fu_847_p2;
wire   [0:0] tmp_1052_fu_867_p1;
wire   [0:0] sel_tmp_mid2_fu_807_p3;
wire   [0:0] sel_tmp4_mid1_fu_877_p2;
wire   [0:0] sel_tmp4_mid_fu_821_p2;
wire   [10:0] dmem_k6_mid2_fu_859_p3;
wire   [12:0] indvar_flatten6_op_fu_913_p2;
wire   [0:0] sel_tmp3_mid_fu_927_p2;
wire   [0:0] sel_tmp3_mid2_fu_931_p3;
wire   [63:0] newSel3_fu_937_p3;
wire   [63:0] newSel4_fu_944_p3;
wire   [31:0] tmp_10_fu_960_p2;
wire   [0:0] tmp_11_fu_965_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_condition_788;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 bin_conv_cnt = 32'd0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 grp_bin_conv_fu_385_ap_start_reg = 1'b0;
#0 ap_reg_ioackin_Output_1_V_V_ap_ack = 1'b0;
end

bin_conv_0_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_0_address0),
    .ce0(dmem_V_0_0_ce0),
    .we0(dmem_V_0_0_we0),
    .d0(dmem_V_0_0_d0),
    .q0(dmem_V_0_0_q0)
);

bin_conv_0_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_1_address0),
    .ce0(dmem_V_0_1_ce0),
    .we0(dmem_V_0_1_we0),
    .d0(dmem_V_0_1_d0),
    .q0(dmem_V_0_1_q0)
);

bin_conv_0_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_0_address0),
    .ce0(dmem_V_1_0_ce0),
    .we0(dmem_V_1_0_we0),
    .d0(grp_bin_conv_fu_385_dmem_1_0_V_d0),
    .q0(dmem_V_1_0_q0)
);

bin_conv_0_dmem_Vg8j #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_1_address0),
    .ce0(dmem_V_1_1_ce0),
    .we0(dmem_V_1_1_we0),
    .d0(grp_bin_conv_fu_385_dmem_1_1_V_d0),
    .q0(dmem_V_1_1_q0)
);

bin_conv_0_kh_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kh_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kh_mem_V_address0),
    .ce0(kh_mem_V_ce0),
    .we0(kh_mem_V_we0),
    .d0(Input_1_V_V),
    .q0(kh_mem_V_q0)
);

bin_conv grp_bin_conv_fu_385(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_conv_fu_385_ap_start),
    .ap_done(grp_bin_conv_fu_385_ap_done),
    .ap_idle(grp_bin_conv_fu_385_ap_idle),
    .ap_ready(grp_bin_conv_fu_385_ap_ready),
    .Input_1_V_V(Input_1_V_V),
    .Input_1_V_V_ap_vld(Input_1_V_V_ap_vld),
    .Input_1_V_V_ap_ack(grp_bin_conv_fu_385_Input_1_V_V_ap_ack),
    .nc_V(nc_V_reg_1067),
    .dmem_0_0_V_address0(grp_bin_conv_fu_385_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_bin_conv_fu_385_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_bin_conv_fu_385_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_bin_conv_fu_385_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_bin_conv_fu_385_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_bin_conv_fu_385_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_bin_conv_fu_385_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_bin_conv_fu_385_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_bin_conv_fu_385_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_bin_conv_fu_385_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_bin_conv_fu_385_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_bin_conv_fu_385_dmem_1_0_V_d0),
    .dmem_1_0_V_q0(dmem_V_1_0_q0),
    .dmem_1_1_V_address0(grp_bin_conv_fu_385_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_bin_conv_fu_385_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_bin_conv_fu_385_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_bin_conv_fu_385_dmem_1_1_V_d0),
    .dmem_1_1_V_q0(dmem_V_1_1_q0),
    .d_i_idx_V(tmp_3_reg_1072),
    .d_o_idx_V(tmp_7_reg_1077),
    .n_inputs(tmp_9_reg_1082),
    .o_index_V(t_V_reg_307),
    .new_batch_V(this_assign_1_reg_1053),
    .width_mode_V(tmp_12_reg_1087),
    .norm_mode_V(tmp_13_reg_1092)
);

bin_conv_0_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
bin_conv_0_mux_32kbM_U303(
    .din0(16'd128),
    .din1(16'd256),
    .din2(16'd128),
    .din3(n_outputs_V_fu_422_p4),
    .dout(n_outputs_V_fu_422_p5)
);

bin_conv_0_mux_32lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
bin_conv_0_mux_32lbW_U304(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd0),
    .din3(tmp_1045_reg_992),
    .dout(tmp_3_fu_671_p5)
);

bin_conv_0_mux_32lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
bin_conv_0_mux_32lbW_U305(
    .din0(1'd1),
    .din1(1'd0),
    .din2(1'd1),
    .din3(tmp_1045_reg_992),
    .dout(tmp_7_fu_683_p5)
);

bin_conv_0_mux_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
bin_conv_0_mux_32kbM_U306(
    .din0(16'd128),
    .din1(16'd128),
    .din2(16'd256),
    .din3(tmp_1045_reg_992),
    .dout(tmp_9_fu_695_p5)
);

bin_conv_0_mux_32mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 2 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
bin_conv_0_mux_32mb6_U307(
    .din0(2'd2),
    .din1(2'd1),
    .din2(2'd1),
    .din3(tmp_1045_reg_992),
    .dout(tmp_12_fu_707_p5)
);

bin_conv_0_mux_32mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 2 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
bin_conv_0_mux_32mb6_U308(
    .din0(2'd2),
    .din1(2'd1),
    .din2(2'd2),
    .din3(tmp_1045_reg_992),
    .dout(tmp_13_fu_719_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state10) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state10))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state10);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_788)) begin
            if ((1'b0 == ap_block_pp2_stage0_11001)) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b0;
            end else if (((1'b0 == ap_block_pp2_stage0_01001) & (1'b1 == Output_1_V_V_ap_ack))) begin
                ap_reg_ioackin_Output_1_V_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bin_conv_fu_385_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_bin_conv_fu_385_ap_start_reg <= 1'b1;
        end else if ((grp_bin_conv_fu_385_ap_ready == 1'b1)) begin
            grp_bin_conv_fu_385_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
        dmem_i_reg_341 <= 2'd0;
    end else if (((exitcond_flatten1_fu_757_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_i_reg_341 <= dmem_i_mid2_fu_839_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
        dmem_j5_reg_363 <= 2'd0;
    end else if (((exitcond_flatten1_fu_757_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_j5_reg_363 <= dmem_j5_mid2_fu_891_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_451_p2 == 1'd1))) begin
        dmem_j_reg_285 <= 2'd0;
    end else if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_j_reg_285 <= dmem_j_t_mid2_v_fu_488_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
        dmem_k6_reg_374 <= 11'd0;
    end else if (((exitcond_flatten1_fu_757_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_k6_reg_374 <= dmem_k_2_fu_907_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_451_p2 == 1'd1))) begin
        dmem_k_reg_296 <= 11'd0;
    end else if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_k_reg_296 <= dmem_k_1_fu_506_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
        indvar_flatten1_reg_330 <= 13'd0;
    end else if (((exitcond_flatten1_fu_757_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        indvar_flatten1_reg_330 <= indvar_flatten_next1_fu_763_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
        indvar_flatten6_reg_352 <= 13'd0;
    end else if (((exitcond_flatten1_fu_757_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        indvar_flatten6_reg_352 <= indvar_flatten_next7_fu_919_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_451_p2 == 1'd1))) begin
        indvar_flatten_reg_274 <= 12'd0;
    end else if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten_reg_274 <= indvar_flatten_next_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld)) & (tmp_s_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kh_i_reg_263 <= kh_i_1_fu_440_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        kh_i_reg_263 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_385_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        p_2_reg_319 <= i_V_reg_1058;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_2_reg_319 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_bin_conv_fu_385_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        t_V_reg_307 <= kh_index_V_reg_1043;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t_V_reg_307 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        bin_conv_cnt <= p_s_fu_971_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bin_conv_cnt_load_reg_985 <= bin_conv_cnt;
        n_outputs_V_reg_1001 <= n_outputs_V_fu_422_p5;
        tmp_1045_reg_992 <= tmp_1045_fu_418_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_757_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_i_t_mid2_reg_1111 <= dmem_i_t_mid2_fu_793_p3;
        not_exitcond_flatten_reg_1116 <= not_exitcond_flatten_fu_815_p2;
        sel_tmp3_mid1_reg_1131 <= sel_tmp3_mid1_fu_871_p2;
        sel_tmp4_mid2_reg_1136 <= sel_tmp4_mid2_fu_883_p3;
        tmp_13_mid_reg_1121 <= tmp_13_mid_fu_833_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        exitcond_flatten1_reg_1102 <= exitcond_flatten1_fu_757_p2;
        sel_tmp3_reg_1097 <= sel_tmp3_fu_745_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        i_V_reg_1058 <= i_V_fu_544_p2;
        this_assign_1_reg_1053 <= this_assign_1_fu_538_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kh_index_V_reg_1043 <= kh_index_V_fu_517_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        nc_V_reg_1067 <= nc_V_fu_663_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_12_reg_1087 <= tmp_12_fu_707_p5;
        tmp_13_reg_1092 <= tmp_13_fu_719_p5;
        tmp_3_reg_1072 <= tmp_3_fu_671_p5;
        tmp_7_reg_1077 <= tmp_7_fu_683_p5;
        tmp_9_reg_1082 <= tmp_9_fu_695_p5;
    end
end

always @ (*) begin
    if ((~((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld)) & (tmp_s_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        Input_1_V_V_ap_ack = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        Input_1_V_V_ap_ack = grp_bin_conv_fu_385_Input_1_V_V_ap_ack;
    end else begin
        Input_1_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        Input_1_V_V_blk_n = Input_1_V_V_ap_vld;
    end else begin
        Input_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        Input_2_V_V_ap_ack = 1'b1;
    end else begin
        Input_2_V_V_ap_ack = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        Input_2_V_V_blk_n = Input_2_V_V_ap_vld;
    end else begin
        Input_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_1102 == 1'd0) & (1'b0 == ap_block_pp2_stage0_01001) & (ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        Output_1_V_V_ap_vld = 1'b1;
    end else begin
        Output_1_V_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten1_reg_1102 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        Output_1_V_V_blk_n = Output_1_V_V_ap_ack;
    end else begin
        Output_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond_flatten1_fu_757_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state10 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state10 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_Output_1_V_V_ap_ack == 1'b0)) begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = Output_1_V_V_ap_ack;
    end else begin
        ap_sig_ioackin_Output_1_V_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_0_address0 = tmp_15_fu_899_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dmem_V_0_0_address0 = tmp_8_fu_500_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_0_address0 = grp_bin_conv_fu_385_dmem_0_0_V_address0;
    end else begin
        dmem_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        dmem_V_0_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_0_ce0 = grp_bin_conv_fu_385_dmem_0_0_V_ce0;
    end else begin
        dmem_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dmem_V_0_0_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_0_d0 = grp_bin_conv_fu_385_dmem_0_0_V_d0;
    end else begin
        dmem_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (tmp_1046_fu_496_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        dmem_V_0_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_0_we0 = grp_bin_conv_fu_385_dmem_0_0_V_we0;
    end else begin
        dmem_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_0_1_address0 = tmp_15_fu_899_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dmem_V_0_1_address0 = tmp_8_fu_500_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_1_address0 = grp_bin_conv_fu_385_dmem_0_1_V_address0;
    end else begin
        dmem_V_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        dmem_V_0_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_1_ce0 = grp_bin_conv_fu_385_dmem_0_1_V_ce0;
    end else begin
        dmem_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dmem_V_0_1_d0 = Input_2_V_V;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_1_d0 = grp_bin_conv_fu_385_dmem_0_1_V_d0;
    end else begin
        dmem_V_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (tmp_1046_fu_496_p1 == 1'd1))) begin
        dmem_V_0_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_0_1_we0 = grp_bin_conv_fu_385_dmem_0_1_V_we0;
    end else begin
        dmem_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_0_address0 = tmp_15_fu_899_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_1_0_address0 = grp_bin_conv_fu_385_dmem_1_0_V_address0;
    end else begin
        dmem_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_V_1_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_1_0_ce0 = grp_bin_conv_fu_385_dmem_1_0_V_ce0;
    end else begin
        dmem_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_1_0_we0 = grp_bin_conv_fu_385_dmem_1_0_V_we0;
    end else begin
        dmem_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dmem_V_1_1_address0 = tmp_15_fu_899_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_1_1_address0 = grp_bin_conv_fu_385_dmem_1_1_V_address0;
    end else begin
        dmem_V_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        dmem_V_1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_1_1_ce0 = grp_bin_conv_fu_385_dmem_1_1_V_ce0;
    end else begin
        dmem_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        dmem_V_1_1_we0 = grp_bin_conv_fu_385_dmem_1_1_V_we0;
    end else begin
        dmem_V_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kh_mem_V_address0 = tmp_i_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        kh_mem_V_address0 = tmp_2_fu_446_p1;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (~((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld)) & (1'b1 == ap_CS_fsm_state2)))) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld)) & (tmp_s_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kh_mem_V_we0 = 1'b1;
    end else begin
        kh_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld)) & (tmp_s_fu_434_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld)) & (tmp_s_fu_434_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (tmp_1_fu_451_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld)) & (exitcond_flatten_fu_456_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (tmp_6_fu_550_p2 == 1'd1) & (exitcond_fu_512_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((tmp_6_fu_550_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (exitcond_fu_512_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_bin_conv_fu_385_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (exitcond_flatten1_fu_757_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (exitcond_flatten1_fu_757_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_1_V_V = ((dmem_i_t_mid2_reg_1111[0:0] === 1'b1) ? newSel3_fu_937_p3 : newSel4_fu_944_p3);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((1'b1 == ap_block_state11_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((1'b1 == ap_block_state11_io) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_state10_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_io = ((exitcond_flatten1_reg_1102 == 1'd0) & (ap_sig_ioackin_Output_1_V_V_ap_ack == 1'b0));
end

assign ap_block_state11_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2 = ((tmp_s_fu_434_p2 == 1'd0) & (1'b0 == Input_1_V_V_ap_vld));
end

always @ (*) begin
    ap_block_state4 = ((exitcond_flatten_fu_456_p2 == 1'd0) & (1'b0 == Input_2_V_V_ap_vld));
end

always @ (*) begin
    ap_condition_788 = ((exitcond_flatten1_reg_1102 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0));
end

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign dmem_i_mid2_fu_839_p3 = ((exitcond_flatten2_fu_769_p2[0:0] === 1'b1) ? dmem_i_s_fu_783_p2 : dmem_i_reg_341);

assign dmem_i_s_fu_783_p2 = (2'd1 + dmem_i_reg_341);

assign dmem_i_t_mid2_fu_793_p3 = ((exitcond_flatten2_fu_769_p2[0:0] === 1'b1) ? tmp_1051_fu_789_p1 : tmp_1049_fu_731_p1);

assign dmem_j5_mid2_fu_891_p3 = ((tmp_13_mid_fu_833_p2[0:0] === 1'b1) ? dmem_j_1_fu_847_p2 : dmem_j5_mid_fu_775_p3);

assign dmem_j5_mid_fu_775_p3 = ((exitcond_flatten2_fu_769_p2[0:0] === 1'b1) ? 2'd0 : dmem_j5_reg_363);

assign dmem_j_1_fu_847_p2 = (2'd1 + dmem_j5_mid_fu_775_p3);

assign dmem_j_s_fu_482_p2 = (2'd1 + dmem_j_reg_285);

assign dmem_j_t_mid2_v_fu_488_p3 = ((tmp_5_fu_468_p2[0:0] === 1'b1) ? dmem_j_s_fu_482_p2 : dmem_j_reg_285);

assign dmem_k6_mid2_fu_859_p3 = ((tmp_17_fu_853_p2[0:0] === 1'b1) ? 11'd0 : dmem_k6_reg_374);

assign dmem_k_1_fu_506_p2 = (dmem_k_mid2_fu_474_p3 + 11'd1);

assign dmem_k_2_fu_907_p2 = (11'd1 + dmem_k6_mid2_fu_859_p3);

assign dmem_k_mid2_fu_474_p3 = ((tmp_5_fu_468_p2[0:0] === 1'b1) ? 11'd0 : dmem_k_reg_296);

assign exitcond_flatten1_fu_757_p2 = ((indvar_flatten1_reg_330 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_769_p2 = ((indvar_flatten6_reg_352 == 13'd2048) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_456_p2 = ((indvar_flatten_reg_274 == 12'd2048) ? 1'b1 : 1'b0);

assign exitcond_fu_512_p2 = ((t_V_reg_307 == n_outputs_V_reg_1001) ? 1'b1 : 1'b0);

assign grp_bin_conv_fu_385_ap_start = grp_bin_conv_fu_385_ap_start_reg;

assign i_V_fu_544_p2 = (10'd1 + p_2_reg_319);

assign indvar_flatten6_op_fu_913_p2 = (13'd1 + indvar_flatten6_reg_352);

assign indvar_flatten_next1_fu_763_p2 = (13'd1 + indvar_flatten1_reg_330);

assign indvar_flatten_next7_fu_919_p3 = ((exitcond_flatten2_fu_769_p2[0:0] === 1'b1) ? 13'd1 : indvar_flatten6_op_fu_913_p2);

assign indvar_flatten_next_fu_462_p2 = (indvar_flatten_reg_274 + 12'd1);

assign kh_i_1_fu_440_p2 = (kh_i_reg_263 + 7'd1);

assign kh_index_V_fu_517_p2 = (t_V_reg_307 + 16'd1);

assign loc_V_1_fu_575_p4 = {{kh_mem_V_q0[31:16]}};

assign loc_V_2_fu_591_p4 = {{kh_mem_V_q0[47:32]}};

assign loc_V_3_fu_601_p4 = {{kh_mem_V_q0[63:48]}};

assign loc_V_fu_565_p1 = kh_mem_V_q0[15:0];

assign n_outputs_V_fu_422_p4 = bin_conv_cnt[1:0];

assign nc_V_fu_663_p3 = ((or_cond_fu_649_p2[0:0] === 1'b1) ? newSel_fu_641_p3 : newSel1_fu_655_p3);

assign newSel1_fu_655_p3 = ((tmp_3_i_fu_559_p2[0:0] === 1'b1) ? loc_V_fu_565_p1 : loc_V_3_fu_601_p4);

assign newSel3_fu_937_p3 = ((sel_tmp4_mid2_reg_1136[0:0] === 1'b1) ? dmem_V_1_1_q0 : dmem_V_1_0_q0);

assign newSel4_fu_944_p3 = ((sel_tmp3_mid2_fu_931_p3[0:0] === 1'b1) ? dmem_V_0_1_q0 : dmem_V_0_0_q0);

assign newSel_fu_641_p3 = ((sel_tmp7_fu_635_p2[0:0] === 1'b1) ? loc_V_2_fu_591_p4 : loc_V_1_fu_575_p4);

assign not_exitcond_flatten_fu_815_p2 = (exitcond_flatten2_fu_769_p2 ^ 1'd1);

assign off_V_fu_555_p1 = t_V_reg_307[1:0];

assign or_cond_fu_649_p2 = (sel_tmp7_fu_635_p2 | sel_tmp2_fu_617_p2);

assign p_s_fu_971_p3 = ((tmp_11_fu_965_p2[0:0] === 1'b1) ? 32'd0 : tmp_10_fu_960_p2);

assign r_V_fu_523_p4 = {{t_V_reg_307[15:2]}};

assign sel_tmp1_fu_611_p2 = (tmp_3_i_fu_559_p2 ^ 1'd1);

assign sel_tmp2_fu_617_p2 = (tmp_4_i_fu_569_p2 & sel_tmp1_fu_611_p2);

assign sel_tmp3_fu_745_p2 = (tmp_1050_fu_741_p1 & sel_tmp_fu_735_p2);

assign sel_tmp3_mid1_fu_871_p2 = (tmp_1052_fu_867_p1 & sel_tmp_mid2_fu_807_p3);

assign sel_tmp3_mid2_fu_931_p3 = ((tmp_13_mid_reg_1121[0:0] === 1'b1) ? sel_tmp3_mid1_reg_1131 : sel_tmp3_mid_fu_927_p2);

assign sel_tmp3_mid_fu_927_p2 = (sel_tmp3_reg_1097 & not_exitcond_flatten_reg_1116);

assign sel_tmp4_fu_751_p2 = (tmp_1050_fu_741_p1 & tmp_1049_fu_731_p1);

assign sel_tmp4_mid1_fu_877_p2 = (tmp_1052_fu_867_p1 & dmem_i_t_mid2_fu_793_p3);

assign sel_tmp4_mid2_fu_883_p3 = ((tmp_13_mid_fu_833_p2[0:0] === 1'b1) ? sel_tmp4_mid1_fu_877_p2 : sel_tmp4_mid_fu_821_p2);

assign sel_tmp4_mid_fu_821_p2 = (sel_tmp4_fu_751_p2 & not_exitcond_flatten_fu_815_p2);

assign sel_tmp6_demorgan_fu_623_p2 = (tmp_4_i_fu_569_p2 | tmp_3_i_fu_559_p2);

assign sel_tmp6_fu_629_p2 = (sel_tmp6_demorgan_fu_623_p2 ^ 1'd1);

assign sel_tmp7_fu_635_p2 = (tmp_5_i_fu_585_p2 & sel_tmp6_fu_629_p2);

assign sel_tmp_fu_735_p2 = (tmp_1049_fu_731_p1 ^ 1'd1);

assign sel_tmp_mid1_fu_801_p2 = (tmp_1051_fu_789_p1 ^ 1'd1);

assign sel_tmp_mid2_fu_807_p3 = ((exitcond_flatten2_fu_769_p2[0:0] === 1'b1) ? sel_tmp_mid1_fu_801_p2 : sel_tmp_fu_735_p2);

assign this_assign_1_fu_538_p2 = ((p_2_reg_319 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_1045_fu_418_p1 = bin_conv_cnt[1:0];

assign tmp_1046_fu_496_p1 = dmem_j_t_mid2_v_fu_488_p3[0:0];

assign tmp_1049_fu_731_p1 = dmem_i_reg_341[0:0];

assign tmp_1050_fu_741_p1 = dmem_j5_reg_363[0:0];

assign tmp_1051_fu_789_p1 = dmem_i_s_fu_783_p2[0:0];

assign tmp_1052_fu_867_p1 = dmem_j_1_fu_847_p2[0:0];

assign tmp_10_fu_960_p2 = (bin_conv_cnt_load_reg_985 + 32'd1);

assign tmp_11_fu_965_p2 = ((tmp_10_fu_960_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_13_mid_fu_833_p2 = (tmp_16_fu_827_p2 & not_exitcond_flatten_fu_815_p2);

assign tmp_15_fu_899_p1 = dmem_k6_mid2_fu_859_p3;

assign tmp_16_fu_827_p2 = ((dmem_k6_reg_374 == 11'd1024) ? 1'b1 : 1'b0);

assign tmp_17_fu_853_p2 = (tmp_13_mid_fu_833_p2 | exitcond_flatten2_fu_769_p2);

assign tmp_1_fu_451_p2 = ((bin_conv_cnt_load_reg_985 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_2_fu_446_p1 = kh_i_reg_263;

assign tmp_3_i_fu_559_p2 = ((off_V_fu_555_p1 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_4_i_fu_569_p2 = ((off_V_fu_555_p1 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_5_fu_468_p2 = ((dmem_k_reg_296 == 11'd1024) ? 1'b1 : 1'b0);

assign tmp_5_i_fu_585_p2 = ((off_V_fu_555_p1 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_6_fu_550_p2 = ((bin_conv_cnt_load_reg_985 == 32'd2) ? 1'b1 : 1'b0);

assign tmp_8_fu_500_p1 = dmem_k_mid2_fu_474_p3;

assign tmp_i_fu_533_p1 = r_V_fu_523_p4;

assign tmp_s_fu_434_p2 = ((kh_i_reg_263 == 7'd64) ? 1'b1 : 1'b0);

endmodule //bin_conv_0
