// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bin_dense (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wt_mem_0_V_address0,
        wt_mem_0_V_ce0,
        wt_mem_0_V_q0,
        wt_mem_1_V_address0,
        wt_mem_1_V_ce0,
        wt_mem_1_V_q0,
        kh_mem_V_address0,
        kh_mem_V_ce0,
        kh_mem_V_q0,
        dmem_0_0_V_address0,
        dmem_0_0_V_ce0,
        dmem_0_0_V_we0,
        dmem_0_0_V_d0,
        dmem_0_0_V_q0,
        dmem_0_1_V_address0,
        dmem_0_1_V_ce0,
        dmem_0_1_V_we0,
        dmem_0_1_V_d0,
        dmem_0_1_V_q0,
        dmem_1_0_V_address0,
        dmem_1_0_V_ce0,
        dmem_1_0_V_we0,
        dmem_1_0_V_d0,
        dmem_1_0_V_q0,
        dmem_1_1_V_address0,
        dmem_1_1_V_ce0,
        dmem_1_1_V_we0,
        dmem_1_1_V_d0,
        dmem_1_1_V_q0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_pp0_stage0 = 10'd16;
parameter    ap_ST_fsm_state10 = 10'd32;
parameter    ap_ST_fsm_state11 = 10'd64;
parameter    ap_ST_fsm_state12 = 10'd128;
parameter    ap_ST_fsm_state13 = 10'd256;
parameter    ap_ST_fsm_state14 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] wt_mem_0_V_address0;
output   wt_mem_0_V_ce0;
input  [63:0] wt_mem_0_V_q0;
output  [11:0] wt_mem_1_V_address0;
output   wt_mem_1_V_ce0;
input  [63:0] wt_mem_1_V_q0;
output  [5:0] kh_mem_V_address0;
output   kh_mem_V_ce0;
input  [63:0] kh_mem_V_q0;
output  [5:0] dmem_0_0_V_address0;
output   dmem_0_0_V_ce0;
output   dmem_0_0_V_we0;
output  [63:0] dmem_0_0_V_d0;
input  [63:0] dmem_0_0_V_q0;
output  [5:0] dmem_0_1_V_address0;
output   dmem_0_1_V_ce0;
output   dmem_0_1_V_we0;
output  [63:0] dmem_0_1_V_d0;
input  [63:0] dmem_0_1_V_q0;
output  [5:0] dmem_1_0_V_address0;
output   dmem_1_0_V_ce0;
output   dmem_1_0_V_we0;
output  [63:0] dmem_1_0_V_d0;
input  [63:0] dmem_1_0_V_q0;
output  [5:0] dmem_1_1_V_address0;
output   dmem_1_1_V_ce0;
output   dmem_1_1_V_we0;
output  [63:0] dmem_1_1_V_d0;
input  [63:0] dmem_1_1_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg wt_mem_0_V_ce0;
reg wt_mem_1_V_ce0;
reg[5:0] kh_mem_V_address0;
reg kh_mem_V_ce0;
reg[5:0] dmem_0_0_V_address0;
reg dmem_0_0_V_ce0;
reg dmem_0_0_V_we0;
reg[63:0] dmem_0_0_V_d0;
reg[5:0] dmem_0_1_V_address0;
reg dmem_0_1_V_ce0;
reg dmem_0_1_V_we0;
reg[5:0] dmem_1_0_V_address0;
reg dmem_1_0_V_ce0;
reg dmem_1_0_V_we0;
reg[63:0] dmem_1_0_V_d0;
reg[5:0] dmem_1_1_V_address0;
reg dmem_1_1_V_ce0;
reg dmem_1_1_V_we0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] ctrl_i;
wire   [5:0] tmp1_list_address0;
reg    tmp1_list_ce0;
wire   [29:0] tmp1_list_q0;
wire   [5:0] tmp2_list_address0;
reg    tmp2_list_ce0;
wire   [29:0] tmp2_list_q0;
reg   [15:0] p_Val2_2_reg_493;
reg   [15:0] p_2_reg_505;
wire   [1:0] layer_type_V_fu_552_p4;
reg   [1:0] layer_type_V_reg_3770;
wire    ap_CS_fsm_state2;
reg   [0:0] d_i_idx_V_reg_3775;
wire   [0:0] d_o_idx_V_fu_570_p3;
reg   [0:0] d_o_idx_V_reg_3781;
wire   [15:0] p_Result_1_fu_598_p1;
reg   [15:0] p_Result_1_reg_3787;
wire   [15:0] tmp_25_fu_602_p1;
reg   [15:0] tmp_25_reg_3792;
wire   [16:0] lhs_V_fu_606_p1;
reg   [16:0] lhs_V_reg_3797;
reg   [5:0] tmp_13_reg_3802;
wire   [21:0] rhs_V_1_cast_fu_620_p1;
reg   [21:0] rhs_V_1_cast_reg_3807;
wire   [0:0] tmp_14_fu_624_p2;
reg   [0:0] tmp_14_reg_3812;
wire   [0:0] sel_tmp_fu_630_p2;
reg   [0:0] sel_tmp_reg_3820;
wire   [15:0] o_V_fu_641_p2;
reg   [15:0] o_V_reg_3828;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_29_reg_3833;
wire   [0:0] exitcond_fu_636_p2;
reg   [5:0] dmem_0_0_V_addr_reg_3840;
reg   [5:0] dmem_0_1_V_addr_reg_3845;
reg   [5:0] dmem_1_0_V_addr_reg_3850;
reg   [5:0] dmem_1_1_V_addr_reg_3855;
wire   [5:0] o_offset_V_fu_701_p2;
reg   [5:0] o_offset_V_reg_3863;
wire    ap_CS_fsm_state4;
wire   [63:0] o_word_V_4_fu_740_p3;
reg   [63:0] o_word_V_4_reg_3868;
wire   [21:0] r_V_2_fu_3749_p2;
reg   [21:0] r_V_2_reg_3875;
wire   [0:0] tmp_18_fu_752_p2;
reg   [0:0] tmp_18_reg_3880;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_18_reg_3880_pp0_iter1_reg;
reg   [0:0] tmp_18_reg_3880_pp0_iter2_reg;
reg   [0:0] tmp_18_reg_3880_pp0_iter3_reg;
wire   [15:0] i_V_fu_800_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [1:0] tmp_22_reg_3919;
reg   [1:0] tmp_23_reg_3924;
reg   [1:0] tmp_89_reg_3930;
reg   [1:0] tmp_90_reg_3936;
reg   [1:0] tmp_91_reg_3942;
reg   [1:0] tmp_92_reg_3948;
reg   [1:0] tmp_93_reg_3954;
reg   [1:0] tmp_94_reg_3960;
reg   [1:0] tmp_95_reg_3966;
reg   [1:0] tmp_96_reg_3972;
reg   [1:0] tmp_97_reg_3978;
reg   [1:0] tmp_98_reg_3984;
reg   [1:0] tmp_99_reg_3990;
reg   [1:0] tmp_100_reg_3996;
reg   [1:0] tmp_101_reg_4002;
wire   [1:0] tmp_137_fu_1365_p1;
reg   [1:0] tmp_137_reg_4008;
reg   [1:0] tmp_102_reg_4015;
reg   [1:0] tmp_103_reg_4020;
reg   [1:0] tmp_105_reg_4026;
reg   [1:0] tmp_106_reg_4032;
reg   [1:0] tmp_107_reg_4038;
reg   [1:0] tmp_108_reg_4044;
reg   [1:0] tmp_109_reg_4050;
reg   [1:0] tmp_110_reg_4056;
reg   [1:0] tmp_111_reg_4062;
reg   [1:0] tmp_112_reg_4068;
reg   [1:0] tmp_113_reg_4074;
reg   [1:0] tmp_114_reg_4080;
reg   [1:0] tmp_115_reg_4086;
reg   [1:0] tmp_116_reg_4092;
reg   [1:0] tmp_117_reg_4098;
reg   [1:0] tmp_118_reg_4104;
reg   [1:0] tmp_132_reg_4111;
reg   [1:0] tmp_133_reg_4116;
reg   [1:0] tmp_166_reg_4122;
reg   [1:0] tmp_167_reg_4128;
reg   [1:0] tmp_168_reg_4134;
reg   [1:0] tmp_169_reg_4140;
reg   [1:0] tmp_170_reg_4146;
reg   [1:0] tmp_171_reg_4152;
reg   [1:0] tmp_172_reg_4158;
reg   [1:0] tmp_173_reg_4164;
reg   [1:0] tmp_174_reg_4170;
reg   [1:0] tmp_175_reg_4176;
reg   [1:0] tmp_176_reg_4182;
reg   [1:0] tmp_177_reg_4188;
reg   [1:0] tmp_178_reg_4194;
wire   [1:0] tmp_217_fu_2088_p1;
reg   [1:0] tmp_217_reg_4200;
reg   [1:0] tmp_179_reg_4207;
reg   [1:0] tmp_180_reg_4212;
reg   [1:0] tmp_182_reg_4218;
reg   [1:0] tmp_183_reg_4224;
reg   [1:0] tmp_184_reg_4230;
reg   [1:0] tmp_185_reg_4236;
reg   [1:0] tmp_186_reg_4242;
reg   [1:0] tmp_187_reg_4248;
reg   [1:0] tmp_188_reg_4254;
reg   [1:0] tmp_189_reg_4260;
reg   [1:0] tmp_190_reg_4266;
reg   [1:0] tmp_191_reg_4272;
reg   [1:0] tmp_192_reg_4278;
reg   [1:0] tmp_193_reg_4284;
reg   [1:0] tmp_194_reg_4290;
reg   [1:0] tmp_195_reg_4296;
reg   [3:0] tmp_121_reg_4303;
reg   [3:0] tmp_122_reg_4309;
reg   [3:0] tmp_123_reg_4316;
reg   [3:0] tmp_124_reg_4324;
reg   [3:0] tmp_125_reg_4332;
reg   [3:0] tmp_126_reg_4340;
reg   [3:0] tmp_127_reg_4348;
reg   [3:0] tmp_127_reg_4348_pp0_iter3_reg;
wire   [3:0] tmp_138_fu_2582_p1;
reg   [3:0] tmp_138_reg_4357;
wire   [3:0] tmp_31_fu_2592_p2;
reg   [3:0] tmp_31_reg_4363;
reg   [3:0] tmp_31_reg_4363_pp0_iter3_reg;
reg   [3:0] tmp_198_reg_4368;
reg   [3:0] tmp_199_reg_4374;
reg   [3:0] tmp_200_reg_4381;
reg   [3:0] tmp_201_reg_4389;
reg   [3:0] tmp_202_reg_4397;
reg   [3:0] tmp_203_reg_4405;
reg   [3:0] tmp_204_reg_4413;
reg   [3:0] tmp_204_reg_4413_pp0_iter3_reg;
wire   [3:0] tmp_218_fu_2928_p1;
reg   [3:0] tmp_218_reg_4422;
wire   [3:0] tmp_46_fu_2938_p2;
reg   [3:0] tmp_46_reg_4428;
reg   [3:0] tmp_46_reg_4428_pp0_iter3_reg;
wire   [6:0] tmp_35_fu_3107_p2;
reg   [6:0] tmp_35_reg_4433;
wire   [6:0] tmp_63_fu_3276_p2;
reg   [6:0] tmp_63_reg_4438;
wire   [15:0] sum_V_1_fu_3378_p2;
reg    ap_enable_reg_pp0_iter4;
wire    ap_CS_fsm_state10;
wire   [0:0] kh_off_V_1_fu_3399_p1;
reg   [0:0] kh_off_V_1_reg_4453;
wire    ap_CS_fsm_state11;
reg   [63:0] kh_word_V_2_reg_4458;
wire   [15:0] ki_V_2_fu_3417_p3;
reg  signed [15:0] ki_V_2_reg_4464;
wire    ap_CS_fsm_state12;
wire  signed [35:0] p_Val2_5_fu_3754_p2;
reg  signed [35:0] p_Val2_5_reg_4474;
wire   [15:0] best_out_V_2_fu_3713_p3;
reg   [15:0] best_out_V_2_reg_4479;
wire    ap_CS_fsm_state13;
wire   [63:0] o_word_V_3_fu_3727_p3;
reg   [63:0] o_word_V_3_reg_4484;
wire   [7:0] prediction_V_2_fu_3741_p3;
reg   [7:0] prediction_V_2_reg_4492;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [15:0] p_Val2_9_reg_457;
wire    ap_CS_fsm_state14;
reg   [7:0] p_Val2_11_reg_469;
reg   [15:0] p_1_reg_481;
wire  signed [63:0] tmp_fu_520_p1;
wire   [63:0] tmp_17_fu_666_p1;
wire   [0:0] tmp_15_fu_682_p2;
wire   [63:0] tmp_20_fu_776_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_21_fu_794_p1;
wire   [63:0] tmp_27_fu_3394_p1;
wire   [63:0] tmp_24_fu_3435_p1;
wire   [7:0] p_s_fu_538_p3;
wire   [63:0] p_Result_2_fu_687_p3;
wire  signed [7:0] tmp_fu_520_p0;
wire  signed [7:0] tmp_s_fu_526_p1;
wire   [7:0] tmp_s_fu_526_p2;
wire   [0:0] tmp_12_fu_532_p2;
wire   [13:0] tmp_1_fu_588_p4;
wire   [11:0] p_Result_s_fu_578_p4;
wire   [16:0] rhs_V_fu_647_p1;
wire   [16:0] r_V_fu_651_p2;
wire   [9:0] tmp_16_fu_656_p4;
wire   [5:0] tmp_28_fu_697_p1;
wire   [0:0] sel_tmp1_fu_706_p2;
wire   [0:0] sel_tmp3_fu_718_p2;
wire   [0:0] sel_tmp4_fu_723_p2;
wire   [63:0] sel_tmp2_fu_710_p3;
wire   [0:0] sel_tmp6_fu_736_p2;
wire   [63:0] sel_tmp5_fu_728_p3;
wire   [21:0] rhs_V_2_cast_fu_757_p1;
wire   [8:0] r_V_5_fu_766_p4;
(* use_dsp48 = "no" *) wire   [21:0] r_V_1_fu_761_p2;
wire   [14:0] p_0839_s_fu_784_p4;
wire   [63:0] in_wrd_V_0_phi_fu_806_p3;
wire   [63:0] r_V_s_fu_813_p2;
wire   [0:0] tmp_32_fu_819_p3;
wire   [0:0] tmp_38_fu_827_p3;
wire   [0:0] tmp_51_fu_835_p3;
wire   [0:0] tmp_56_fu_843_p3;
wire   [0:0] tmp_61_fu_851_p3;
wire   [0:0] tmp_67_fu_859_p3;
wire   [0:0] tmp_68_fu_867_p3;
wire   [0:0] tmp_69_fu_875_p3;
wire   [0:0] tmp_70_fu_883_p3;
wire   [0:0] tmp_71_fu_891_p3;
wire   [0:0] tmp_72_fu_899_p3;
wire   [0:0] tmp_73_fu_907_p3;
wire   [0:0] tmp_74_fu_915_p3;
wire   [0:0] tmp_75_fu_923_p3;
wire   [0:0] tmp_76_fu_931_p3;
wire   [0:0] tmp_77_fu_939_p3;
wire   [0:0] tmp_78_fu_947_p3;
wire   [0:0] tmp_79_fu_955_p3;
wire   [0:0] tmp_80_fu_963_p3;
wire   [0:0] tmp_81_fu_971_p3;
wire   [0:0] tmp_82_fu_979_p3;
wire   [0:0] tmp_83_fu_987_p3;
wire   [0:0] tmp_84_fu_995_p3;
wire   [0:0] tmp_85_fu_1003_p3;
wire   [0:0] tmp_86_fu_1011_p3;
wire   [0:0] tmp_87_fu_1019_p3;
wire   [0:0] tmp_88_fu_1027_p3;
wire   [0:0] tmp_104_fu_1035_p3;
wire   [0:0] tmp_130_fu_1043_p3;
wire   [0:0] tmp_134_fu_1051_p3;
wire   [0:0] tmp_135_fu_1059_p3;
wire   [0:0] tmp_136_fu_1067_p3;
wire   [62:0] r_V_6_fu_1075_p64;
wire   [63:0] r_V_6_cast_fu_1205_p1;
wire   [63:0] x_V_6_fu_1209_p2;
wire   [63:0] in_wrd_V_1_phi_fu_1529_p3;
wire   [63:0] r_V_15_1_fu_1536_p2;
wire   [0:0] tmp_139_fu_1542_p3;
wire   [0:0] tmp_140_fu_1550_p3;
wire   [0:0] tmp_141_fu_1558_p3;
wire   [0:0] tmp_142_fu_1566_p3;
wire   [0:0] tmp_143_fu_1574_p3;
wire   [0:0] tmp_144_fu_1582_p3;
wire   [0:0] tmp_145_fu_1590_p3;
wire   [0:0] tmp_146_fu_1598_p3;
wire   [0:0] tmp_147_fu_1606_p3;
wire   [0:0] tmp_148_fu_1614_p3;
wire   [0:0] tmp_149_fu_1622_p3;
wire   [0:0] tmp_150_fu_1630_p3;
wire   [0:0] tmp_151_fu_1638_p3;
wire   [0:0] tmp_152_fu_1646_p3;
wire   [0:0] tmp_153_fu_1654_p3;
wire   [0:0] tmp_154_fu_1662_p3;
wire   [0:0] tmp_155_fu_1670_p3;
wire   [0:0] tmp_156_fu_1678_p3;
wire   [0:0] tmp_157_fu_1686_p3;
wire   [0:0] tmp_158_fu_1694_p3;
wire   [0:0] tmp_159_fu_1702_p3;
wire   [0:0] tmp_160_fu_1710_p3;
wire   [0:0] tmp_161_fu_1718_p3;
wire   [0:0] tmp_162_fu_1726_p3;
wire   [0:0] tmp_163_fu_1734_p3;
wire   [0:0] tmp_164_fu_1742_p3;
wire   [0:0] tmp_165_fu_1750_p3;
wire   [0:0] tmp_181_fu_1758_p3;
wire   [0:0] tmp_207_fu_1766_p3;
wire   [0:0] tmp_211_fu_1774_p3;
wire   [0:0] tmp_215_fu_1782_p3;
wire   [0:0] tmp_216_fu_1790_p3;
wire   [62:0] r_V_10_1_fu_1798_p64;
wire   [63:0] r_V_10_1_cast_fu_1928_p1;
wire   [63:0] x_V_6_1_fu_1932_p2;
wire   [61:0] r_V_7_fu_2252_p32;
wire   [61:0] r_V_8_fu_2306_p32;
wire   [62:0] r_V_7_cast_fu_2302_p1;
wire   [62:0] r_V_8_cast_fu_2356_p1;
wire   [62:0] x_V_fu_2464_p2;
wire   [58:0] tmp_120_fu_2476_p4;
wire   [59:0] tmp_3_fu_2409_p31;
wire   [59:0] tmp_2_fu_2360_p31;
wire   [59:0] tmp_5_fu_2490_p2;
wire   [59:0] tmp_4_fu_2486_p1;
wire   [61:0] tmp_119_fu_2458_p2;
wire   [59:0] tmp_44_cast_fu_2496_p2;
wire   [3:0] tmp_30_fu_2502_p4;
wire   [3:0] tmp_32_cast_fu_2470_p1;
wire   [3:0] tmp_33_cast_fu_2473_p1;
wire   [3:0] tmp6_fu_2586_p2;
wire   [61:0] r_V_11_1_fu_2598_p32;
wire   [61:0] r_V_12_1_fu_2652_p32;
wire   [62:0] r_V_11_1_cast_fu_2648_p1;
wire   [62:0] r_V_12_1_cast_fu_2702_p1;
wire   [62:0] x_V_1_fu_2810_p2;
wire   [58:0] tmp_197_fu_2822_p4;
wire   [59:0] tmp_42_fu_2755_p31;
wire   [59:0] tmp_41_fu_2706_p31;
wire   [59:0] tmp_44_fu_2836_p2;
wire   [59:0] tmp_43_fu_2832_p1;
wire   [61:0] tmp_196_fu_2804_p2;
wire   [59:0] tmp_44_1_cast_fu_2842_p2;
wire   [3:0] tmp_45_fu_2848_p4;
wire   [3:0] tmp_65_cast_fu_2816_p1;
wire   [3:0] tmp_66_cast_fu_2819_p1;
wire   [3:0] tmp44_fu_2932_p2;
wire   [59:0] x_V_2_fu_2944_p16;
wire   [51:0] r_V_9_fu_2974_p14;
wire   [59:0] tmp_128_fu_2997_p1;
wire   [60:0] x_V_2_cast_fu_2970_p1;
wire   [60:0] r_V_9_cast_fu_3001_p1;
wire   [46:0] tmp_8_fu_3027_p13;
wire   [46:0] tmp_7_fu_3005_p13;
wire   [60:0] x_V_3_fu_3055_p2;
wire   [44:0] tmp_131_fu_3067_p4;
wire   [46:0] x_V_3_cast_fu_3061_p2;
wire   [46:0] r_V_10_cast_fu_3077_p1;
wire   [46:0] x_V_4_fu_3081_p2;
wire   [59:0] tmp_129_fu_3049_p2;
wire   [6:0] tmp_34_fu_3097_p4;
wire   [6:0] tmp_33_fu_3087_p4;
wire   [59:0] x_V_2_1_fu_3113_p16;
wire   [51:0] r_V_13_1_fu_3143_p14;
wire   [59:0] tmp_205_fu_3166_p1;
wire   [60:0] x_V_2_1_cast_fu_3139_p1;
wire   [60:0] r_V_13_1_cast_fu_3170_p1;
wire   [46:0] tmp_48_fu_3196_p13;
wire   [46:0] tmp_47_fu_3174_p13;
wire   [60:0] x_V_3_1_fu_3224_p2;
wire   [44:0] tmp_208_fu_3236_p4;
wire   [46:0] x_V_3_1_cast_fu_3230_p2;
wire   [46:0] r_V_14_1_cast_fu_3246_p1;
wire   [46:0] x_V_4_1_fu_3250_p2;
wire   [59:0] tmp_206_fu_3218_p2;
wire   [6:0] tmp_60_fu_3266_p4;
wire   [6:0] tmp_59_fu_3256_p4;
wire   [6:0] tmp_10_fu_3285_p3;
wire   [6:0] tmp_9_fu_3282_p1;
wire   [6:0] tmp_36_fu_3292_p2;
wire   [6:0] tmp_37_fu_3298_p2;
wire   [7:0] tmp_39_fu_3303_p3;
wire   [8:0] phitmp_cast_fu_3311_p1;
wire   [8:0] tmp_40_fu_3315_p2;
wire   [6:0] tmp_58_fu_3328_p3;
wire   [6:0] tmp_54_fu_3325_p1;
wire   [6:0] tmp_65_fu_3335_p2;
wire   [6:0] tmp_4616_s_fu_3341_p2;
wire   [7:0] tmp_47_1_fu_3346_p3;
wire   [8:0] phitmp_1_cast_fu_3354_p1;
wire   [8:0] tmp_48_1_fu_3358_p2;
wire  signed [9:0] tmp_48_cast_fu_3321_p1;
wire  signed [9:0] tmp_48_1_cast_fu_3364_p1;
wire   [9:0] tmp_66_fu_3368_p2;
wire  signed [15:0] p_cast_fu_3374_p1;
wire   [14:0] r_V_4_fu_3384_p4;
wire   [15:0] loc_V_2_fu_3407_p4;
wire   [15:0] loc_V_1_fu_3403_p1;
wire   [13:0] r_V_3_fu_3425_p4;
wire   [9:0] tmp_223_fu_3440_p1;
wire  signed [19:0] tmp_52_fu_3444_p3;
wire   [1:0] kh_off_V_fu_3459_p1;
wire   [15:0] tmp_209_fu_3498_p4;
wire   [15:0] tmp_210_fu_3507_p4;
wire   [15:0] tmp_212_fu_3516_p3;
wire   [27:0] tmp_55_fu_3523_p3;
wire  signed [36:0] tmp_55_cast_fu_3531_p1;
wire   [36:0] tmp_53_fu_3495_p1;
wire   [36:0] p_Val2_7_fu_3535_p2;
wire   [19:0] p_Val2_8_fu_3541_p4;
wire  signed [21:0] tmp_60_cast_fu_3577_p1;
wire   [21:0] tmp_62_fu_3581_p3;
wire   [0:0] tmp_26_fu_3463_p2;
wire   [0:0] tmp_49_fu_3473_p2;
wire   [0:0] sel_tmp7_fu_3595_p2;
wire   [0:0] sel_tmp17_demorgan_fu_3607_p2;
wire   [0:0] tmp_50_fu_3489_p2;
wire   [0:0] sel_tmp9_fu_3613_p2;
wire   [0:0] sel_tmp10_fu_3619_p2;
wire   [15:0] loc_V_4_fu_3557_p4;
wire   [15:0] loc_V_3_fu_3479_p4;
wire   [0:0] sel_tmp8_fu_3601_p2;
wire   [15:0] loc_V_fu_3469_p1;
wire   [15:0] loc_V_5_fu_3567_p4;
wire   [0:0] or_cond_fu_3633_p2;
wire   [15:0] newSel_fu_3625_p3;
wire   [15:0] newSel1_fu_3639_p3;
wire   [15:0] nc_V_4_fu_3647_p3;
wire   [0:0] not_s_fu_3658_p2;
wire   [31:0] bvh_d_index_fu_3655_p1;
wire   [63:0] p_Repl2_s_fu_3664_p1;
wire   [13:0] p_Val2_s_28_fu_3681_p4;
wire  signed [15:0] best_out_V_fu_3691_p1;
wire   [0:0] tmp_57_fu_3551_p2;
wire   [0:0] tmp_64_fu_3589_p2;
wire   [0:0] tmp47_fu_3702_p2;
wire   [0:0] sel_tmp25_demorgan_fu_3708_p2;
wire   [15:0] best_out_V_1_fu_3695_p3;
reg   [63:0] p_Result_s_27_fu_3668_p4;
wire   [63:0] o_word_V_2_fu_3721_p3;
wire   [7:0] prediction_V_fu_3677_p1;
wire   [7:0] prediction_V_1_fu_3734_p3;
wire   [13:0] r_V_2_fu_3749_p0;
wire   [15:0] r_V_2_fu_3749_p1;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [21:0] r_V_2_fu_3749_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ctrl_i = 8'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

bin_dense_tmp1_list #(
    .DataWidth( 30 ),
    .AddressRange( 37 ),
    .AddressWidth( 6 ))
tmp1_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp1_list_address0),
    .ce0(tmp1_list_ce0),
    .q0(tmp1_list_q0)
);

bin_dense_tmp2_list #(
    .DataWidth( 30 ),
    .AddressRange( 37 ),
    .AddressWidth( 6 ))
tmp2_list_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp2_list_address0),
    .ce0(tmp2_list_ce0),
    .q0(tmp2_list_q0)
);

bin_dense_wrapperbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 22 ))
bin_dense_wrapperbkb_U1(
    .din0(r_V_2_fu_3749_p0),
    .din1(r_V_2_fu_3749_p1),
    .dout(r_V_2_fu_3749_p2)
);

bin_dense_wrappercud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 36 ))
bin_dense_wrappercud_U2(
    .din0(tmp_52_fu_3444_p3),
    .din1(ki_V_2_reg_4464),
    .dout(p_Val2_5_fu_3754_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state5)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_1_reg_481 <= o_V_reg_3828;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_1_reg_481 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_18_fu_752_p2 == 1'd1))) begin
        p_2_reg_505 <= i_V_fu_800_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_2_reg_505 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_Val2_11_reg_469 <= prediction_V_2_reg_4492;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_11_reg_469 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_18_reg_3880_pp0_iter3_reg == 1'd1))) begin
        p_Val2_2_reg_493 <= sum_V_1_fu_3378_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_2_reg_493 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_Val2_9_reg_457 <= best_out_V_2_reg_4479;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_9_reg_457 <= 16'd49152;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        best_out_V_2_reg_4479 <= best_out_V_2_fu_3713_p3;
        o_word_V_3_reg_4484 <= o_word_V_3_fu_3727_p3;
        prediction_V_2_reg_4492 <= prediction_V_2_fu_3741_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ctrl_i <= p_s_fu_538_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_idx_V_reg_3775 <= tmp1_list_q0[32'd24];
        d_o_idx_V_reg_3781 <= tmp1_list_q0[32'd20];
        layer_type_V_reg_3770 <= {{tmp1_list_q0[29:28]}};
        lhs_V_reg_3797[11 : 0] <= lhs_V_fu_606_p1[11 : 0];
        p_Result_1_reg_3787[13 : 0] <= p_Result_1_fu_598_p1[13 : 0];
        rhs_V_1_cast_reg_3807[13 : 0] <= rhs_V_1_cast_fu_620_p1[13 : 0];
        sel_tmp_reg_3820 <= sel_tmp_fu_630_p2;
        tmp_13_reg_3802 <= {{tmp1_list_q0[13:8]}};
        tmp_14_reg_3812 <= tmp_14_fu_624_p2;
        tmp_25_reg_3792 <= tmp_25_fu_602_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd0))) begin
        dmem_0_0_V_addr_reg_3840 <= tmp_17_fu_666_p1;
        dmem_0_1_V_addr_reg_3845 <= tmp_17_fu_666_p1;
        dmem_1_0_V_addr_reg_3850 <= tmp_17_fu_666_p1;
        dmem_1_1_V_addr_reg_3855 <= tmp_17_fu_666_p1;
        tmp_29_reg_3833 <= r_V_fu_651_p2[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        kh_off_V_1_reg_4453 <= kh_off_V_1_fu_3399_p1;
        kh_word_V_2_reg_4458 <= kh_mem_V_q0;
        ki_V_2_reg_4464 <= ki_V_2_fu_3417_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        o_V_reg_3828 <= o_V_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_14_reg_3812 == 1'd1))) begin
        o_offset_V_reg_3863 <= o_offset_V_fu_701_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        o_word_V_4_reg_3868 <= o_word_V_4_fu_740_p3;
        r_V_2_reg_3875 <= r_V_2_fu_3749_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_Val2_5_reg_4474 <= p_Val2_5_fu_3754_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_18_reg_3880 == 1'd1))) begin
        tmp_100_reg_3996 <= {{x_V_6_fu_1209_p2[9:8]}};
        tmp_101_reg_4002 <= {{x_V_6_fu_1209_p2[5:4]}};
        tmp_102_reg_4015 <= {{x_V_6_fu_1209_p2[63:62]}};
        tmp_103_reg_4020 <= {{x_V_6_fu_1209_p2[59:58]}};
        tmp_105_reg_4026 <= {{x_V_6_fu_1209_p2[55:54]}};
        tmp_106_reg_4032 <= {{x_V_6_fu_1209_p2[51:50]}};
        tmp_107_reg_4038 <= {{x_V_6_fu_1209_p2[47:46]}};
        tmp_108_reg_4044 <= {{x_V_6_fu_1209_p2[43:42]}};
        tmp_109_reg_4050 <= {{x_V_6_fu_1209_p2[39:38]}};
        tmp_110_reg_4056 <= {{x_V_6_fu_1209_p2[35:34]}};
        tmp_111_reg_4062 <= {{x_V_6_fu_1209_p2[31:30]}};
        tmp_112_reg_4068 <= {{x_V_6_fu_1209_p2[27:26]}};
        tmp_113_reg_4074 <= {{x_V_6_fu_1209_p2[23:22]}};
        tmp_114_reg_4080 <= {{x_V_6_fu_1209_p2[19:18]}};
        tmp_115_reg_4086 <= {{x_V_6_fu_1209_p2[15:14]}};
        tmp_116_reg_4092 <= {{x_V_6_fu_1209_p2[11:10]}};
        tmp_117_reg_4098 <= {{x_V_6_fu_1209_p2[7:6]}};
        tmp_118_reg_4104 <= {{x_V_6_fu_1209_p2[3:2]}};
        tmp_132_reg_4111 <= {{x_V_6_1_fu_1932_p2[61:60]}};
        tmp_133_reg_4116 <= {{x_V_6_1_fu_1932_p2[57:56]}};
        tmp_137_reg_4008 <= tmp_137_fu_1365_p1;
        tmp_166_reg_4122 <= {{x_V_6_1_fu_1932_p2[53:52]}};
        tmp_167_reg_4128 <= {{x_V_6_1_fu_1932_p2[49:48]}};
        tmp_168_reg_4134 <= {{x_V_6_1_fu_1932_p2[45:44]}};
        tmp_169_reg_4140 <= {{x_V_6_1_fu_1932_p2[41:40]}};
        tmp_170_reg_4146 <= {{x_V_6_1_fu_1932_p2[37:36]}};
        tmp_171_reg_4152 <= {{x_V_6_1_fu_1932_p2[33:32]}};
        tmp_172_reg_4158 <= {{x_V_6_1_fu_1932_p2[29:28]}};
        tmp_173_reg_4164 <= {{x_V_6_1_fu_1932_p2[25:24]}};
        tmp_174_reg_4170 <= {{x_V_6_1_fu_1932_p2[21:20]}};
        tmp_175_reg_4176 <= {{x_V_6_1_fu_1932_p2[17:16]}};
        tmp_176_reg_4182 <= {{x_V_6_1_fu_1932_p2[13:12]}};
        tmp_177_reg_4188 <= {{x_V_6_1_fu_1932_p2[9:8]}};
        tmp_178_reg_4194 <= {{x_V_6_1_fu_1932_p2[5:4]}};
        tmp_179_reg_4207 <= {{x_V_6_1_fu_1932_p2[63:62]}};
        tmp_180_reg_4212 <= {{x_V_6_1_fu_1932_p2[59:58]}};
        tmp_182_reg_4218 <= {{x_V_6_1_fu_1932_p2[55:54]}};
        tmp_183_reg_4224 <= {{x_V_6_1_fu_1932_p2[51:50]}};
        tmp_184_reg_4230 <= {{x_V_6_1_fu_1932_p2[47:46]}};
        tmp_185_reg_4236 <= {{x_V_6_1_fu_1932_p2[43:42]}};
        tmp_186_reg_4242 <= {{x_V_6_1_fu_1932_p2[39:38]}};
        tmp_187_reg_4248 <= {{x_V_6_1_fu_1932_p2[35:34]}};
        tmp_188_reg_4254 <= {{x_V_6_1_fu_1932_p2[31:30]}};
        tmp_189_reg_4260 <= {{x_V_6_1_fu_1932_p2[27:26]}};
        tmp_190_reg_4266 <= {{x_V_6_1_fu_1932_p2[23:22]}};
        tmp_191_reg_4272 <= {{x_V_6_1_fu_1932_p2[19:18]}};
        tmp_192_reg_4278 <= {{x_V_6_1_fu_1932_p2[15:14]}};
        tmp_193_reg_4284 <= {{x_V_6_1_fu_1932_p2[11:10]}};
        tmp_194_reg_4290 <= {{x_V_6_1_fu_1932_p2[7:6]}};
        tmp_195_reg_4296 <= {{x_V_6_1_fu_1932_p2[3:2]}};
        tmp_217_reg_4200 <= tmp_217_fu_2088_p1;
        tmp_22_reg_3919 <= {{x_V_6_fu_1209_p2[61:60]}};
        tmp_23_reg_3924 <= {{x_V_6_fu_1209_p2[57:56]}};
        tmp_89_reg_3930 <= {{x_V_6_fu_1209_p2[53:52]}};
        tmp_90_reg_3936 <= {{x_V_6_fu_1209_p2[49:48]}};
        tmp_91_reg_3942 <= {{x_V_6_fu_1209_p2[45:44]}};
        tmp_92_reg_3948 <= {{x_V_6_fu_1209_p2[41:40]}};
        tmp_93_reg_3954 <= {{x_V_6_fu_1209_p2[37:36]}};
        tmp_94_reg_3960 <= {{x_V_6_fu_1209_p2[33:32]}};
        tmp_95_reg_3966 <= {{x_V_6_fu_1209_p2[29:28]}};
        tmp_96_reg_3972 <= {{x_V_6_fu_1209_p2[25:24]}};
        tmp_97_reg_3978 <= {{x_V_6_fu_1209_p2[21:20]}};
        tmp_98_reg_3984 <= {{x_V_6_fu_1209_p2[17:16]}};
        tmp_99_reg_3990 <= {{x_V_6_fu_1209_p2[13:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_18_reg_3880_pp0_iter1_reg == 1'd1))) begin
        tmp_121_reg_4303 <= {{tmp_44_cast_fu_2496_p2[59:56]}};
        tmp_122_reg_4309 <= {{tmp_44_cast_fu_2496_p2[51:48]}};
        tmp_123_reg_4316 <= {{tmp_44_cast_fu_2496_p2[43:40]}};
        tmp_124_reg_4324 <= {{tmp_44_cast_fu_2496_p2[35:32]}};
        tmp_125_reg_4332 <= {{tmp_44_cast_fu_2496_p2[27:24]}};
        tmp_126_reg_4340 <= {{tmp_44_cast_fu_2496_p2[19:16]}};
        tmp_127_reg_4348 <= {{tmp_44_cast_fu_2496_p2[11:8]}};
        tmp_138_reg_4357 <= tmp_138_fu_2582_p1;
        tmp_198_reg_4368 <= {{tmp_44_1_cast_fu_2842_p2[59:56]}};
        tmp_199_reg_4374 <= {{tmp_44_1_cast_fu_2842_p2[51:48]}};
        tmp_200_reg_4381 <= {{tmp_44_1_cast_fu_2842_p2[43:40]}};
        tmp_201_reg_4389 <= {{tmp_44_1_cast_fu_2842_p2[35:32]}};
        tmp_202_reg_4397 <= {{tmp_44_1_cast_fu_2842_p2[27:24]}};
        tmp_203_reg_4405 <= {{tmp_44_1_cast_fu_2842_p2[19:16]}};
        tmp_204_reg_4413 <= {{tmp_44_1_cast_fu_2842_p2[11:8]}};
        tmp_218_reg_4422 <= tmp_218_fu_2928_p1;
        tmp_31_reg_4363 <= tmp_31_fu_2592_p2;
        tmp_46_reg_4428 <= tmp_46_fu_2938_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_127_reg_4348_pp0_iter3_reg <= tmp_127_reg_4348;
        tmp_18_reg_3880_pp0_iter2_reg <= tmp_18_reg_3880_pp0_iter1_reg;
        tmp_18_reg_3880_pp0_iter3_reg <= tmp_18_reg_3880_pp0_iter2_reg;
        tmp_204_reg_4413_pp0_iter3_reg <= tmp_204_reg_4413;
        tmp_31_reg_4363_pp0_iter3_reg <= tmp_31_reg_4363;
        tmp_46_reg_4428_pp0_iter3_reg <= tmp_46_reg_4428;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_18_reg_3880 <= tmp_18_fu_752_p2;
        tmp_18_reg_3880_pp0_iter1_reg <= tmp_18_reg_3880;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_18_reg_3880_pp0_iter2_reg == 1'd1))) begin
        tmp_35_reg_4433 <= tmp_35_fu_3107_p2;
        tmp_63_reg_4438 <= tmp_63_fu_3276_p2;
    end
end

always @ (*) begin
    if ((tmp_18_fu_752_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_0_0_V_address0 = dmem_0_0_V_addr_reg_3840;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dmem_0_0_V_address0 = tmp_20_fu_776_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd0))) begin
        dmem_0_0_V_address0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd0))) begin
        dmem_0_0_V_address0 = tmp_17_fu_666_p1;
    end else begin
        dmem_0_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd0)))) begin
        dmem_0_0_V_ce0 = 1'b1;
    end else begin
        dmem_0_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_0_0_V_d0 = o_word_V_3_reg_4484;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd0))) begin
        dmem_0_0_V_d0 = p_Result_2_fu_687_p3;
    end else begin
        dmem_0_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (tmp_29_reg_3833 == 1'd0) & (d_o_idx_V_reg_3781 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd0)))) begin
        dmem_0_0_V_we0 = 1'b1;
    end else begin
        dmem_0_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_0_1_V_address0 = dmem_0_1_V_addr_reg_3845;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dmem_0_1_V_address0 = tmp_20_fu_776_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dmem_0_1_V_address0 = tmp_17_fu_666_p1;
    end else begin
        dmem_0_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state3) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        dmem_0_1_V_ce0 = 1'b1;
    end else begin
        dmem_0_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (tmp_29_reg_3833 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd0))) begin
        dmem_0_1_V_we0 = 1'b1;
    end else begin
        dmem_0_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_1_0_V_address0 = dmem_1_0_V_addr_reg_3850;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dmem_1_0_V_address0 = tmp_20_fu_776_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd1))) begin
        dmem_1_0_V_address0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd0))) begin
        dmem_1_0_V_address0 = tmp_17_fu_666_p1;
    end else begin
        dmem_1_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd0)))) begin
        dmem_1_0_V_ce0 = 1'b1;
    end else begin
        dmem_1_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_1_0_V_d0 = o_word_V_3_reg_4484;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd1))) begin
        dmem_1_0_V_d0 = p_Result_2_fu_687_p3;
    end else begin
        dmem_1_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state14) & (tmp_29_reg_3833 == 1'd0) & (d_o_idx_V_reg_3781 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (tmp_15_fu_682_p2 == 1'd1) & (exitcond_fu_636_p2 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd1)))) begin
        dmem_1_0_V_we0 = 1'b1;
    end else begin
        dmem_1_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_1_1_V_address0 = dmem_1_1_V_addr_reg_3855;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dmem_1_1_V_address0 = tmp_20_fu_776_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dmem_1_1_V_address0 = tmp_17_fu_666_p1;
    end else begin
        dmem_1_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state3) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        dmem_1_1_V_ce0 = 1'b1;
    end else begin
        dmem_1_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (tmp_29_reg_3833 == 1'd1) & (d_o_idx_V_reg_3781 == 1'd1))) begin
        dmem_1_1_V_we0 = 1'b1;
    end else begin
        dmem_1_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        kh_mem_V_address0 = tmp_24_fu_3435_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        kh_mem_V_address0 = tmp_27_fu_3394_p1;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10))) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp1_list_ce0 = 1'b1;
    end else begin
        tmp1_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp2_list_ce0 = 1'b1;
    end else begin
        tmp2_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        wt_mem_0_V_ce0 = 1'b1;
    end else begin
        wt_mem_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        wt_mem_1_V_ce0 = 1'b1;
    end else begin
        wt_mem_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_636_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_18_fu_752_p2 == 1'd0)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_18_fu_752_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign best_out_V_1_fu_3695_p3 = ((tmp_14_reg_3812[0:0] === 1'b1) ? p_Val2_9_reg_457 : best_out_V_fu_3691_p1);

assign best_out_V_2_fu_3713_p3 = ((sel_tmp25_demorgan_fu_3708_p2[0:0] === 1'b1) ? best_out_V_1_fu_3695_p3 : p_Val2_9_reg_457);

assign best_out_V_fu_3691_p1 = $signed(p_Val2_s_28_fu_3681_p4);

assign bvh_d_index_fu_3655_p1 = o_offset_V_reg_3863;

assign d_o_idx_V_fu_570_p3 = tmp1_list_q0[32'd20];

assign dmem_0_1_V_d0 = o_word_V_3_reg_4484;

assign dmem_1_1_V_d0 = o_word_V_3_reg_4484;

assign exitcond_fu_636_p2 = ((p_1_reg_481 == tmp_25_reg_3792) ? 1'b1 : 1'b0);

assign i_V_fu_800_p2 = (16'd128 + p_2_reg_505);

assign in_wrd_V_0_phi_fu_806_p3 = ((d_i_idx_V_reg_3775[0:0] === 1'b1) ? dmem_1_0_V_q0 : dmem_0_0_V_q0);

assign in_wrd_V_1_phi_fu_1529_p3 = ((d_i_idx_V_reg_3775[0:0] === 1'b1) ? dmem_1_1_V_q0 : dmem_0_1_V_q0);

assign kh_off_V_1_fu_3399_p1 = p_1_reg_481[0:0];

assign kh_off_V_fu_3459_p1 = p_1_reg_481[1:0];

assign ki_V_2_fu_3417_p3 = ((kh_off_V_1_fu_3399_p1[0:0] === 1'b1) ? loc_V_2_fu_3407_p4 : loc_V_1_fu_3403_p1);

assign layer_type_V_fu_552_p4 = {{tmp1_list_q0[29:28]}};

assign lhs_V_fu_606_p1 = p_Result_s_fu_578_p4;

assign loc_V_1_fu_3403_p1 = kh_mem_V_q0[15:0];

assign loc_V_2_fu_3407_p4 = {{kh_mem_V_q0[47:32]}};

assign loc_V_3_fu_3479_p4 = {{kh_mem_V_q0[31:16]}};

assign loc_V_4_fu_3557_p4 = {{kh_mem_V_q0[47:32]}};

assign loc_V_5_fu_3567_p4 = {{kh_mem_V_q0[63:48]}};

assign loc_V_fu_3469_p1 = kh_mem_V_q0[15:0];

assign nc_V_4_fu_3647_p3 = ((or_cond_fu_3633_p2[0:0] === 1'b1) ? newSel_fu_3625_p3 : newSel1_fu_3639_p3);

assign newSel1_fu_3639_p3 = ((tmp_26_fu_3463_p2[0:0] === 1'b1) ? loc_V_fu_3469_p1 : loc_V_5_fu_3567_p4);

assign newSel_fu_3625_p3 = ((sel_tmp10_fu_3619_p2[0:0] === 1'b1) ? loc_V_4_fu_3557_p4 : loc_V_3_fu_3479_p4);

assign not_s_fu_3658_p2 = (($signed(p_Val2_2_reg_493) < $signed(nc_V_4_fu_3647_p3)) ? 1'b1 : 1'b0);

assign o_V_fu_641_p2 = (p_1_reg_481 + 16'd1);

assign o_offset_V_fu_701_p2 = (tmp_13_reg_3802 + tmp_28_fu_697_p1);

assign o_word_V_2_fu_3721_p3 = ((tmp_14_reg_3812[0:0] === 1'b1) ? p_Result_s_27_fu_3668_p4 : o_word_V_4_reg_3868);

assign o_word_V_3_fu_3727_p3 = ((sel_tmp25_demorgan_fu_3708_p2[0:0] === 1'b1) ? o_word_V_2_fu_3721_p3 : o_word_V_4_reg_3868);

assign o_word_V_4_fu_740_p3 = ((sel_tmp6_fu_736_p2[0:0] === 1'b1) ? dmem_1_1_V_q0 : sel_tmp5_fu_728_p3);

assign or_cond_fu_3633_p2 = (sel_tmp8_fu_3601_p2 | sel_tmp10_fu_3619_p2);

assign p_0839_s_fu_784_p4 = {{r_V_1_fu_761_p2[21:7]}};

assign p_Repl2_s_fu_3664_p1 = not_s_fu_3658_p2;

assign p_Result_1_fu_598_p1 = tmp_1_fu_588_p4;

assign p_Result_2_fu_687_p3 = {{56'd0}, {p_Val2_11_reg_469}};

always @ (*) begin
    p_Result_s_27_fu_3668_p4 = o_word_V_4_reg_3868;
    p_Result_s_27_fu_3668_p4[bvh_d_index_fu_3655_p1] = |(p_Repl2_s_fu_3664_p1);
end

assign p_Result_s_fu_578_p4 = {{tmp1_list_q0[19:8]}};

assign p_Val2_7_fu_3535_p2 = ($signed(tmp_55_cast_fu_3531_p1) + $signed(tmp_53_fu_3495_p1));

assign p_Val2_8_fu_3541_p4 = {{p_Val2_7_fu_3535_p2[33:14]}};

assign p_Val2_s_28_fu_3681_p4 = {{p_Val2_7_fu_3535_p2[33:20]}};

assign p_cast_fu_3374_p1 = $signed(tmp_66_fu_3368_p2);

assign p_s_fu_538_p3 = ((tmp_12_fu_532_p2[0:0] === 1'b1) ? 8'd0 : tmp_s_fu_526_p2);

assign phitmp_1_cast_fu_3354_p1 = tmp_47_1_fu_3346_p3;

assign phitmp_cast_fu_3311_p1 = tmp_39_fu_3303_p3;

assign prediction_V_1_fu_3734_p3 = ((tmp_14_reg_3812[0:0] === 1'b1) ? p_Val2_11_reg_469 : prediction_V_fu_3677_p1);

assign prediction_V_2_fu_3741_p3 = ((sel_tmp25_demorgan_fu_3708_p2[0:0] === 1'b1) ? prediction_V_1_fu_3734_p3 : p_Val2_11_reg_469);

assign prediction_V_fu_3677_p1 = p_1_reg_481[7:0];

assign r_V_10_1_cast_fu_1928_p1 = r_V_10_1_fu_1798_p64;

assign r_V_10_1_fu_1798_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_139_fu_1542_p3}, {1'd0}}, {tmp_140_fu_1550_p3}}, {1'd0}}, {tmp_141_fu_1558_p3}}, {1'd0}}, {tmp_142_fu_1566_p3}}, {1'd0}}, {tmp_143_fu_1574_p3}}, {1'd0}}, {tmp_144_fu_1582_p3}}, {1'd0}}, {tmp_145_fu_1590_p3}}, {1'd0}}, {tmp_146_fu_1598_p3}}, {1'd0}}, {tmp_147_fu_1606_p3}}, {1'd0}}, {tmp_148_fu_1614_p3}}, {1'd0}}, {tmp_149_fu_1622_p3}}, {1'd0}}, {tmp_150_fu_1630_p3}}, {1'd0}}, {tmp_151_fu_1638_p3}}, {1'd0}}, {tmp_152_fu_1646_p3}}, {1'd0}}, {tmp_153_fu_1654_p3}}, {1'd0}}, {tmp_154_fu_1662_p3}}, {1'd0}}, {tmp_155_fu_1670_p3}}, {1'd0}}, {tmp_156_fu_1678_p3}}, {1'd0}}, {tmp_157_fu_1686_p3}}, {1'd0}}, {tmp_158_fu_1694_p3}}, {1'd0}}, {tmp_159_fu_1702_p3}}, {1'd0}}, {tmp_160_fu_1710_p3}}, {1'd0}}, {tmp_161_fu_1718_p3}}, {1'd0}}, {tmp_162_fu_1726_p3}}, {1'd0}}, {tmp_163_fu_1734_p3}}, {1'd0}}, {tmp_164_fu_1742_p3}}, {1'd0}}, {tmp_165_fu_1750_p3}}, {1'd0}}, {tmp_181_fu_1758_p3}}, {1'd0}}, {tmp_207_fu_1766_p3}}, {1'd0}}, {tmp_211_fu_1774_p3}}, {1'd0}}, {tmp_215_fu_1782_p3}}, {1'd0}}, {tmp_216_fu_1790_p3}};

assign r_V_10_cast_fu_3077_p1 = tmp_131_fu_3067_p4;

assign r_V_11_1_cast_fu_2648_p1 = r_V_11_1_fu_2598_p32;

assign r_V_11_1_fu_2598_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_132_reg_4111}, {2'd0}}, {tmp_133_reg_4116}}, {2'd0}}, {tmp_166_reg_4122}}, {2'd0}}, {tmp_167_reg_4128}}, {2'd0}}, {tmp_168_reg_4134}}, {2'd0}}, {tmp_169_reg_4140}}, {2'd0}}, {tmp_170_reg_4146}}, {2'd0}}, {tmp_171_reg_4152}}, {2'd0}}, {tmp_172_reg_4158}}, {2'd0}}, {tmp_173_reg_4164}}, {2'd0}}, {tmp_174_reg_4170}}, {2'd0}}, {tmp_175_reg_4176}}, {2'd0}}, {tmp_176_reg_4182}}, {2'd0}}, {tmp_177_reg_4188}}, {2'd0}}, {tmp_178_reg_4194}}, {2'd0}}, {tmp_217_reg_4200}};

assign r_V_12_1_cast_fu_2702_p1 = r_V_12_1_fu_2652_p32;

assign r_V_12_1_fu_2652_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_179_reg_4207}, {2'd0}}, {tmp_180_reg_4212}}, {2'd0}}, {tmp_182_reg_4218}}, {2'd0}}, {tmp_183_reg_4224}}, {2'd0}}, {tmp_184_reg_4230}}, {2'd0}}, {tmp_185_reg_4236}}, {2'd0}}, {tmp_186_reg_4242}}, {2'd0}}, {tmp_187_reg_4248}}, {2'd0}}, {tmp_188_reg_4254}}, {2'd0}}, {tmp_189_reg_4260}}, {2'd0}}, {tmp_190_reg_4266}}, {2'd0}}, {tmp_191_reg_4272}}, {2'd0}}, {tmp_192_reg_4278}}, {2'd0}}, {tmp_193_reg_4284}}, {2'd0}}, {tmp_194_reg_4290}}, {2'd0}}, {tmp_195_reg_4296}};

assign r_V_13_1_cast_fu_3170_p1 = r_V_13_1_fu_3143_p14;

assign r_V_13_1_fu_3143_p14 = {{{{{{{{{{{{{tmp_198_reg_4368}, {4'd0}}, {tmp_199_reg_4374}}, {4'd0}}, {tmp_200_reg_4381}}, {4'd0}}, {tmp_201_reg_4389}}, {4'd0}}, {tmp_202_reg_4397}}, {4'd0}}, {tmp_203_reg_4405}}, {4'd0}}, {tmp_204_reg_4413}};

assign r_V_14_1_cast_fu_3246_p1 = tmp_208_fu_3236_p4;

assign r_V_15_1_fu_1536_p2 = (wt_mem_1_V_q0 ^ in_wrd_V_1_phi_fu_1529_p3);

assign r_V_1_fu_761_p2 = (rhs_V_2_cast_fu_757_p1 + r_V_2_reg_3875);

assign r_V_2_fu_3749_p0 = rhs_V_1_cast_reg_3807;

assign r_V_2_fu_3749_p1 = r_V_2_fu_3749_p10;

assign r_V_2_fu_3749_p10 = p_1_reg_481;

assign r_V_3_fu_3425_p4 = {{p_1_reg_481[15:2]}};

assign r_V_4_fu_3384_p4 = {{p_1_reg_481[15:1]}};

assign r_V_5_fu_766_p4 = {{p_2_reg_505[15:7]}};

assign r_V_6_cast_fu_1205_p1 = r_V_6_fu_1075_p64;

assign r_V_6_fu_1075_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_32_fu_819_p3}, {1'd0}}, {tmp_38_fu_827_p3}}, {1'd0}}, {tmp_51_fu_835_p3}}, {1'd0}}, {tmp_56_fu_843_p3}}, {1'd0}}, {tmp_61_fu_851_p3}}, {1'd0}}, {tmp_67_fu_859_p3}}, {1'd0}}, {tmp_68_fu_867_p3}}, {1'd0}}, {tmp_69_fu_875_p3}}, {1'd0}}, {tmp_70_fu_883_p3}}, {1'd0}}, {tmp_71_fu_891_p3}}, {1'd0}}, {tmp_72_fu_899_p3}}, {1'd0}}, {tmp_73_fu_907_p3}}, {1'd0}}, {tmp_74_fu_915_p3}}, {1'd0}}, {tmp_75_fu_923_p3}}, {1'd0}}, {tmp_76_fu_931_p3}}, {1'd0}}, {tmp_77_fu_939_p3}}, {1'd0}}, {tmp_78_fu_947_p3}}, {1'd0}}, {tmp_79_fu_955_p3}}, {1'd0}}, {tmp_80_fu_963_p3}}, {1'd0}}, {tmp_81_fu_971_p3}}, {1'd0}}, {tmp_82_fu_979_p3}}, {1'd0}}, {tmp_83_fu_987_p3}}, {1'd0}}, {tmp_84_fu_995_p3}}, {1'd0}}, {tmp_85_fu_1003_p3}}, {1'd0}}, {tmp_86_fu_1011_p3}}, {1'd0}}, {tmp_87_fu_1019_p3}}, {1'd0}}, {tmp_88_fu_1027_p3}}, {1'd0}}, {tmp_104_fu_1035_p3}}, {1'd0}}, {tmp_130_fu_1043_p3}}, {1'd0}}, {tmp_134_fu_1051_p3}}, {1'd0}}, {tmp_135_fu_1059_p3}}, {1'd0}}, {tmp_136_fu_1067_p3}};

assign r_V_7_cast_fu_2302_p1 = r_V_7_fu_2252_p32;

assign r_V_7_fu_2252_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_22_reg_3919}, {2'd0}}, {tmp_23_reg_3924}}, {2'd0}}, {tmp_89_reg_3930}}, {2'd0}}, {tmp_90_reg_3936}}, {2'd0}}, {tmp_91_reg_3942}}, {2'd0}}, {tmp_92_reg_3948}}, {2'd0}}, {tmp_93_reg_3954}}, {2'd0}}, {tmp_94_reg_3960}}, {2'd0}}, {tmp_95_reg_3966}}, {2'd0}}, {tmp_96_reg_3972}}, {2'd0}}, {tmp_97_reg_3978}}, {2'd0}}, {tmp_98_reg_3984}}, {2'd0}}, {tmp_99_reg_3990}}, {2'd0}}, {tmp_100_reg_3996}}, {2'd0}}, {tmp_101_reg_4002}}, {2'd0}}, {tmp_137_reg_4008}};

assign r_V_8_cast_fu_2356_p1 = r_V_8_fu_2306_p32;

assign r_V_8_fu_2306_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_102_reg_4015}, {2'd0}}, {tmp_103_reg_4020}}, {2'd0}}, {tmp_105_reg_4026}}, {2'd0}}, {tmp_106_reg_4032}}, {2'd0}}, {tmp_107_reg_4038}}, {2'd0}}, {tmp_108_reg_4044}}, {2'd0}}, {tmp_109_reg_4050}}, {2'd0}}, {tmp_110_reg_4056}}, {2'd0}}, {tmp_111_reg_4062}}, {2'd0}}, {tmp_112_reg_4068}}, {2'd0}}, {tmp_113_reg_4074}}, {2'd0}}, {tmp_114_reg_4080}}, {2'd0}}, {tmp_115_reg_4086}}, {2'd0}}, {tmp_116_reg_4092}}, {2'd0}}, {tmp_117_reg_4098}}, {2'd0}}, {tmp_118_reg_4104}};

assign r_V_9_cast_fu_3001_p1 = r_V_9_fu_2974_p14;

assign r_V_9_fu_2974_p14 = {{{{{{{{{{{{{tmp_121_reg_4303}, {4'd0}}, {tmp_122_reg_4309}}, {4'd0}}, {tmp_123_reg_4316}}, {4'd0}}, {tmp_124_reg_4324}}, {4'd0}}, {tmp_125_reg_4332}}, {4'd0}}, {tmp_126_reg_4340}}, {4'd0}}, {tmp_127_reg_4348}};

assign r_V_fu_651_p2 = (lhs_V_reg_3797 + rhs_V_fu_647_p1);

assign r_V_s_fu_813_p2 = (wt_mem_0_V_q0 ^ in_wrd_V_0_phi_fu_806_p3);

assign rhs_V_1_cast_fu_620_p1 = tmp_1_fu_588_p4;

assign rhs_V_2_cast_fu_757_p1 = p_2_reg_505;

assign rhs_V_fu_647_p1 = p_1_reg_481;

assign sel_tmp10_fu_3619_p2 = (tmp_50_fu_3489_p2 & sel_tmp9_fu_3613_p2);

assign sel_tmp17_demorgan_fu_3607_p2 = (tmp_49_fu_3473_p2 | tmp_26_fu_3463_p2);

assign sel_tmp1_fu_706_p2 = (tmp_29_reg_3833 & sel_tmp_reg_3820);

assign sel_tmp25_demorgan_fu_3708_p2 = (tmp_14_reg_3812 | tmp47_fu_3702_p2);

assign sel_tmp2_fu_710_p3 = ((sel_tmp1_fu_706_p2[0:0] === 1'b1) ? dmem_0_1_V_q0 : dmem_0_0_V_q0);

assign sel_tmp3_fu_718_p2 = (tmp_29_reg_3833 ^ 1'd1);

assign sel_tmp4_fu_723_p2 = (sel_tmp3_fu_718_p2 & d_o_idx_V_reg_3781);

assign sel_tmp5_fu_728_p3 = ((sel_tmp4_fu_723_p2[0:0] === 1'b1) ? dmem_1_0_V_q0 : sel_tmp2_fu_710_p3);

assign sel_tmp6_fu_736_p2 = (tmp_29_reg_3833 & d_o_idx_V_reg_3781);

assign sel_tmp7_fu_3595_p2 = (tmp_26_fu_3463_p2 ^ 1'd1);

assign sel_tmp8_fu_3601_p2 = (tmp_49_fu_3473_p2 & sel_tmp7_fu_3595_p2);

assign sel_tmp9_fu_3613_p2 = (sel_tmp17_demorgan_fu_3607_p2 ^ 1'd1);

assign sel_tmp_fu_630_p2 = (d_o_idx_V_fu_570_p3 ^ 1'd1);

assign sum_V_1_fu_3378_p2 = ($signed(p_cast_fu_3374_p1) + $signed(p_Val2_2_reg_493));

assign tmp1_list_address0 = tmp_fu_520_p1;

assign tmp2_list_address0 = tmp_fu_520_p1;

assign tmp44_fu_2932_p2 = (tmp_45_fu_2848_p4 + tmp_65_cast_fu_2816_p1);

assign tmp47_fu_3702_p2 = (tmp_64_fu_3589_p2 | tmp_57_fu_3551_p2);

assign tmp6_fu_2586_p2 = (tmp_30_fu_2502_p4 + tmp_32_cast_fu_2470_p1);

assign tmp_104_fu_1035_p3 = r_V_s_fu_813_p2[32'd9];

assign tmp_10_fu_3285_p3 = {{3'd0}, {tmp_127_reg_4348_pp0_iter3_reg}};

assign tmp_119_fu_2458_p2 = (r_V_8_fu_2306_p32 + r_V_7_fu_2252_p32);

assign tmp_120_fu_2476_p4 = {{x_V_fu_2464_p2[62:4]}};

assign tmp_128_fu_2997_p1 = r_V_9_fu_2974_p14;

assign tmp_129_fu_3049_p2 = (tmp_128_fu_2997_p1 + x_V_2_fu_2944_p16);

assign tmp_12_fu_532_p2 = ((tmp_s_fu_526_p2 == 8'd37) ? 1'b1 : 1'b0);

assign tmp_130_fu_1043_p3 = r_V_s_fu_813_p2[32'd7];

assign tmp_131_fu_3067_p4 = {{x_V_3_fu_3055_p2[60:16]}};

assign tmp_134_fu_1051_p3 = r_V_s_fu_813_p2[32'd5];

assign tmp_135_fu_1059_p3 = r_V_s_fu_813_p2[32'd3];

assign tmp_136_fu_1067_p3 = r_V_s_fu_813_p2[32'd1];

assign tmp_137_fu_1365_p1 = x_V_6_fu_1209_p2[1:0];

assign tmp_138_fu_2582_p1 = tmp_44_cast_fu_2496_p2[3:0];

assign tmp_139_fu_1542_p3 = r_V_15_1_fu_1536_p2[32'd63];

assign tmp_140_fu_1550_p3 = r_V_15_1_fu_1536_p2[32'd61];

assign tmp_141_fu_1558_p3 = r_V_15_1_fu_1536_p2[32'd59];

assign tmp_142_fu_1566_p3 = r_V_15_1_fu_1536_p2[32'd57];

assign tmp_143_fu_1574_p3 = r_V_15_1_fu_1536_p2[32'd55];

assign tmp_144_fu_1582_p3 = r_V_15_1_fu_1536_p2[32'd53];

assign tmp_145_fu_1590_p3 = r_V_15_1_fu_1536_p2[32'd51];

assign tmp_146_fu_1598_p3 = r_V_15_1_fu_1536_p2[32'd49];

assign tmp_147_fu_1606_p3 = r_V_15_1_fu_1536_p2[32'd47];

assign tmp_148_fu_1614_p3 = r_V_15_1_fu_1536_p2[32'd45];

assign tmp_149_fu_1622_p3 = r_V_15_1_fu_1536_p2[32'd43];

assign tmp_14_fu_624_p2 = ((layer_type_V_fu_552_p4 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_150_fu_1630_p3 = r_V_15_1_fu_1536_p2[32'd41];

assign tmp_151_fu_1638_p3 = r_V_15_1_fu_1536_p2[32'd39];

assign tmp_152_fu_1646_p3 = r_V_15_1_fu_1536_p2[32'd37];

assign tmp_153_fu_1654_p3 = r_V_15_1_fu_1536_p2[32'd35];

assign tmp_154_fu_1662_p3 = r_V_15_1_fu_1536_p2[32'd33];

assign tmp_155_fu_1670_p3 = r_V_15_1_fu_1536_p2[32'd31];

assign tmp_156_fu_1678_p3 = r_V_15_1_fu_1536_p2[32'd29];

assign tmp_157_fu_1686_p3 = r_V_15_1_fu_1536_p2[32'd27];

assign tmp_158_fu_1694_p3 = r_V_15_1_fu_1536_p2[32'd25];

assign tmp_159_fu_1702_p3 = r_V_15_1_fu_1536_p2[32'd23];

assign tmp_15_fu_682_p2 = ((layer_type_V_reg_3770 == 2'd3) ? 1'b1 : 1'b0);

assign tmp_160_fu_1710_p3 = r_V_15_1_fu_1536_p2[32'd21];

assign tmp_161_fu_1718_p3 = r_V_15_1_fu_1536_p2[32'd19];

assign tmp_162_fu_1726_p3 = r_V_15_1_fu_1536_p2[32'd17];

assign tmp_163_fu_1734_p3 = r_V_15_1_fu_1536_p2[32'd15];

assign tmp_164_fu_1742_p3 = r_V_15_1_fu_1536_p2[32'd13];

assign tmp_165_fu_1750_p3 = r_V_15_1_fu_1536_p2[32'd11];

assign tmp_16_fu_656_p4 = {{r_V_fu_651_p2[16:7]}};

assign tmp_17_fu_666_p1 = tmp_16_fu_656_p4;

assign tmp_181_fu_1758_p3 = r_V_15_1_fu_1536_p2[32'd9];

assign tmp_18_fu_752_p2 = ((p_2_reg_505 < p_Result_1_reg_3787) ? 1'b1 : 1'b0);

assign tmp_196_fu_2804_p2 = (r_V_12_1_fu_2652_p32 + r_V_11_1_fu_2598_p32);

assign tmp_197_fu_2822_p4 = {{x_V_1_fu_2810_p2[62:4]}};

assign tmp_1_fu_588_p4 = {{tmp2_list_q0[29:16]}};

assign tmp_205_fu_3166_p1 = r_V_13_1_fu_3143_p14;

assign tmp_206_fu_3218_p2 = (tmp_205_fu_3166_p1 + x_V_2_1_fu_3113_p16);

assign tmp_207_fu_1766_p3 = r_V_15_1_fu_1536_p2[32'd7];

assign tmp_208_fu_3236_p4 = {{x_V_3_1_fu_3224_p2[60:16]}};

assign tmp_209_fu_3498_p4 = {{kh_word_V_2_reg_4458[63:48]}};

assign tmp_20_fu_776_p1 = r_V_5_fu_766_p4;

assign tmp_210_fu_3507_p4 = {{kh_word_V_2_reg_4458[31:16]}};

assign tmp_211_fu_1774_p3 = r_V_15_1_fu_1536_p2[32'd5];

assign tmp_212_fu_3516_p3 = ((kh_off_V_1_reg_4453[0:0] === 1'b1) ? tmp_209_fu_3498_p4 : tmp_210_fu_3507_p4);

assign tmp_215_fu_1782_p3 = r_V_15_1_fu_1536_p2[32'd3];

assign tmp_216_fu_1790_p3 = r_V_15_1_fu_1536_p2[32'd1];

assign tmp_217_fu_2088_p1 = x_V_6_1_fu_1932_p2[1:0];

assign tmp_218_fu_2928_p1 = tmp_44_1_cast_fu_2842_p2[3:0];

assign tmp_21_fu_794_p1 = p_0839_s_fu_784_p4;

assign tmp_223_fu_3440_p1 = p_Val2_2_reg_493[9:0];

assign tmp_24_fu_3435_p1 = r_V_3_fu_3425_p4;

assign tmp_25_fu_602_p1 = tmp2_list_q0[15:0];

assign tmp_26_fu_3463_p2 = ((kh_off_V_fu_3459_p1 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_27_fu_3394_p1 = r_V_4_fu_3384_p4;

assign tmp_28_fu_697_p1 = p_1_reg_481[5:0];

assign tmp_2_fu_2360_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_23_reg_3924}}}, {2'd0}}}, {tmp_89_reg_3930}}}, {2'd0}}}, {tmp_90_reg_3936}}}, {2'd0}}}, {tmp_91_reg_3942}}}, {2'd0}}}, {tmp_92_reg_3948}}}, {2'd0}}}, {tmp_93_reg_3954}}}, {2'd0}}}, {tmp_94_reg_3960}}}, {2'd0}}}, {tmp_95_reg_3966}}}, {2'd0}}}, {tmp_96_reg_3972}}}, {2'd0}}}, {tmp_97_reg_3978}}}, {2'd0}}}, {tmp_98_reg_3984}}}, {2'd0}}}, {tmp_99_reg_3990}}}, {2'd0}}}, {tmp_100_reg_3996}}}, {2'd0}}}, {tmp_101_reg_4002}}}, {2'd0}}}, {tmp_137_reg_4008}};

assign tmp_30_fu_2502_p4 = {{tmp_119_fu_2458_p2[7:4]}};

assign tmp_31_fu_2592_p2 = (tmp_33_cast_fu_2473_p1 + tmp6_fu_2586_p2);

assign tmp_32_cast_fu_2470_p1 = tmp_137_reg_4008;

assign tmp_32_fu_819_p3 = r_V_s_fu_813_p2[32'd63];

assign tmp_33_cast_fu_2473_p1 = tmp_118_reg_4104;

assign tmp_33_fu_3087_p4 = {{x_V_4_fu_3081_p2[38:32]}};

assign tmp_34_fu_3097_p4 = {{tmp_129_fu_3049_p2[22:16]}};

assign tmp_35_fu_3107_p2 = (tmp_34_fu_3097_p4 + tmp_33_fu_3087_p4);

assign tmp_36_fu_3292_p2 = (tmp_10_fu_3285_p3 + tmp_9_fu_3282_p1);

assign tmp_37_fu_3298_p2 = (tmp_35_reg_4433 + tmp_36_fu_3292_p2);

assign tmp_38_fu_827_p3 = r_V_s_fu_813_p2[32'd61];

assign tmp_39_fu_3303_p3 = {{tmp_37_fu_3298_p2}, {1'd0}};

assign tmp_3_fu_2409_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_103_reg_4020}}}, {2'd0}}}, {tmp_105_reg_4026}}}, {2'd0}}}, {tmp_106_reg_4032}}}, {2'd0}}}, {tmp_107_reg_4038}}}, {2'd0}}}, {tmp_108_reg_4044}}}, {2'd0}}}, {tmp_109_reg_4050}}}, {2'd0}}}, {tmp_110_reg_4056}}}, {2'd0}}}, {tmp_111_reg_4062}}}, {2'd0}}}, {tmp_112_reg_4068}}}, {2'd0}}}, {tmp_113_reg_4074}}}, {2'd0}}}, {tmp_114_reg_4080}}}, {2'd0}}}, {tmp_115_reg_4086}}}, {2'd0}}}, {tmp_116_reg_4092}}}, {2'd0}}}, {tmp_117_reg_4098}}}, {2'd0}}}, {tmp_118_reg_4104}};

assign tmp_40_fu_3315_p2 = (9'd64 - phitmp_cast_fu_3311_p1);

assign tmp_41_fu_2706_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_133_reg_4116}}}, {2'd0}}}, {tmp_166_reg_4122}}}, {2'd0}}}, {tmp_167_reg_4128}}}, {2'd0}}}, {tmp_168_reg_4134}}}, {2'd0}}}, {tmp_169_reg_4140}}}, {2'd0}}}, {tmp_170_reg_4146}}}, {2'd0}}}, {tmp_171_reg_4152}}}, {2'd0}}}, {tmp_172_reg_4158}}}, {2'd0}}}, {tmp_173_reg_4164}}}, {2'd0}}}, {tmp_174_reg_4170}}}, {2'd0}}}, {tmp_175_reg_4176}}}, {2'd0}}}, {tmp_176_reg_4182}}}, {2'd0}}}, {tmp_177_reg_4188}}}, {2'd0}}}, {tmp_178_reg_4194}}}, {2'd0}}}, {tmp_217_reg_4200}};

assign tmp_42_fu_2755_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_180_reg_4212}}}, {2'd0}}}, {tmp_182_reg_4218}}}, {2'd0}}}, {tmp_183_reg_4224}}}, {2'd0}}}, {tmp_184_reg_4230}}}, {2'd0}}}, {tmp_185_reg_4236}}}, {2'd0}}}, {tmp_186_reg_4242}}}, {2'd0}}}, {tmp_187_reg_4248}}}, {2'd0}}}, {tmp_188_reg_4254}}}, {2'd0}}}, {tmp_189_reg_4260}}}, {2'd0}}}, {tmp_190_reg_4266}}}, {2'd0}}}, {tmp_191_reg_4272}}}, {2'd0}}}, {tmp_192_reg_4278}}}, {2'd0}}}, {tmp_193_reg_4284}}}, {2'd0}}}, {tmp_194_reg_4290}}}, {2'd0}}}, {tmp_195_reg_4296}};

assign tmp_43_fu_2832_p1 = tmp_197_fu_2822_p4;

assign tmp_44_1_cast_fu_2842_p2 = (tmp_44_fu_2836_p2 + tmp_43_fu_2832_p1);

assign tmp_44_cast_fu_2496_p2 = (tmp_5_fu_2490_p2 + tmp_4_fu_2486_p1);

assign tmp_44_fu_2836_p2 = (tmp_42_fu_2755_p31 + tmp_41_fu_2706_p31);

assign tmp_45_fu_2848_p4 = {{tmp_196_fu_2804_p2[7:4]}};

assign tmp_4616_s_fu_3341_p2 = (tmp_63_reg_4438 + tmp_65_fu_3335_p2);

assign tmp_46_fu_2938_p2 = (tmp_66_cast_fu_2819_p1 + tmp44_fu_2932_p2);

assign tmp_47_1_fu_3346_p3 = {{tmp_4616_s_fu_3341_p2}, {1'd0}};

assign tmp_47_fu_3174_p13 = {{{{{{{{{{{{{{{{{{{{{{3'd0}, {tmp_200_reg_4381}}}, {4'd0}}}, {tmp_201_reg_4389}}}, {4'd0}}}, {tmp_202_reg_4397}}}, {4'd0}}}, {tmp_203_reg_4405}}}, {4'd0}}}, {tmp_204_reg_4413}}}, {4'd0}}}, {tmp_218_reg_4422}};

assign tmp_48_1_cast_fu_3364_p1 = $signed(tmp_48_1_fu_3358_p2);

assign tmp_48_1_fu_3358_p2 = (9'd64 - phitmp_1_cast_fu_3354_p1);

assign tmp_48_cast_fu_3321_p1 = $signed(tmp_40_fu_3315_p2);

assign tmp_48_fu_3196_p13 = {{{{{{{{{{{{{{{{{{{{{{3'd0}, {tmp_199_reg_4374}}}, {4'd0}}}, {tmp_200_reg_4381}}}, {4'd0}}}, {tmp_201_reg_4389}}}, {4'd0}}}, {tmp_202_reg_4397}}}, {4'd0}}}, {tmp_203_reg_4405}}}, {4'd0}}}, {tmp_204_reg_4413}};

assign tmp_49_fu_3473_p2 = ((kh_off_V_fu_3459_p1 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_4_fu_2486_p1 = tmp_120_fu_2476_p4;

assign tmp_50_fu_3489_p2 = ((kh_off_V_fu_3459_p1 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_51_fu_835_p3 = r_V_s_fu_813_p2[32'd59];

assign tmp_52_fu_3444_p3 = {{tmp_223_fu_3440_p1}, {10'd0}};

assign tmp_53_fu_3495_p1 = $unsigned(p_Val2_5_reg_4474);

assign tmp_54_fu_3325_p1 = tmp_46_reg_4428_pp0_iter3_reg;

assign tmp_55_cast_fu_3531_p1 = $signed(tmp_55_fu_3523_p3);

assign tmp_55_fu_3523_p3 = {{tmp_212_fu_3516_p3}, {12'd0}};

assign tmp_56_fu_843_p3 = r_V_s_fu_813_p2[32'd57];

assign tmp_57_fu_3551_p2 = ((p_1_reg_481 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_58_fu_3328_p3 = {{3'd0}, {tmp_204_reg_4413_pp0_iter3_reg}};

assign tmp_59_fu_3256_p4 = {{x_V_4_1_fu_3250_p2[38:32]}};

assign tmp_5_fu_2490_p2 = (tmp_3_fu_2409_p31 + tmp_2_fu_2360_p31);

assign tmp_60_cast_fu_3577_p1 = $signed(p_Val2_8_fu_3541_p4);

assign tmp_60_fu_3266_p4 = {{tmp_206_fu_3218_p2[22:16]}};

assign tmp_61_fu_851_p3 = r_V_s_fu_813_p2[32'd55];

assign tmp_62_fu_3581_p3 = {{p_Val2_9_reg_457}, {6'd0}};

assign tmp_63_fu_3276_p2 = (tmp_60_fu_3266_p4 + tmp_59_fu_3256_p4);

assign tmp_64_fu_3589_p2 = (($signed(tmp_60_cast_fu_3577_p1) > $signed(tmp_62_fu_3581_p3)) ? 1'b1 : 1'b0);

assign tmp_65_cast_fu_2816_p1 = tmp_217_reg_4200;

assign tmp_65_fu_3335_p2 = (tmp_58_fu_3328_p3 + tmp_54_fu_3325_p1);

assign tmp_66_cast_fu_2819_p1 = tmp_195_reg_4296;

assign tmp_66_fu_3368_p2 = ($signed(tmp_48_cast_fu_3321_p1) + $signed(tmp_48_1_cast_fu_3364_p1));

assign tmp_67_fu_859_p3 = r_V_s_fu_813_p2[32'd53];

assign tmp_68_fu_867_p3 = r_V_s_fu_813_p2[32'd51];

assign tmp_69_fu_875_p3 = r_V_s_fu_813_p2[32'd49];

assign tmp_70_fu_883_p3 = r_V_s_fu_813_p2[32'd47];

assign tmp_71_fu_891_p3 = r_V_s_fu_813_p2[32'd45];

assign tmp_72_fu_899_p3 = r_V_s_fu_813_p2[32'd43];

assign tmp_73_fu_907_p3 = r_V_s_fu_813_p2[32'd41];

assign tmp_74_fu_915_p3 = r_V_s_fu_813_p2[32'd39];

assign tmp_75_fu_923_p3 = r_V_s_fu_813_p2[32'd37];

assign tmp_76_fu_931_p3 = r_V_s_fu_813_p2[32'd35];

assign tmp_77_fu_939_p3 = r_V_s_fu_813_p2[32'd33];

assign tmp_78_fu_947_p3 = r_V_s_fu_813_p2[32'd31];

assign tmp_79_fu_955_p3 = r_V_s_fu_813_p2[32'd29];

assign tmp_7_fu_3005_p13 = {{{{{{{{{{{{{{{{{{{{{{3'd0}, {tmp_123_reg_4316}}}, {4'd0}}}, {tmp_124_reg_4324}}}, {4'd0}}}, {tmp_125_reg_4332}}}, {4'd0}}}, {tmp_126_reg_4340}}}, {4'd0}}}, {tmp_127_reg_4348}}}, {4'd0}}}, {tmp_138_reg_4357}};

assign tmp_80_fu_963_p3 = r_V_s_fu_813_p2[32'd27];

assign tmp_81_fu_971_p3 = r_V_s_fu_813_p2[32'd25];

assign tmp_82_fu_979_p3 = r_V_s_fu_813_p2[32'd23];

assign tmp_83_fu_987_p3 = r_V_s_fu_813_p2[32'd21];

assign tmp_84_fu_995_p3 = r_V_s_fu_813_p2[32'd19];

assign tmp_85_fu_1003_p3 = r_V_s_fu_813_p2[32'd17];

assign tmp_86_fu_1011_p3 = r_V_s_fu_813_p2[32'd15];

assign tmp_87_fu_1019_p3 = r_V_s_fu_813_p2[32'd13];

assign tmp_88_fu_1027_p3 = r_V_s_fu_813_p2[32'd11];

assign tmp_8_fu_3027_p13 = {{{{{{{{{{{{{{{{{{{{{{3'd0}, {tmp_122_reg_4309}}}, {4'd0}}}, {tmp_123_reg_4316}}}, {4'd0}}}, {tmp_124_reg_4324}}}, {4'd0}}}, {tmp_125_reg_4332}}}, {4'd0}}}, {tmp_126_reg_4340}}}, {4'd0}}}, {tmp_127_reg_4348}};

assign tmp_9_fu_3282_p1 = tmp_31_reg_4363_pp0_iter3_reg;

assign tmp_fu_520_p0 = ctrl_i;

assign tmp_fu_520_p1 = tmp_fu_520_p0;

assign tmp_s_fu_526_p1 = ctrl_i;

assign tmp_s_fu_526_p2 = ($signed(8'd1) + $signed(tmp_s_fu_526_p1));

assign wt_mem_0_V_address0 = tmp_21_fu_794_p1;

assign wt_mem_1_V_address0 = tmp_21_fu_794_p1;

assign x_V_1_fu_2810_p2 = (r_V_11_1_cast_fu_2648_p1 + r_V_12_1_cast_fu_2702_p1);

assign x_V_2_1_cast_fu_3139_p1 = x_V_2_1_fu_3113_p16;

assign x_V_2_1_fu_3113_p16 = {{{{{{{{{{{{{{{tmp_198_reg_4368}, {4'd0}}, {tmp_199_reg_4374}}, {4'd0}}, {tmp_200_reg_4381}}, {4'd0}}, {tmp_201_reg_4389}}, {4'd0}}, {tmp_202_reg_4397}}, {4'd0}}, {tmp_203_reg_4405}}, {4'd0}}, {tmp_204_reg_4413}}, {4'd0}}, {tmp_218_reg_4422}};

assign x_V_2_cast_fu_2970_p1 = x_V_2_fu_2944_p16;

assign x_V_2_fu_2944_p16 = {{{{{{{{{{{{{{{tmp_121_reg_4303}, {4'd0}}, {tmp_122_reg_4309}}, {4'd0}}, {tmp_123_reg_4316}}, {4'd0}}, {tmp_124_reg_4324}}, {4'd0}}, {tmp_125_reg_4332}}, {4'd0}}, {tmp_126_reg_4340}}, {4'd0}}, {tmp_127_reg_4348}}, {4'd0}}, {tmp_138_reg_4357}};

assign x_V_3_1_cast_fu_3230_p2 = (tmp_48_fu_3196_p13 + tmp_47_fu_3174_p13);

assign x_V_3_1_fu_3224_p2 = (x_V_2_1_cast_fu_3139_p1 + r_V_13_1_cast_fu_3170_p1);

assign x_V_3_cast_fu_3061_p2 = (tmp_8_fu_3027_p13 + tmp_7_fu_3005_p13);

assign x_V_3_fu_3055_p2 = (x_V_2_cast_fu_2970_p1 + r_V_9_cast_fu_3001_p1);

assign x_V_4_1_fu_3250_p2 = (x_V_3_1_cast_fu_3230_p2 + r_V_14_1_cast_fu_3246_p1);

assign x_V_4_fu_3081_p2 = (x_V_3_cast_fu_3061_p2 + r_V_10_cast_fu_3077_p1);

assign x_V_6_1_fu_1932_p2 = (r_V_15_1_fu_1536_p2 - r_V_10_1_cast_fu_1928_p1);

assign x_V_6_fu_1209_p2 = (r_V_s_fu_813_p2 - r_V_6_cast_fu_1205_p1);

assign x_V_fu_2464_p2 = (r_V_7_cast_fu_2302_p1 + r_V_8_cast_fu_2356_p1);

always @ (posedge ap_clk) begin
    p_Result_1_reg_3787[15:14] <= 2'b00;
    lhs_V_reg_3797[16:12] <= 5'b00000;
    rhs_V_1_cast_reg_3807[21:14] <= 8'b00000000;
end

endmodule //bin_dense
